"""Hand-entered GURPS cases, reconstructed from knowledge; source audit pending.

Intended references: Lite 28-30; Basic Set Campaigns B378-381, B419-423.
These expected results are not generated by the implementation.
"""

import pytest
from pydantic import ValidationError as SchemaError

from wayfarer.engine.rules.checks import RecordedDice
from wayfarer.engine.rules.injury_types import InjuryStatus
from wayfarer.engine.simulation.gurps_equipment import DamageType
from wayfarer.engine.simulation.injury import InjuryTurn, Wound, apply_injury, impaired_movement
from wayfarer.engine.simulation.resources import Pool, ResourceState
from wayfarer.errors import ConflictError, ValidationError


def state(hp: int = 10) -> ResourceState:
    return ResourceState(
        pools=(
            Pool(
                id="hp:a",
                current=hp,
                maximum=10,
                injury=InjuryStatus(profile_id="gurps-basic-set-4e-2004"),
            ),
        )
    )


def wound(
    damage: int, kind: DamageType = "cr", resistance: int = 0, revision: int = 0, id: str = "hit"
) -> Wound:
    return Wound(
        id=id,
        actor_id="a",
        expected_revision=revision,
        basic_damage=damage,
        resistance=resistance,
        damage_type=kind,
    )


@pytest.mark.parametrize(
    "kind,damage,dr,expected",
    [
        ("cut", 5, 2, 4),
        ("imp", 5, 2, 6),
        ("pi-", 1, 0, 1),
        ("pi-", 5, 0, 2),
        ("pi+", 3, 0, 4),
        ("pi++", 3, 0, 6),
        ("burn", 5, 5, 0),
        ("cr", 4, 0, 4),
        ("tox", 3, 0, 3),
    ],
)
def test_torso_factors(kind: DamageType, damage: int, dr: int, expected: int) -> None:
    updated, trace = apply_injury(
        state(), wound(damage, kind, dr), ht=12, rng=RecordedDice([3, 3, 3]), system=True
    )
    assert trace.injury == expected
    assert updated.pools[0].current == 10 - expected


def test_overkill_thresholds_and_retry_after_reload() -> None:
    dice = RecordedDice([3, 3, 3] * 4)
    updated, trace = apply_injury(state(), wound(45), ht=12, rng=dice, system=True)
    assert updated.pools[0].current == -35
    assert [c.threshold for c in trace.checks] == [-10, -20, -30, None]
    assert dice.exhausted()
    reloaded = ResourceState.model_validate_json(updated.model_dump_json())
    retried, replay = apply_injury(reloaded, wound(45), ht=12, rng=RecordedDice([]), system=True)
    assert retried == updated and replay == trace
    with pytest.raises(ConflictError):
        apply_injury(updated, wound(44), ht=12, rng=RecordedDice([]), system=True)
    with pytest.raises(ConflictError):
        apply_injury(updated, wound(1, id="new"), ht=12, rng=RecordedDice([]), system=True)


def test_repeated_damage_does_not_repeat_crossed_threshold() -> None:
    first, _ = apply_injury(state(-9), wound(1), ht=12, rng=RecordedDice([3, 3, 3]), system=True)
    second, trace = apply_injury(
        first, wound(1, revision=1, id="second"), ht=12, rng=RecordedDice([]), system=True
    )
    assert second.pools[0].current == -11
    assert not trace.checks


def test_automatic_death_and_mortal_wound() -> None:
    dead, trace = apply_injury(state(), wound(60), ht=12, rng=RecordedDice([]), system=True)
    assert dead.pools[0].injury is not None and dead.pools[0].injury.dead
    assert not trace.checks
    mortal, _ = apply_injury(state(-9), wound(1), ht=12, rng=RecordedDice([4, 4, 5]), system=True)
    assert mortal.pools[0].injury is not None and mortal.pools[0].injury.mortal_wound
    dead, _ = apply_injury(
        mortal, wound(10, revision=1, id="second"), ht=12, rng=RecordedDice([4, 4, 5]), system=True
    )
    assert dead.pools[0].injury is not None and dead.pools[0].injury.dead


def test_stun_recovery_is_end_of_forced_turn_and_retry_safe() -> None:
    stunned, _ = apply_injury(state(), wound(6), ht=12, rng=RecordedDice([4, 4, 5]), system=True)
    status = stunned.pools[0].injury
    assert status is not None and status.stunned and status.prone and status.shock == 4
    start = InjuryTurn(
        id="start", actor_id="a", expected_revision=1, turn=1, phase="start", do_nothing=True
    )
    acting, _ = apply_injury(stunned, start, ht=12, rng=RecordedDice([]), system=True)
    end = InjuryTurn(
        id="end", actor_id="a", expected_revision=2, turn=1, phase="end", do_nothing=True
    )
    recovered, result = apply_injury(acting, end, ht=12, rng=RecordedDice([3, 3, 3]), system=True)
    assert recovered.pools[0].injury is not None
    assert not recovered.pools[0].injury.stunned and recovered.pools[0].injury.shock == 0
    assert apply_injury(recovered, end, ht=12, rng=RecordedDice([]), system=True) == (
        recovered,
        result,
    )
    with pytest.raises(ValidationError):
        apply_injury(
            recovered,
            end.model_copy(update={"id": "another", "expected_revision": 3}),
            ht=12,
            rng=RecordedDice([]),
            system=True,
        )


def test_consciousness_and_move_boundaries() -> None:
    assert impaired_movement(state(3).pools[0], 5) == 3
    assert impaired_movement(state(4).pools[0], 5) == 5
    for do_nothing, rolls in [(True, []), (False, [4, 4, 4])]:
        updated, result = apply_injury(
            state(-10),
            InjuryTurn(
                id="turn",
                actor_id="a",
                expected_revision=0,
                turn=1,
                phase="start",
                do_nothing=do_nothing,
            ),
            ht=12,
            rng=RecordedDice(rolls),
            system=True,
        )
        assert updated.pools[0].injury is not None
        assert updated.pools[0].injury.unconscious is (not do_nothing)
        if not do_nothing:
            assert result.checks[0].check.effective_target == 11


def test_fail_closed_profile_and_authority() -> None:
    with pytest.raises(SchemaError):
        Pool(id="hp:a", current=-1, maximum=10)
    with pytest.raises(SchemaError):
        Pool(id="fp:a", current=-1, maximum=10, injury=state().pools[0].injury)
    with pytest.raises(ValidationError):
        apply_injury(state(), wound(1), ht=12, rng=RecordedDice([]))
    with pytest.raises(ValidationError):
        apply_injury(state(), wound(1, "fat"), ht=12, rng=RecordedDice([]), system=True)
