/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/me": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** getMe */
    get: operations["getMe"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/campaigns": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** listCampaigns */
    get: operations["listCampaigns"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/campaigns/{campaign_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** getCampaign */
    get: operations["getCampaign"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/campaigns/{campaign_id}/members": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** listMembers */
    get: operations["listMembers"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/campaigns/{campaign_id}/sessions/current": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** getCurrentSession */
    get: operations["getCurrentSession"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/campaigns/{campaign_id}/characters": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** listCharacters */
    get: operations["listCharacters"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/campaigns/{campaign_id}/characters/{actor_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** getCharacter */
    get: operations["getCharacter"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/campaigns/{campaign_id}/characters/{actor_id}/inventory": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** getInventory */
    get: operations["getInventory"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/campaigns/{campaign_id}/scenes": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** listScenes */
    get: operations["listScenes"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/campaigns/{campaign_id}/scenes/{scene_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** getScene */
    get: operations["getScene"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/campaigns/{campaign_id}/actions": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** listActions */
    get: operations["listActions"];
    put?: never;
    /** submitAction */
    post: operations["submitAction"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/campaigns/{campaign_id}/actions/{action_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** getAction */
    get: operations["getAction"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/campaigns/{campaign_id}/actions/{action_id}/clarifications": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** clarifyAction */
    post: operations["clarifyAction"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/campaigns/{campaign_id}/actions/{action_id}/cancellation": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** cancelAction */
    post: operations["cancelAction"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/campaigns/{campaign_id}/invitations": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** createInvitation */
    post: operations["createInvitation"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/invitations/redeem": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** redeemInvitation */
    post: operations["redeemInvitation"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    Id: string;
    Version: string;
    /** Format: date-time */
    Timestamp: string;
    GameTime: {
      ticks: number;
      tick_duration_ms: number;
    };
    FieldError: {
      pointer: string;
      code: string;
      message: string;
    };
    Error: {
      /** @enum {string} */
      code:
        | "unauthenticated"
        | "forbidden"
        | "not_found"
        | "invalid_request"
        | "invalid_cursor"
        | "cursor_expired"
        | "stale_version"
        | "idempotency_conflict"
        | "invalid_transition"
        | "unsupported_action"
        | "illegal_action"
        | "payload_too_large"
        | "unsupported_media_type"
        | "rate_limited"
        | "service_unavailable"
        | "internal_error";
      message: string;
      /** Format: uuid */
      request_id: string;
      retryable: boolean;
      field_errors: components["schemas"]["FieldError"][];
    };
    Principal: {
      id: components["schemas"]["Id"];
      display_name: string;
    };
    Membership: {
      principal_id: components["schemas"]["Id"];
      /** @enum {string} */
      role: "gm" | "player" | "spectator";
      actor_ids: components["schemas"]["Id"][];
      version: components["schemas"]["Version"];
      campaign_id: components["schemas"]["Id"];
    };
    Campaign: {
      id: components["schemas"]["Id"];
      name: string;
      premise: string;
      /** @enum {string} */
      status:
        "draft" | "ready" | "active" | "paused" | "completed" | "archived";
      version: components["schemas"]["Version"];
      game_time: components["schemas"]["GameTime"];
      membership: components["schemas"]["Membership"];
      capabilities: string[];
      updated_at: components["schemas"]["Timestamp"];
    };
    Pool: {
      current: number;
      maximum: number;
    };
    Stat: {
      id: components["schemas"]["Id"];
      label: string;
      value: number;
    };
    Condition: {
      id: components["schemas"]["Id"];
      label: string;
      description: string;
    };
    Character: {
      id: components["schemas"]["Id"];
      campaign_id: components["schemas"]["Id"];
      name: string;
      version: components["schemas"]["Version"];
      hp: components["schemas"]["Pool"];
      fp: components["schemas"]["Pool"];
      attributes: components["schemas"]["Stat"][];
      skills: components["schemas"]["Stat"][];
      defenses: components["schemas"]["Stat"][];
      movement: components["schemas"]["Stat"][];
      conditions: components["schemas"]["Condition"][];
      equipped_item_ids: components["schemas"]["Id"][];
    };
    Item: {
      id: components["schemas"]["Id"];
      name: string;
      description: string;
      quantity: number;
      unit_weight_grams: number;
      /** @enum {string} */
      location: "carried" | "equipped" | "stored" | "confiscated";
      container_id: components["schemas"]["Id"] | null;
      allowed_actions: ("inspect" | "use_item")[];
    };
    Inventory: {
      actor_id: components["schemas"]["Id"];
      version: components["schemas"]["Version"];
      items: components["schemas"]["Item"][];
      total_weight_grams: number;
      encumbrance: string;
    };
    Observation: {
      id: components["schemas"]["Id"];
      label: string;
      description: string;
    };
    Scene: {
      id: components["schemas"]["Id"];
      version: components["schemas"]["Version"];
      title: string;
      description: string;
      game_time: components["schemas"]["GameTime"];
      observations: components["schemas"]["Observation"][];
      visible_actor_ids: components["schemas"]["Id"][];
    };
    Clarification: {
      id: components["schemas"]["Id"];
      prompt: string;
      choices: {
        id: components["schemas"]["Id"];
        label: string;
      }[];
      allows_text: boolean;
    };
    Check: {
      label: string;
      dice: number[];
      target: number;
      margin: number;
      /** @enum {string} */
      outcome: "success" | "failure" | "critical_success" | "critical_failure";
    };
    ResourceVersion: {
      /** @enum {string} */
      resource_type:
        "campaign" | "scene" | "character" | "inventory" | "action";
      resource_id: components["schemas"]["Id"];
      version: components["schemas"]["Version"];
    };
    Resolution: {
      summary: string;
      checks: components["schemas"]["Check"][];
      changed_resources: components["schemas"]["ResourceVersion"][];
      game_time: components["schemas"]["GameTime"];
    };
    ExpectedVersions: {
      scene: components["schemas"]["Version"];
      character: components["schemas"]["Version"];
      inventory?: components["schemas"]["Version"];
    };
    TextIntent: {
      /** @constant */
      kind: "text";
      text: string;
    };
    InspectIntent: {
      /** @constant */
      kind: "inspect";
      target_id: components["schemas"]["Id"];
    };
    MoveIntent: {
      /** @constant */
      kind: "move";
      destination_id: components["schemas"]["Id"];
    };
    UseItemIntent: {
      /** @constant */
      kind: "use_item";
      item_id: components["schemas"]["Id"];
      quantity: number;
    };
    WaitIntent: {
      /** @constant */
      kind: "wait";
      ticks: number;
    };
    QuestionIntent: {
      /** @constant */
      kind: "question";
      text: string;
    };
    Intent:
      | components["schemas"]["TextIntent"]
      | components["schemas"]["InspectIntent"]
      | components["schemas"]["MoveIntent"]
      | components["schemas"]["UseItemIntent"]
      | components["schemas"]["WaitIntent"]
      | components["schemas"]["QuestionIntent"];
    SubmitAction: {
      /** Format: uuid */
      command_id: string;
      actor_id: components["schemas"]["Id"];
      scene_id: components["schemas"]["Id"];
      expected_versions: components["schemas"]["ExpectedVersions"];
      intent: components["schemas"]["Intent"];
    } & unknown;
    ClarifyAction: {
      /** Format: uuid */
      command_id: string;
      expected_action_version: components["schemas"]["Version"];
      expected_versions: components["schemas"]["ExpectedVersions"];
      clarification_id: components["schemas"]["Id"];
      answer:
        | {
            choice_id: components["schemas"]["Id"];
          }
        | {
            text: string;
          };
    };
    CancelAction: {
      /** Format: uuid */
      command_id: string;
      expected_action_version: components["schemas"]["Version"];
    };
    ActionSubmitted: {
      id: components["schemas"]["Id"];
      /** Format: uuid */
      command_id: string;
      actor_id: components["schemas"]["Id"];
      scene_id: components["schemas"]["Id"];
      version: components["schemas"]["Version"];
      created_at: components["schemas"]["Timestamp"];
      updated_at: components["schemas"]["Timestamp"];
      /** @constant */
      status: "submitted";
    };
    ActionNeedsClarification: {
      id: components["schemas"]["Id"];
      /** Format: uuid */
      command_id: string;
      actor_id: components["schemas"]["Id"];
      scene_id: components["schemas"]["Id"];
      version: components["schemas"]["Version"];
      created_at: components["schemas"]["Timestamp"];
      updated_at: components["schemas"]["Timestamp"];
      /** @constant */
      status: "needs_clarification";
      clarification: components["schemas"]["Clarification"];
    };
    ActionResolving: {
      id: components["schemas"]["Id"];
      /** Format: uuid */
      command_id: string;
      actor_id: components["schemas"]["Id"];
      scene_id: components["schemas"]["Id"];
      version: components["schemas"]["Version"];
      created_at: components["schemas"]["Timestamp"];
      updated_at: components["schemas"]["Timestamp"];
      /** @constant */
      status: "resolving";
    };
    ActionSucceeded: {
      id: components["schemas"]["Id"];
      /** Format: uuid */
      command_id: string;
      actor_id: components["schemas"]["Id"];
      scene_id: components["schemas"]["Id"];
      version: components["schemas"]["Version"];
      created_at: components["schemas"]["Timestamp"];
      updated_at: components["schemas"]["Timestamp"];
      /** @constant */
      status: "succeeded";
      resolution: components["schemas"]["Resolution"];
    };
    ActionRejected: {
      id: components["schemas"]["Id"];
      /** Format: uuid */
      command_id: string;
      actor_id: components["schemas"]["Id"];
      scene_id: components["schemas"]["Id"];
      version: components["schemas"]["Version"];
      created_at: components["schemas"]["Timestamp"];
      updated_at: components["schemas"]["Timestamp"];
      /** @constant */
      status: "rejected";
      error: components["schemas"]["Error"];
    };
    ActionCancelled: {
      id: components["schemas"]["Id"];
      /** Format: uuid */
      command_id: string;
      actor_id: components["schemas"]["Id"];
      scene_id: components["schemas"]["Id"];
      version: components["schemas"]["Version"];
      created_at: components["schemas"]["Timestamp"];
      updated_at: components["schemas"]["Timestamp"];
      /** @constant */
      status: "cancelled";
    };
    Action:
      | components["schemas"]["ActionSubmitted"]
      | components["schemas"]["ActionNeedsClarification"]
      | components["schemas"]["ActionResolving"]
      | components["schemas"]["ActionSucceeded"]
      | components["schemas"]["ActionRejected"]
      | components["schemas"]["ActionCancelled"];
    InvitationRequest: {
      /** Format: uuid */
      command_id: string;
      expected_membership_version: components["schemas"]["Version"];
      /** @enum {string} */
      role: "player" | "spectator";
      expires_in_seconds: number;
    };
    Invitation: {
      id: components["schemas"]["Id"];
      campaign_id: components["schemas"]["Id"];
      token: string;
      /** @enum {string} */
      role: "player" | "spectator";
      expires_at: components["schemas"]["Timestamp"];
    };
    RedeemInvitation: {
      /** Format: uuid */
      command_id: string;
      token: string;
    };
    Session: {
      id: components["schemas"]["Id"];
      campaign_id: components["schemas"]["Id"];
      /** @enum {string} */
      status: "active" | "paused" | "completed";
      summary: string | null;
      started_at: components["schemas"]["Timestamp"];
      ended_at: components["schemas"]["Timestamp"] | null;
    };
    CampaignPage: {
      items: components["schemas"]["Campaign"][];
      next_cursor: string | null;
    };
    CharacterPage: {
      items: components["schemas"]["Character"][];
      next_cursor: string | null;
    };
    ScenePage: {
      items: components["schemas"]["Scene"][];
      next_cursor: string | null;
    };
    ActionPage: {
      items: components["schemas"]["Action"][];
      next_cursor: string | null;
    };
    MembershipPage: {
      items: components["schemas"]["Membership"][];
      next_cursor: string | null;
    };
  };
  responses: {
    /** @description invalid_request, invalid_cursor */
    Error400: {
      headers: {
        "X-Request-ID"?: string;
        "Cache-Control"?: "no-store";
        [name: string]: unknown;
      };
      content: {
        "application/json": components["schemas"]["Error"];
      };
    };
    /** @description unauthenticated */
    Error401: {
      headers: {
        "X-Request-ID"?: string;
        "Cache-Control"?: "no-store";
        "WWW-Authenticate"?: "Bearer";
        [name: string]: unknown;
      };
      content: {
        "application/json": components["schemas"]["Error"];
      };
    };
    /** @description forbidden */
    Error403: {
      headers: {
        "X-Request-ID"?: string;
        "Cache-Control"?: "no-store";
        [name: string]: unknown;
      };
      content: {
        "application/json": components["schemas"]["Error"];
      };
    };
    /** @description not_found */
    Error404: {
      headers: {
        "X-Request-ID"?: string;
        "Cache-Control"?: "no-store";
        [name: string]: unknown;
      };
      content: {
        "application/json": components["schemas"]["Error"];
      };
    };
    /** @description stale_version, idempotency_conflict, invalid_transition */
    Error409: {
      headers: {
        "X-Request-ID"?: string;
        "Cache-Control"?: "no-store";
        [name: string]: unknown;
      };
      content: {
        "application/json": components["schemas"]["Error"];
      };
    };
    /** @description cursor_expired */
    Error410: {
      headers: {
        "X-Request-ID"?: string;
        "Cache-Control"?: "no-store";
        [name: string]: unknown;
      };
      content: {
        "application/json": components["schemas"]["Error"];
      };
    };
    /** @description payload_too_large */
    Error413: {
      headers: {
        "X-Request-ID"?: string;
        "Cache-Control"?: "no-store";
        [name: string]: unknown;
      };
      content: {
        "application/json": components["schemas"]["Error"];
      };
    };
    /** @description unsupported_media_type */
    Error415: {
      headers: {
        "X-Request-ID"?: string;
        "Cache-Control"?: "no-store";
        [name: string]: unknown;
      };
      content: {
        "application/json": components["schemas"]["Error"];
      };
    };
    /** @description unsupported_action, illegal_action */
    Error422: {
      headers: {
        "X-Request-ID"?: string;
        "Cache-Control"?: "no-store";
        [name: string]: unknown;
      };
      content: {
        "application/json": components["schemas"]["Error"];
      };
    };
    /** @description rate_limited */
    Error429: {
      headers: {
        "X-Request-ID"?: string;
        "Cache-Control"?: "no-store";
        /** @description Required integer delay in seconds. */
        "Retry-After"?: number;
        [name: string]: unknown;
      };
      content: {
        "application/json": components["schemas"]["Error"];
      };
    };
    /** @description internal_error */
    Error500: {
      headers: {
        "X-Request-ID"?: string;
        "Cache-Control"?: "no-store";
        [name: string]: unknown;
      };
      content: {
        "application/json": components["schemas"]["Error"];
      };
    };
    /** @description service_unavailable */
    Error503: {
      headers: {
        "X-Request-ID"?: string;
        "Cache-Control"?: "no-store";
        /** @description Required integer delay in seconds. */
        "Retry-After"?: number;
        [name: string]: unknown;
      };
      content: {
        "application/json": components["schemas"]["Error"];
      };
    };
  };
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  getMe: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Success */
      200: {
        headers: {
          "X-Request-ID"?: string;
          "Cache-Control"?: "no-store";
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Principal"];
        };
      };
      400: components["responses"]["Error400"];
      401: components["responses"]["Error401"];
      403: components["responses"]["Error403"];
      404: components["responses"]["Error404"];
      429: components["responses"]["Error429"];
      500: components["responses"]["Error500"];
      503: components["responses"]["Error503"];
    };
  };
  listCampaigns: {
    parameters: {
      query?: {
        limit?: number;
        cursor?: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Success */
      200: {
        headers: {
          "X-Request-ID"?: string;
          "Cache-Control"?: "no-store";
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CampaignPage"];
        };
      };
      400: components["responses"]["Error400"];
      401: components["responses"]["Error401"];
      403: components["responses"]["Error403"];
      404: components["responses"]["Error404"];
      410: components["responses"]["Error410"];
      429: components["responses"]["Error429"];
      500: components["responses"]["Error500"];
      503: components["responses"]["Error503"];
    };
  };
  getCampaign: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        campaign_id: components["schemas"]["Id"];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Success */
      200: {
        headers: {
          "X-Request-ID"?: string;
          "Cache-Control"?: "no-store";
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Campaign"];
        };
      };
      400: components["responses"]["Error400"];
      401: components["responses"]["Error401"];
      403: components["responses"]["Error403"];
      404: components["responses"]["Error404"];
      429: components["responses"]["Error429"];
      500: components["responses"]["Error500"];
      503: components["responses"]["Error503"];
    };
  };
  listMembers: {
    parameters: {
      query?: {
        limit?: number;
        cursor?: string;
      };
      header?: never;
      path: {
        campaign_id: components["schemas"]["Id"];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Success */
      200: {
        headers: {
          "X-Request-ID"?: string;
          "Cache-Control"?: "no-store";
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["MembershipPage"];
        };
      };
      400: components["responses"]["Error400"];
      401: components["responses"]["Error401"];
      403: components["responses"]["Error403"];
      404: components["responses"]["Error404"];
      410: components["responses"]["Error410"];
      429: components["responses"]["Error429"];
      500: components["responses"]["Error500"];
      503: components["responses"]["Error503"];
    };
  };
  getCurrentSession: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        campaign_id: components["schemas"]["Id"];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Success */
      200: {
        headers: {
          "X-Request-ID"?: string;
          "Cache-Control"?: "no-store";
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Session"];
        };
      };
      400: components["responses"]["Error400"];
      401: components["responses"]["Error401"];
      403: components["responses"]["Error403"];
      404: components["responses"]["Error404"];
      429: components["responses"]["Error429"];
      500: components["responses"]["Error500"];
      503: components["responses"]["Error503"];
    };
  };
  listCharacters: {
    parameters: {
      query?: {
        limit?: number;
        cursor?: string;
      };
      header?: never;
      path: {
        campaign_id: components["schemas"]["Id"];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Success */
      200: {
        headers: {
          "X-Request-ID"?: string;
          "Cache-Control"?: "no-store";
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CharacterPage"];
        };
      };
      400: components["responses"]["Error400"];
      401: components["responses"]["Error401"];
      403: components["responses"]["Error403"];
      404: components["responses"]["Error404"];
      410: components["responses"]["Error410"];
      429: components["responses"]["Error429"];
      500: components["responses"]["Error500"];
      503: components["responses"]["Error503"];
    };
  };
  getCharacter: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        campaign_id: components["schemas"]["Id"];
        actor_id: components["schemas"]["Id"];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Success */
      200: {
        headers: {
          "X-Request-ID"?: string;
          "Cache-Control"?: "no-store";
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Character"];
        };
      };
      400: components["responses"]["Error400"];
      401: components["responses"]["Error401"];
      403: components["responses"]["Error403"];
      404: components["responses"]["Error404"];
      429: components["responses"]["Error429"];
      500: components["responses"]["Error500"];
      503: components["responses"]["Error503"];
    };
  };
  getInventory: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        campaign_id: components["schemas"]["Id"];
        actor_id: components["schemas"]["Id"];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Success */
      200: {
        headers: {
          "X-Request-ID"?: string;
          "Cache-Control"?: "no-store";
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Inventory"];
        };
      };
      400: components["responses"]["Error400"];
      401: components["responses"]["Error401"];
      403: components["responses"]["Error403"];
      404: components["responses"]["Error404"];
      429: components["responses"]["Error429"];
      500: components["responses"]["Error500"];
      503: components["responses"]["Error503"];
    };
  };
  listScenes: {
    parameters: {
      query?: {
        limit?: number;
        cursor?: string;
      };
      header?: never;
      path: {
        campaign_id: components["schemas"]["Id"];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Success */
      200: {
        headers: {
          "X-Request-ID"?: string;
          "Cache-Control"?: "no-store";
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ScenePage"];
        };
      };
      400: components["responses"]["Error400"];
      401: components["responses"]["Error401"];
      403: components["responses"]["Error403"];
      404: components["responses"]["Error404"];
      410: components["responses"]["Error410"];
      429: components["responses"]["Error429"];
      500: components["responses"]["Error500"];
      503: components["responses"]["Error503"];
    };
  };
  getScene: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        campaign_id: components["schemas"]["Id"];
        scene_id: components["schemas"]["Id"];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Success */
      200: {
        headers: {
          "X-Request-ID"?: string;
          "Cache-Control"?: "no-store";
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Scene"];
        };
      };
      400: components["responses"]["Error400"];
      401: components["responses"]["Error401"];
      403: components["responses"]["Error403"];
      404: components["responses"]["Error404"];
      429: components["responses"]["Error429"];
      500: components["responses"]["Error500"];
      503: components["responses"]["Error503"];
    };
  };
  listActions: {
    parameters: {
      query: {
        limit?: number;
        cursor?: string;
        scene_id: components["schemas"]["Id"];
      };
      header?: never;
      path: {
        campaign_id: components["schemas"]["Id"];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Success */
      200: {
        headers: {
          "X-Request-ID"?: string;
          "Cache-Control"?: "no-store";
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ActionPage"];
        };
      };
      400: components["responses"]["Error400"];
      401: components["responses"]["Error401"];
      403: components["responses"]["Error403"];
      404: components["responses"]["Error404"];
      410: components["responses"]["Error410"];
      429: components["responses"]["Error429"];
      500: components["responses"]["Error500"];
      503: components["responses"]["Error503"];
    };
  };
  submitAction: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        campaign_id: components["schemas"]["Id"];
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["SubmitAction"];
      };
    };
    responses: {
      /** @description Accepted action resource; poll until terminal. */
      202: {
        headers: {
          "X-Request-ID"?: string;
          "Cache-Control"?: "no-store";
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Action"];
        };
      };
      400: components["responses"]["Error400"];
      401: components["responses"]["Error401"];
      403: components["responses"]["Error403"];
      404: components["responses"]["Error404"];
      409: components["responses"]["Error409"];
      413: components["responses"]["Error413"];
      415: components["responses"]["Error415"];
      422: components["responses"]["Error422"];
      429: components["responses"]["Error429"];
      500: components["responses"]["Error500"];
      503: components["responses"]["Error503"];
    };
  };
  getAction: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        campaign_id: components["schemas"]["Id"];
        action_id: components["schemas"]["Id"];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Success */
      200: {
        headers: {
          "X-Request-ID"?: string;
          "Cache-Control"?: "no-store";
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Action"];
        };
      };
      400: components["responses"]["Error400"];
      401: components["responses"]["Error401"];
      403: components["responses"]["Error403"];
      404: components["responses"]["Error404"];
      429: components["responses"]["Error429"];
      500: components["responses"]["Error500"];
      503: components["responses"]["Error503"];
    };
  };
  clarifyAction: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        campaign_id: components["schemas"]["Id"];
        action_id: components["schemas"]["Id"];
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ClarifyAction"];
      };
    };
    responses: {
      /** @description Accepted action resource; poll until terminal. */
      202: {
        headers: {
          "X-Request-ID"?: string;
          "Cache-Control"?: "no-store";
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Action"];
        };
      };
      400: components["responses"]["Error400"];
      401: components["responses"]["Error401"];
      403: components["responses"]["Error403"];
      404: components["responses"]["Error404"];
      409: components["responses"]["Error409"];
      413: components["responses"]["Error413"];
      415: components["responses"]["Error415"];
      422: components["responses"]["Error422"];
      429: components["responses"]["Error429"];
      500: components["responses"]["Error500"];
      503: components["responses"]["Error503"];
    };
  };
  cancelAction: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        campaign_id: components["schemas"]["Id"];
        action_id: components["schemas"]["Id"];
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CancelAction"];
      };
    };
    responses: {
      /** @description Success */
      200: {
        headers: {
          "X-Request-ID"?: string;
          "Cache-Control"?: "no-store";
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Action"];
        };
      };
      400: components["responses"]["Error400"];
      401: components["responses"]["Error401"];
      403: components["responses"]["Error403"];
      404: components["responses"]["Error404"];
      409: components["responses"]["Error409"];
      413: components["responses"]["Error413"];
      415: components["responses"]["Error415"];
      422: components["responses"]["Error422"];
      429: components["responses"]["Error429"];
      500: components["responses"]["Error500"];
      503: components["responses"]["Error503"];
    };
  };
  createInvitation: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        campaign_id: components["schemas"]["Id"];
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["InvitationRequest"];
      };
    };
    responses: {
      /** @description Success */
      201: {
        headers: {
          "X-Request-ID"?: string;
          "Cache-Control"?: "no-store";
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Invitation"];
        };
      };
      400: components["responses"]["Error400"];
      401: components["responses"]["Error401"];
      403: components["responses"]["Error403"];
      404: components["responses"]["Error404"];
      409: components["responses"]["Error409"];
      413: components["responses"]["Error413"];
      415: components["responses"]["Error415"];
      422: components["responses"]["Error422"];
      429: components["responses"]["Error429"];
      500: components["responses"]["Error500"];
      503: components["responses"]["Error503"];
    };
  };
  redeemInvitation: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["RedeemInvitation"];
      };
    };
    responses: {
      /** @description Success */
      200: {
        headers: {
          "X-Request-ID"?: string;
          "Cache-Control"?: "no-store";
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Membership"];
        };
      };
      400: components["responses"]["Error400"];
      401: components["responses"]["Error401"];
      403: components["responses"]["Error403"];
      404: components["responses"]["Error404"];
      409: components["responses"]["Error409"];
      413: components["responses"]["Error413"];
      415: components["responses"]["Error415"];
      422: components["responses"]["Error422"];
      429: components["responses"]["Error429"];
      500: components["responses"]["Error500"];
      503: components["responses"]["Error503"];
    };
  };
}
