/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export type paths = Record<string, never>;
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    HTTP_Id: string;
    HTTP_Version: string;
    /** Format: date-time */
    HTTP_Timestamp: string;
    HTTP_GameTime: {
      ticks: number;
      tick_duration_ms: number;
    };
    HTTP_FieldError: {
      pointer: string;
      code: string;
      message: string;
    };
    HTTP_Error: {
      /** @enum {string} */
      code:
        | "unauthenticated"
        | "forbidden"
        | "not_found"
        | "invalid_request"
        | "invalid_cursor"
        | "cursor_expired"
        | "stale_version"
        | "idempotency_conflict"
        | "invalid_transition"
        | "unsupported_action"
        | "illegal_action"
        | "payload_too_large"
        | "unsupported_media_type"
        | "rate_limited"
        | "service_unavailable"
        | "internal_error";
      message: string;
      /** Format: uuid */
      request_id: string;
      retryable: boolean;
      field_errors: components["schemas"]["HTTP_FieldError"][];
    };
    HTTP_Principal: {
      id: components["schemas"]["HTTP_Id"];
      display_name: string;
    };
    HTTP_Membership: {
      principal_id: components["schemas"]["HTTP_Id"];
      /** @enum {string} */
      role: "gm" | "player" | "spectator";
      actor_ids: components["schemas"]["HTTP_Id"][];
      version: components["schemas"]["HTTP_Version"];
      campaign_id: components["schemas"]["HTTP_Id"];
    };
    HTTP_Campaign: {
      id: components["schemas"]["HTTP_Id"];
      name: string;
      premise: string;
      /** @enum {string} */
      status:
        "draft" | "ready" | "active" | "paused" | "completed" | "archived";
      version: components["schemas"]["HTTP_Version"];
      game_time: components["schemas"]["HTTP_GameTime"];
      membership: components["schemas"]["HTTP_Membership"];
      capabilities: string[];
      updated_at: components["schemas"]["HTTP_Timestamp"];
    };
    HTTP_Pool: {
      current: number;
      maximum: number;
    };
    HTTP_Stat: {
      id: components["schemas"]["HTTP_Id"];
      label: string;
      value: number;
    };
    HTTP_Condition: {
      id: components["schemas"]["HTTP_Id"];
      label: string;
      description: string;
    };
    HTTP_Character: {
      id: components["schemas"]["HTTP_Id"];
      campaign_id: components["schemas"]["HTTP_Id"];
      name: string;
      version: components["schemas"]["HTTP_Version"];
      hp: components["schemas"]["HTTP_Pool"];
      fp: components["schemas"]["HTTP_Pool"];
      attributes: components["schemas"]["HTTP_Stat"][];
      skills: components["schemas"]["HTTP_Stat"][];
      defenses: components["schemas"]["HTTP_Stat"][];
      movement: components["schemas"]["HTTP_Stat"][];
      conditions: components["schemas"]["HTTP_Condition"][];
      equipped_item_ids: components["schemas"]["HTTP_Id"][];
    };
    HTTP_Item: {
      id: components["schemas"]["HTTP_Id"];
      name: string;
      description: string;
      quantity: number;
      unit_weight_grams: number;
      /** @enum {string} */
      location: "carried" | "equipped" | "stored" | "confiscated";
      container_id: components["schemas"]["HTTP_Id"] | null;
      allowed_actions: ("inspect" | "use_item")[];
    };
    HTTP_Inventory: {
      actor_id: components["schemas"]["HTTP_Id"];
      version: components["schemas"]["HTTP_Version"];
      items: components["schemas"]["HTTP_Item"][];
      total_weight_grams: number;
      encumbrance: string;
    };
    HTTP_Observation: {
      id: components["schemas"]["HTTP_Id"];
      label: string;
      description: string;
    };
    HTTP_Scene: {
      id: components["schemas"]["HTTP_Id"];
      version: components["schemas"]["HTTP_Version"];
      title: string;
      description: string;
      game_time: components["schemas"]["HTTP_GameTime"];
      observations: components["schemas"]["HTTP_Observation"][];
      visible_actor_ids: components["schemas"]["HTTP_Id"][];
    };
    HTTP_Clarification: {
      id: components["schemas"]["HTTP_Id"];
      prompt: string;
      choices: {
        id: components["schemas"]["HTTP_Id"];
        label: string;
      }[];
      allows_text: boolean;
    };
    HTTP_Check: {
      label: string;
      dice: number[];
      target: number;
      margin: number;
      /** @enum {string} */
      outcome: "success" | "failure" | "critical_success" | "critical_failure";
    };
    HTTP_ResourceVersion: {
      /** @enum {string} */
      resource_type:
        "campaign" | "scene" | "character" | "inventory" | "action";
      resource_id: components["schemas"]["HTTP_Id"];
      version: components["schemas"]["HTTP_Version"];
    };
    HTTP_Resolution: {
      summary: string;
      checks: components["schemas"]["HTTP_Check"][];
      changed_resources: components["schemas"]["HTTP_ResourceVersion"][];
      game_time: components["schemas"]["HTTP_GameTime"];
    };
    HTTP_ExpectedVersions: {
      scene: components["schemas"]["HTTP_Version"];
      character: components["schemas"]["HTTP_Version"];
      inventory?: components["schemas"]["HTTP_Version"];
    };
    HTTP_TextIntent: {
      /** @constant */
      kind: "text";
      text: string;
    };
    HTTP_InspectIntent: {
      /** @constant */
      kind: "inspect";
      target_id: components["schemas"]["HTTP_Id"];
    };
    HTTP_MoveIntent: {
      /** @constant */
      kind: "move";
      destination_id: components["schemas"]["HTTP_Id"];
    };
    HTTP_UseItemIntent: {
      /** @constant */
      kind: "use_item";
      item_id: components["schemas"]["HTTP_Id"];
      quantity: number;
    };
    HTTP_WaitIntent: {
      /** @constant */
      kind: "wait";
      ticks: number;
    };
    HTTP_QuestionIntent: {
      /** @constant */
      kind: "question";
      text: string;
    };
    HTTP_Intent:
      | components["schemas"]["HTTP_TextIntent"]
      | components["schemas"]["HTTP_InspectIntent"]
      | components["schemas"]["HTTP_MoveIntent"]
      | components["schemas"]["HTTP_UseItemIntent"]
      | components["schemas"]["HTTP_WaitIntent"]
      | components["schemas"]["HTTP_QuestionIntent"];
    HTTP_SubmitAction: {
      /** Format: uuid */
      command_id: string;
      actor_id: components["schemas"]["HTTP_Id"];
      scene_id: components["schemas"]["HTTP_Id"];
      expected_versions: components["schemas"]["HTTP_ExpectedVersions"];
      intent: components["schemas"]["HTTP_Intent"];
    } & unknown;
    HTTP_ClarifyAction: {
      /** Format: uuid */
      command_id: string;
      expected_action_version: components["schemas"]["HTTP_Version"];
      expected_versions: components["schemas"]["HTTP_ExpectedVersions"];
      clarification_id: components["schemas"]["HTTP_Id"];
      answer:
        | {
            choice_id: components["schemas"]["HTTP_Id"];
          }
        | {
            text: string;
          };
    };
    HTTP_CancelAction: {
      /** Format: uuid */
      command_id: string;
      expected_action_version: components["schemas"]["HTTP_Version"];
    };
    HTTP_ActionSubmitted: {
      id: components["schemas"]["HTTP_Id"];
      /** Format: uuid */
      command_id: string;
      actor_id: components["schemas"]["HTTP_Id"];
      scene_id: components["schemas"]["HTTP_Id"];
      version: components["schemas"]["HTTP_Version"];
      created_at: components["schemas"]["HTTP_Timestamp"];
      updated_at: components["schemas"]["HTTP_Timestamp"];
      /** @constant */
      status: "submitted";
    };
    HTTP_ActionNeedsClarification: {
      id: components["schemas"]["HTTP_Id"];
      /** Format: uuid */
      command_id: string;
      actor_id: components["schemas"]["HTTP_Id"];
      scene_id: components["schemas"]["HTTP_Id"];
      version: components["schemas"]["HTTP_Version"];
      created_at: components["schemas"]["HTTP_Timestamp"];
      updated_at: components["schemas"]["HTTP_Timestamp"];
      /** @constant */
      status: "needs_clarification";
      clarification: components["schemas"]["HTTP_Clarification"];
    };
    HTTP_ActionResolving: {
      id: components["schemas"]["HTTP_Id"];
      /** Format: uuid */
      command_id: string;
      actor_id: components["schemas"]["HTTP_Id"];
      scene_id: components["schemas"]["HTTP_Id"];
      version: components["schemas"]["HTTP_Version"];
      created_at: components["schemas"]["HTTP_Timestamp"];
      updated_at: components["schemas"]["HTTP_Timestamp"];
      /** @constant */
      status: "resolving";
    };
    HTTP_ActionSucceeded: {
      id: components["schemas"]["HTTP_Id"];
      /** Format: uuid */
      command_id: string;
      actor_id: components["schemas"]["HTTP_Id"];
      scene_id: components["schemas"]["HTTP_Id"];
      version: components["schemas"]["HTTP_Version"];
      created_at: components["schemas"]["HTTP_Timestamp"];
      updated_at: components["schemas"]["HTTP_Timestamp"];
      /** @constant */
      status: "succeeded";
      resolution: components["schemas"]["HTTP_Resolution"];
    };
    HTTP_ActionRejected: {
      id: components["schemas"]["HTTP_Id"];
      /** Format: uuid */
      command_id: string;
      actor_id: components["schemas"]["HTTP_Id"];
      scene_id: components["schemas"]["HTTP_Id"];
      version: components["schemas"]["HTTP_Version"];
      created_at: components["schemas"]["HTTP_Timestamp"];
      updated_at: components["schemas"]["HTTP_Timestamp"];
      /** @constant */
      status: "rejected";
      error: components["schemas"]["HTTP_Error"];
    };
    HTTP_ActionCancelled: {
      id: components["schemas"]["HTTP_Id"];
      /** Format: uuid */
      command_id: string;
      actor_id: components["schemas"]["HTTP_Id"];
      scene_id: components["schemas"]["HTTP_Id"];
      version: components["schemas"]["HTTP_Version"];
      created_at: components["schemas"]["HTTP_Timestamp"];
      updated_at: components["schemas"]["HTTP_Timestamp"];
      /** @constant */
      status: "cancelled";
    };
    HTTP_Action:
      | components["schemas"]["HTTP_ActionSubmitted"]
      | components["schemas"]["HTTP_ActionNeedsClarification"]
      | components["schemas"]["HTTP_ActionResolving"]
      | components["schemas"]["HTTP_ActionSucceeded"]
      | components["schemas"]["HTTP_ActionRejected"]
      | components["schemas"]["HTTP_ActionCancelled"];
    HTTP_InvitationRequest: {
      /** Format: uuid */
      command_id: string;
      expected_membership_version: components["schemas"]["HTTP_Version"];
      /** @enum {string} */
      role: "player" | "spectator";
      expires_in_seconds: number;
    };
    HTTP_Invitation: {
      id: components["schemas"]["HTTP_Id"];
      campaign_id: components["schemas"]["HTTP_Id"];
      token: string;
      /** @enum {string} */
      role: "player" | "spectator";
      expires_at: components["schemas"]["HTTP_Timestamp"];
    };
    HTTP_RedeemInvitation: {
      /** Format: uuid */
      command_id: string;
      token: string;
    };
    HTTP_Session: {
      id: components["schemas"]["HTTP_Id"];
      campaign_id: components["schemas"]["HTTP_Id"];
      /** @enum {string} */
      status: "active" | "paused" | "completed";
      summary: string | null;
      started_at: components["schemas"]["HTTP_Timestamp"];
      ended_at: components["schemas"]["HTTP_Timestamp"] | null;
    };
    HTTP_CampaignPage: {
      items: components["schemas"]["HTTP_Campaign"][];
      next_cursor: string | null;
    };
    HTTP_CharacterPage: {
      items: components["schemas"]["HTTP_Character"][];
      next_cursor: string | null;
    };
    HTTP_ScenePage: {
      items: components["schemas"]["HTTP_Scene"][];
      next_cursor: string | null;
    };
    HTTP_ActionPage: {
      items: components["schemas"]["HTTP_Action"][];
      next_cursor: string | null;
    };
    HTTP_MembershipPage: {
      items: components["schemas"]["HTTP_Membership"][];
      next_cursor: string | null;
    };
    Scope: {
      campaign_id: components["schemas"]["HTTP_Id"];
      scene_id: components["schemas"]["HTTP_Id"];
      actor_id: components["schemas"]["HTTP_Id"];
    };
    Cursor: string;
    Epoch: components["schemas"]["HTTP_Version"];
    Authenticate: {
      /** @constant */
      type: "authenticate";
      /** Format: uuid */
      request_id: string;
      credential: string;
    };
    Subscribe: {
      /** @constant */
      type: "subscribe";
      /** Format: uuid */
      request_id: string;
      /** Format: uuid */
      subscription_id: string;
      scope: components["schemas"]["Scope"];
      resume: {
        cursor: components["schemas"]["Cursor"];
        visibility_epoch: components["schemas"]["Epoch"];
      } | null;
    };
    Acknowledge: {
      /** @constant */
      type: "ack";
      /** Format: uuid */
      request_id: string;
      /** Format: uuid */
      subscription_id: string;
      cursor: components["schemas"]["Cursor"];
    };
    Unsubscribe: {
      /** @constant */
      type: "unsubscribe";
      /** Format: uuid */
      request_id: string;
      /** Format: uuid */
      subscription_id: string;
    };
    Pong: {
      /** @constant */
      type: "heartbeat.pong";
      /** Format: uuid */
      request_id: string;
      /** Format: uuid */
      nonce: string;
    };
    InterruptNarration: {
      /** @constant */
      type: "narration.interrupt";
      /** Format: uuid */
      request_id: string;
      /** Format: uuid */
      subscription_id: string;
      /** Format: uuid */
      narration_id: string;
    };
    Authenticated: {
      /** @constant */
      type: "authenticated";
      /** @constant */
      protocol_version: "1.0.0";
      /** Format: uuid */
      request_id: string;
      /** Format: uuid */
      connection_id: string;
      principal_id: components["schemas"]["HTTP_Id"];
      expires_at: components["schemas"]["HTTP_Timestamp"];
    };
    Subscribed: {
      /** @constant */
      type: "subscribed";
      /** @constant */
      protocol_version: "1.0.0";
      /** Format: uuid */
      request_id: string;
      /** Format: uuid */
      subscription_id: string;
      scope: components["schemas"]["Scope"];
      visibility_epoch: components["schemas"]["Epoch"];
      /** @enum {string} */
      mode: "snapshot" | "replay";
    };
    SnapshotBegin: {
      /** @constant */
      type: "snapshot.begin";
      /** @constant */
      protocol_version: "1.0.0";
      /** Format: uuid */
      subscription_id: string;
      scope: components["schemas"]["Scope"];
      visibility_epoch: components["schemas"]["Epoch"];
      /** Format: uuid */
      snapshot_id: string;
      cursor: components["schemas"]["Cursor"];
      resource_count: number;
    };
    CampaignResource: {
      /** @constant */
      kind: "campaign";
      value: components["schemas"]["HTTP_Campaign"];
    };
    SceneResource: {
      /** @constant */
      kind: "scene";
      value: components["schemas"]["HTTP_Scene"];
    };
    CharacterResource: {
      /** @constant */
      kind: "character";
      value: components["schemas"]["HTTP_Character"];
    };
    InventoryResource: {
      /** @constant */
      kind: "inventory";
      value: components["schemas"]["HTTP_Inventory"];
    };
    ActionResource: {
      /** @constant */
      kind: "action";
      value: components["schemas"]["HTTP_Action"];
    };
    SnapshotResource:
      | components["schemas"]["CampaignResource"]
      | components["schemas"]["SceneResource"]
      | components["schemas"]["CharacterResource"]
      | components["schemas"]["InventoryResource"]
      | components["schemas"]["ActionResource"];
    SnapshotResourceMessage: {
      /** @constant */
      type: "snapshot.resource";
      /** @constant */
      protocol_version: "1.0.0";
      /** Format: uuid */
      subscription_id: string;
      scope: components["schemas"]["Scope"];
      visibility_epoch: components["schemas"]["Epoch"];
      /** Format: uuid */
      snapshot_id: string;
      index: number;
      resource: components["schemas"]["SnapshotResource"];
    };
    SnapshotEnd: {
      /** @constant */
      type: "snapshot.end";
      /** @constant */
      protocol_version: "1.0.0";
      /** Format: uuid */
      subscription_id: string;
      scope: components["schemas"]["Scope"];
      visibility_epoch: components["schemas"]["Epoch"];
      /** Format: uuid */
      snapshot_id: string;
      cursor: components["schemas"]["Cursor"];
      resource_count: number;
    };
    Ready: {
      /** @constant */
      type: "stream.ready";
      /** @constant */
      protocol_version: "1.0.0";
      /** Format: uuid */
      subscription_id: string;
      scope: components["schemas"]["Scope"];
      visibility_epoch: components["schemas"]["Epoch"];
      cursor: components["schemas"]["Cursor"];
    };
    ActionUpdated: {
      /** @constant */
      type: "action.updated";
      /** @constant */
      protocol_version: "1.0.0";
      /** Format: uuid */
      subscription_id: string;
      scope: components["schemas"]["Scope"];
      visibility_epoch: components["schemas"]["Epoch"];
      /** Format: uuid */
      event_id: string;
      cursor: components["schemas"]["Cursor"];
      previous_cursor: components["schemas"]["Cursor"];
      occurred_at: components["schemas"]["HTTP_Timestamp"];
      /** Format: uuid */
      correlation_id: string;
      causation_id: string | null;
      action: components["schemas"]["HTTP_Action"];
    };
    ProjectionInvalidated: {
      /** @constant */
      type: "projection.invalidated";
      /** @constant */
      protocol_version: "1.0.0";
      /** Format: uuid */
      subscription_id: string;
      scope: components["schemas"]["Scope"];
      visibility_epoch: components["schemas"]["Epoch"];
      /** Format: uuid */
      event_id: string;
      cursor: components["schemas"]["Cursor"];
      previous_cursor: components["schemas"]["Cursor"];
      occurred_at: components["schemas"]["HTTP_Timestamp"];
      /** Format: uuid */
      correlation_id: string;
      causation_id: string | null;
      resources: components["schemas"]["HTTP_ResourceVersion"][];
    };
    Reset: {
      /** @constant */
      type: "stream.reset";
      /** @constant */
      protocol_version: "1.0.0";
      /** Format: uuid */
      subscription_id: string;
      /** @enum {string} */
      reason:
        | "cursor_expired"
        | "visibility_changed"
        | "backpressure"
        | "resume_unavailable";
      retry_after_ms: number;
    };
    Revoked: {
      /** @constant */
      type: "subscription.revoked";
      /** @constant */
      protocol_version: "1.0.0";
      /** Format: uuid */
      subscription_id: string;
    };
    Unsubscribed: {
      /** @constant */
      type: "unsubscribed";
      /** @constant */
      protocol_version: "1.0.0";
      /** Format: uuid */
      request_id: string;
      /** Format: uuid */
      subscription_id: string;
    };
    Ping: {
      /** @constant */
      type: "heartbeat.ping";
      /** @constant */
      protocol_version: "1.0.0";
      /** Format: uuid */
      nonce: string;
    };
    StreamError: {
      /** @constant */
      type: "error";
      /** @constant */
      protocol_version: "1.0.0";
      request_id: string | null;
      subscription_id: string | null;
      /** @enum {string} */
      code:
        | "unauthenticated"
        | "not_found"
        | "invalid_message"
        | "invalid_cursor"
        | "invalid_transition"
        | "rate_limited"
        | "snapshot_too_large"
        | "service_unavailable";
      retry_after_ms: number | null;
    };
    NarrationStarted: {
      /** @constant */
      type: "narration.started";
      /** @constant */
      protocol_version: "1.0.0";
      /** Format: uuid */
      subscription_id: string;
      scope: components["schemas"]["Scope"];
      visibility_epoch: components["schemas"]["Epoch"];
      /** Format: uuid */
      narration_id: string;
      action_id: components["schemas"]["HTTP_Id"];
      /** Format: uuid */
      command_id: string;
      /** @enum {string} */
      basis: "provisional" | "committed";
      voice_session_id: components["schemas"]["HTTP_Id"] | null;
    };
    NarrationDelta: {
      /** @constant */
      type: "narration.delta";
      /** @constant */
      protocol_version: "1.0.0";
      /** Format: uuid */
      subscription_id: string;
      scope: components["schemas"]["Scope"];
      visibility_epoch: components["schemas"]["Epoch"];
      /** Format: uuid */
      narration_id: string;
      index: number;
      text: string;
    };
    NarrationEnded: {
      /** @constant */
      type: "narration.ended";
      /** @constant */
      protocol_version: "1.0.0";
      /** Format: uuid */
      subscription_id: string;
      scope: components["schemas"]["Scope"];
      visibility_epoch: components["schemas"]["Epoch"];
      /** Format: uuid */
      narration_id: string;
      /** @enum {string} */
      status: "completed" | "interrupted" | "failed";
      chunk_count: number;
      request_id: string | null;
    };
    VoiceSegment: {
      /** @constant */
      type: "voice.segment";
      /** @constant */
      protocol_version: "1.0.0";
      /** Format: uuid */
      subscription_id: string;
      scope: components["schemas"]["Scope"];
      visibility_epoch: components["schemas"]["Epoch"];
      /** Format: uuid */
      narration_id: string;
      voice_session_id: components["schemas"]["HTTP_Id"];
      segment_index: number;
      duration_ms: number;
      /** @enum {string} */
      media_type: "audio/opus" | "audio/pcm";
      /** @enum {integer} */
      sample_rate_hz: 16000 | 24000 | 48000;
    };
    ClientMessage:
      | components["schemas"]["Authenticate"]
      | components["schemas"]["Subscribe"]
      | components["schemas"]["Acknowledge"]
      | components["schemas"]["Unsubscribe"]
      | components["schemas"]["Pong"]
      | components["schemas"]["InterruptNarration"];
    ServerMessage:
      | components["schemas"]["Authenticated"]
      | components["schemas"]["Subscribed"]
      | components["schemas"]["SnapshotBegin"]
      | components["schemas"]["SnapshotResourceMessage"]
      | components["schemas"]["SnapshotEnd"]
      | components["schemas"]["Ready"]
      | components["schemas"]["ActionUpdated"]
      | components["schemas"]["ProjectionInvalidated"]
      | components["schemas"]["Reset"]
      | components["schemas"]["Revoked"]
      | components["schemas"]["Unsubscribed"]
      | components["schemas"]["Ping"]
      | components["schemas"]["StreamError"]
      | components["schemas"]["NarrationStarted"]
      | components["schemas"]["NarrationDelta"]
      | components["schemas"]["NarrationEnded"]
      | components["schemas"]["VoiceSegment"];
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;

export type ClientMessage = components["schemas"]["ClientMessage"];
export type ServerMessage = components["schemas"]["ServerMessage"];
export type Scope = components["schemas"]["Scope"];
