// Generated from contracts/v1/openapi.json. Do not edit.
export const operations = {
  getMe: {
    method: "GET",
    path: "/me",
    requestSchema: null,
    responses: {
      "200": "Principal",
      "400": "Error",
      "401": "Error",
      "403": "Error",
      "404": "Error",
      "429": "Error",
      "500": "Error",
      "503": "Error",
    },
  },
  listCampaigns: {
    method: "GET",
    path: "/campaigns",
    requestSchema: null,
    responses: {
      "200": "CampaignPage",
      "400": "Error",
      "401": "Error",
      "403": "Error",
      "404": "Error",
      "410": "Error",
      "429": "Error",
      "500": "Error",
      "503": "Error",
    },
  },
  getCampaign: {
    method: "GET",
    path: "/campaigns/{campaign_id}",
    requestSchema: null,
    responses: {
      "200": "Campaign",
      "400": "Error",
      "401": "Error",
      "403": "Error",
      "404": "Error",
      "429": "Error",
      "500": "Error",
      "503": "Error",
    },
  },
  listMembers: {
    method: "GET",
    path: "/campaigns/{campaign_id}/members",
    requestSchema: null,
    responses: {
      "200": "MembershipPage",
      "400": "Error",
      "401": "Error",
      "403": "Error",
      "404": "Error",
      "410": "Error",
      "429": "Error",
      "500": "Error",
      "503": "Error",
    },
  },
  getCurrentSession: {
    method: "GET",
    path: "/campaigns/{campaign_id}/sessions/current",
    requestSchema: null,
    responses: {
      "200": "Session",
      "400": "Error",
      "401": "Error",
      "403": "Error",
      "404": "Error",
      "429": "Error",
      "500": "Error",
      "503": "Error",
    },
  },
  listCharacters: {
    method: "GET",
    path: "/campaigns/{campaign_id}/characters",
    requestSchema: null,
    responses: {
      "200": "CharacterPage",
      "400": "Error",
      "401": "Error",
      "403": "Error",
      "404": "Error",
      "410": "Error",
      "429": "Error",
      "500": "Error",
      "503": "Error",
    },
  },
  getCharacter: {
    method: "GET",
    path: "/campaigns/{campaign_id}/characters/{actor_id}",
    requestSchema: null,
    responses: {
      "200": "Character",
      "400": "Error",
      "401": "Error",
      "403": "Error",
      "404": "Error",
      "429": "Error",
      "500": "Error",
      "503": "Error",
    },
  },
  getInventory: {
    method: "GET",
    path: "/campaigns/{campaign_id}/characters/{actor_id}/inventory",
    requestSchema: null,
    responses: {
      "200": "Inventory",
      "400": "Error",
      "401": "Error",
      "403": "Error",
      "404": "Error",
      "429": "Error",
      "500": "Error",
      "503": "Error",
    },
  },
  listScenes: {
    method: "GET",
    path: "/campaigns/{campaign_id}/scenes",
    requestSchema: null,
    responses: {
      "200": "ScenePage",
      "400": "Error",
      "401": "Error",
      "403": "Error",
      "404": "Error",
      "410": "Error",
      "429": "Error",
      "500": "Error",
      "503": "Error",
    },
  },
  getScene: {
    method: "GET",
    path: "/campaigns/{campaign_id}/scenes/{scene_id}",
    requestSchema: null,
    responses: {
      "200": "Scene",
      "400": "Error",
      "401": "Error",
      "403": "Error",
      "404": "Error",
      "429": "Error",
      "500": "Error",
      "503": "Error",
    },
  },
  submitAction: {
    method: "POST",
    path: "/campaigns/{campaign_id}/actions",
    requestSchema: "SubmitAction",
    responses: {
      "202": "Action",
      "400": "Error",
      "401": "Error",
      "403": "Error",
      "404": "Error",
      "409": "Error",
      "413": "Error",
      "415": "Error",
      "422": "Error",
      "429": "Error",
      "500": "Error",
      "503": "Error",
    },
  },
  listActions: {
    method: "GET",
    path: "/campaigns/{campaign_id}/actions",
    requestSchema: null,
    responses: {
      "200": "ActionPage",
      "400": "Error",
      "401": "Error",
      "403": "Error",
      "404": "Error",
      "410": "Error",
      "429": "Error",
      "500": "Error",
      "503": "Error",
    },
  },
  getAction: {
    method: "GET",
    path: "/campaigns/{campaign_id}/actions/{action_id}",
    requestSchema: null,
    responses: {
      "200": "Action",
      "400": "Error",
      "401": "Error",
      "403": "Error",
      "404": "Error",
      "429": "Error",
      "500": "Error",
      "503": "Error",
    },
  },
  clarifyAction: {
    method: "POST",
    path: "/campaigns/{campaign_id}/actions/{action_id}/clarifications",
    requestSchema: "ClarifyAction",
    responses: {
      "202": "Action",
      "400": "Error",
      "401": "Error",
      "403": "Error",
      "404": "Error",
      "409": "Error",
      "413": "Error",
      "415": "Error",
      "422": "Error",
      "429": "Error",
      "500": "Error",
      "503": "Error",
    },
  },
  cancelAction: {
    method: "POST",
    path: "/campaigns/{campaign_id}/actions/{action_id}/cancellation",
    requestSchema: "CancelAction",
    responses: {
      "200": "Action",
      "400": "Error",
      "401": "Error",
      "403": "Error",
      "404": "Error",
      "409": "Error",
      "413": "Error",
      "415": "Error",
      "422": "Error",
      "429": "Error",
      "500": "Error",
      "503": "Error",
    },
  },
  createInvitation: {
    method: "POST",
    path: "/campaigns/{campaign_id}/invitations",
    requestSchema: "InvitationRequest",
    responses: {
      "201": "Invitation",
      "400": "Error",
      "401": "Error",
      "403": "Error",
      "404": "Error",
      "409": "Error",
      "413": "Error",
      "415": "Error",
      "422": "Error",
      "429": "Error",
      "500": "Error",
      "503": "Error",
    },
  },
  redeemInvitation: {
    method: "POST",
    path: "/invitations/redeem",
    requestSchema: "RedeemInvitation",
    responses: {
      "200": "Membership",
      "400": "Error",
      "401": "Error",
      "403": "Error",
      "404": "Error",
      "409": "Error",
      "413": "Error",
      "415": "Error",
      "422": "Error",
      "429": "Error",
      "500": "Error",
      "503": "Error",
    },
  },
} as const;
export type OperationId = keyof typeof operations;
