/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/campaigns/{cid}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["readTactical"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/campaigns/{cid}/commands": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["executeTactical"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    /** BasicMove */
    BasicMove: {
      /** Reference Actor Id */
      reference_actor_id: string;
      /**
       * Direction
       * @enum {string}
       */
      direction: "approach" | "withdraw";
    };
    /** Cell */
    Cell: {
      position: components["schemas"]["Hex"];
      /**
       * Elevation
       * @description Yards above map datum
       * @default 0
       */
      elevation: number;
      /**
       * Blocked
       * @default false
       */
      blocked: boolean;
      /**
       * Extra Cost
       * @description Authored terrain MP surcharge
       * @default 0
       */
      extra_cost: number;
      /**
       * Opaque Height
       * @description Yards above ground
       * @default 0
       */
      opaque_height: number;
      /**
       * Elevation Inches
       * @description Additional inches above elevation datum
       */
      elevation_inches?: number;
    };
    /** ChooseDefense */
    ChooseDefense: {
      /** Id */
      id: string;
      /** Actor Id */
      actor_id: string;
      /** Expected Revision */
      expected_revision: number;
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      kind: "choose_defense";
      /** Encounter Id */
      encounter_id: string;
      /**
       * Defense
       * @enum {string}
       */
      defense: "dodge" | "parry" | "block" | "none";
      /**
       * Item Id
       * @default null
       */
      item_id: string | null;
      /**
       * Second Defense
       * @default null
       */
      second_defense: ("dodge" | "parry" | "block" | "none") | null;
      /**
       * Second Item Id
       * @default null
       */
      second_item_id: string | null;
      /**
       * Catch Thrown
       * @default false
       */
      catch_thrown: boolean;
      /** @default null */
      retreat: components["schemas"]["Hex"] | null;
      /**
       * Basic Retreat
       * @default false
       */
      basic_retreat: boolean;
      /**
       * Parry Mode Id
       * @default null
       */
      parry_mode_id: string | null;
      /**
       * Second Parry Mode Id
       * @default null
       */
      second_parry_mode_id: string | null;
    };
    /** EquipmentChoice */
    EquipmentChoice: {
      /** Label */
      label: string;
      /** Command */
      command:
        | components["schemas"]["RepairEquipment"]
        | components["schemas"]["RetrieveEquipment"]
        | components["schemas"]["TakeCombatTurn"];
    };
    /** EquipmentView */
    EquipmentView: {
      /** Id */
      id: string;
      /** Name */
      name: string;
      condition: components["schemas"]["ObjectCondition"] | null;
      ground: components["schemas"]["GroundPosition"] | null;
      /**
       * Work
       * @default null
       */
      work: string | null;
      /**
       * Due In
       * @default null
       */
      due_in: number | null;
      /**
       * Choices
       * @default []
       */
      choices: components["schemas"]["EquipmentChoice"][];
      /** @default null */
      readiness: components["schemas"]["ProjectileProgress"] | null;
      /**
       * Loaded Rounds
       * @default null
       */
      loaded_rounds: number | null;
      /**
       * Charges
       * @default null
       */
      charges: number | null;
    };
    /** GridPoint */
    GridPoint: {
      /** X */
      x: number;
      /** Y */
      y: number;
    };
    /** GroundPosition */
    GroundPosition: {
      /** Encounter Id */
      encounter_id: string;
      /**
       * Geometry
       * @enum {string}
       */
      geometry: "grid" | "hex";
      /** X */
      x: number;
      /** Y */
      y: number;
    };
    /** Hex */
    Hex: {
      /** Q */
      q: number;
      /** R */
      r: number;
    };
    /** ObjectCondition */
    ObjectCondition: {
      /** Hp */
      hp: number;
      /**
       * Disabled
       * @default false
       */
      disabled: boolean;
      /**
       * Destroyed
       * @default false
       */
      destroyed: boolean;
      /**
       * Last Stress At
       * @default null
       */
      last_stress_at: number | null;
      /**
       * Residual Roll
       * @default null
       */
      residual_roll: number | null;
      /**
       * Shock
       * @default 0
       */
      shock: number;
      /**
       * Shock Until
       * @default null
       */
      shock_until: number | null;
    };
    /** ProjectileProgress */
    ProjectileProgress: {
      /**
       * Stage
       * @default prepare
       * @enum {string}
       */
      stage: "prepare" | "draw" | "cock" | "load" | "loaded" | "unload";
      /**
       * Elapsed
       * @default 0
       */
      elapsed: number;
      /**
       * Required
       * @default 0
       */
      required: number;
      /**
       * Fast Draw Used
       * @default false
       */
      fast_draw_used: boolean;
      /**
       * Cocking Aid Id
       * @default null
       */
      cocking_aid_id: string | null;
    };
    /** RepairEquipment */
    RepairEquipment: {
      /** Id */
      id: string;
      /** Actor Id */
      actor_id: string;
      /** Expected Revision */
      expected_revision: number;
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      kind: "repair_equipment";
      /** Encounter Id */
      encounter_id: string;
      /** Item Id */
      item_id: string;
      /**
       * Stage
       * @enum {string}
       */
      stage: "start" | "finish" | "cancel";
      /**
       * Task Id
       * @default null
       */
      task_id: string | null;
    };
    /** ResumeInterruptedTurn */
    ResumeInterruptedTurn: {
      /** Id */
      id: string;
      /** Actor Id */
      actor_id: string;
      /** Expected Revision */
      expected_revision: number;
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      kind: "resume_interrupted_turn";
      /** Encounter Id */
      encounter_id: string;
      /**
       * Cancel
       * @default false
       */
      cancel: boolean;
    };
    /** RetrieveEquipment */
    RetrieveEquipment: {
      /** Id */
      id: string;
      /** Actor Id */
      actor_id: string;
      /** Expected Revision */
      expected_revision: number;
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      kind: "retrieve_equipment";
      /** Encounter Id */
      encounter_id: string;
      /** Item Id */
      item_id: string;
      /**
       * Stage
       * @enum {string}
       */
      stage: "start" | "finish" | "cancel";
      /**
       * Task Id
       * @default null
       */
      task_id: string | null;
    };
    /** TacticalActor */
    TacticalActor: {
      /** Id */
      id: string;
      /** Name */
      name: string;
      position: components["schemas"]["Hex"];
      /** Facing */
      facing: number;
      /** Posture */
      posture: string;
      /** Controlled */
      controlled: boolean;
      /** Grappled */
      grappled: boolean;
      /** Pinned */
      pinned: boolean;
    };
    /** TacticalChoice */
    TacticalChoice: {
      /** Label */
      label: string;
      /** Command */
      command:
        | components["schemas"]["TakeCombatTurn"]
        | components["schemas"]["TakeUnarmedTurn"]
        | components["schemas"]["ChooseDefense"]
        | components["schemas"]["ResumeInterruptedTurn"];
    };
    /** TacticalEncounter */
    TacticalEncounter: {
      /** Id */
      id: string;
      /** Status */
      status: string;
      /** Round */
      round: number;
      /** Current Actor Id */
      current_actor_id: string | null;
      /**
       * Coordinate System
       * @default hex-axial-v1
       */
      coordinate_system: string;
      /** Cells */
      cells: components["schemas"]["Cell"][];
      /** Actors */
      actors: components["schemas"]["TacticalActor"][];
      /** Grips */
      grips: components["schemas"]["TacticalGrip"][];
      /** Choices */
      choices: components["schemas"]["TacticalChoice"][];
      /**
       * Notice
       * @default null
       */
      notice: string | null;
      /**
       * Traces
       * @default []
       */
      traces: components["schemas"]["TacticalTrace"][];
    };
    /** TacticalGrip */
    TacticalGrip: {
      /** Id */
      id: string;
      /** Holder Id */
      holder_id: string;
      /** Target Id */
      target_id: string;
      /** Location */
      location: string;
      /** Hands */
      hands: string[];
    };
    /** TacticalTrace */
    TacticalTrace: {
      /** Command Id */
      command_id: string;
      /** Actor Id */
      actor_id: string;
      /** Code */
      code: string;
      /**
       * Totals
       * @default []
       */
      totals: number[];
      /**
       * Targets
       * @default []
       */
      targets: number[];
      /**
       * Injury
       * @default 0
       */
      injury: number;
      /**
       * Source
       * @default GURPS Basic Set: Campaigns 4e, fourth printing (April 2008), B367-377, B384-392
       */
      source: string;
    };
    /** TakeCombatTurn */
    TakeCombatTurn: {
      /** Id */
      id: string;
      /** Actor Id */
      actor_id: string;
      /** Expected Revision */
      expected_revision: number;
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      kind: "take_combat_turn";
      /** Encounter Id */
      encounter_id: string;
      /**
       * Maneuver
       * @enum {string}
       */
      maneuver:
        | "do_nothing"
        | "move"
        | "ready"
        | "change_posture"
        | "attack"
        | "wait"
        | "concentrate"
        | "aim"
        | "evaluate"
        | "feint"
        | "all_out_attack"
        | "all_out_defense"
        | "move_and_attack";
      /** @default null */
      destination: components["schemas"]["GridPoint"] | null;
      /**
       * Facing
       * @default null
       */
      facing: ("north" | "east" | "south" | "west") | null;
      /**
       * Posture
       * @default null
       */
      posture: ("standing" | "kneeling" | "prone") | null;
      /**
       * Item Id
       * @default null
       */
      item_id: string | null;
      /**
       * Target Id
       * @default null
       */
      target_id: string | null;
      /**
       * Mode Id
       * @default null
       */
      mode_id: string | null;
      /**
       * Shots
       * @default 1
       */
      shots: number;
      /**
       * Reload Ammunition Id
       * @default null
       */
      reload_ammunition_id: string | null;
      /**
       * Unload Ammunition
       * @default false
       */
      unload_ammunition: boolean;
      /**
       * Fast Draw
       * @default false
       */
      fast_draw: boolean;
      /**
       * Cocking Aid Id
       * @default null
       */
      cocking_aid_id: string | null;
      /**
       * Let Down Bow
       * @default false
       */
      let_down_bow: boolean;
      /**
       * Recover Thrown Item
       * @default false
       */
      recover_thrown_item: boolean;
      /**
       * Escape Entanglement
       * @default false
       */
      escape_entanglement: boolean;
      /**
       * Mount Crew
       * @default []
       */
      mount_crew: string[];
      /**
       * Firearm Service
       * @default null
       */
      firearm_service: ("diagnose" | "clear" | "repair") | null;
      /**
       * Firearm Service Skill
       * @default weapon
       * @enum {string}
       */
      firearm_service_skill: "weapon" | "armoury";
      /**
       * Hit Location
       * @default null
       */
      hit_location:
        | (
            | "torso"
            | "vitals"
            | "skull"
            | "face"
            | "neck"
            | "groin"
            | "left-arm"
            | "right-arm"
            | "left-leg"
            | "right-leg"
            | "left-hand"
            | "right-hand"
            | "left-foot"
            | "right-foot"
            | "left-eye"
            | "right-eye"
          )
        | "random"
        | null;
      /**
       * Target Item Id
       * @default null
       */
      target_item_id: string | null;
      /**
       * Ready Hand
       * @default null
       */
      ready_hand: ("left-hand" | "right-hand") | "both" | null;
      /**
       * Attack Option
       * @default null
       */
      attack_option: ("determined" | "strong" | "double" | "feint") | null;
      /**
       * Defense Option
       * @default null
       */
      defense_option: ("dodge" | "parry" | "block" | "double") | null;
      /** @default null */
      wait_trigger: components["schemas"]["WaitTrigger"] | null;
      /**
       * Step Timing
       * @default before
       * @enum {string}
       */
      step_timing: "before" | "after";
      /**
       * Second Item Id
       * @default null
       */
      second_item_id: string | null;
      /**
       * Second Target Id
       * @default null
       */
      second_target_id: string | null;
      /**
       * Second Mode Id
       * @default null
       */
      second_mode_id: string | null;
      /**
       * Braced
       * @default false
       */
      braced: boolean;
      /**
       * Hex Path
       * @default []
       */
      hex_path: components["schemas"]["Hex"][];
      /**
       * Hex Facing
       * @default null
       */
      hex_facing: (0 | 1 | 2 | 3 | 4 | 5) | null;
      /** @default null */
      basic_move: components["schemas"]["BasicMove"] | null;
    };
    /** TakeUnarmedTurn */
    TakeUnarmedTurn: {
      /** Id */
      id: string;
      /** Actor Id */
      actor_id: string;
      /** Expected Revision */
      expected_revision: number;
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      kind: "take_unarmed_turn";
      /** Encounter Id */
      encounter_id: string;
      /**
       * Action
       * @enum {string}
       */
      action:
        | "punch"
        | "kick"
        | "grapple"
        | "break_free"
        | "takedown"
        | "pin"
        | "release"
        | "arm_lock"
        | "lock_damage"
        | "strangle";
      /**
       * Foot
       * @default right-foot
       * @enum {string}
       */
      foot: "left-foot" | "right-foot";
      /** Target Id */
      target_id: string;
      /**
       * Skill
       * @default attribute:dx
       * @enum {string}
       */
      skill:
        | "attribute:dx"
        | "skill:brawling"
        | "skill:boxing"
        | "skill:karate"
        | "skill:judo"
        | "skill:wrestling"
        | "skill:sumo-wrestling";
      /**
       * Hands
       * @default []
       */
      hands: ("left-hand" | "right-hand")[];
      /**
       * Location
       * @default torso
       * @enum {string}
       */
      location:
        "torso" | "neck" | "left-arm" | "right-arm" | "left-leg" | "right-leg";
      /**
       * Grip Id
       * @default null
       */
      grip_id: string | null;
      /**
       * Enter Close Combat
       * @default false
       */
      enter_close_combat: boolean;
      /**
       * Maneuver
       * @default attack
       * @enum {string}
       */
      maneuver: "attack" | "all_out_attack" | "move_and_attack";
      /**
       * Attack Option
       * @default null
       */
      attack_option: ("determined" | "strong" | "double" | "feint") | null;
    };
    /**
     * UnarmedReaction
     * @description An unarmed attack declared in advance as a Wait reaction (B366).
     *
     *     Every parameter is fixed before the trigger fires, so the reaction cannot be
     *     re-chosen once an opponent commits. A reaction never includes a step, so
     *     close-combat entry is not declarable here.
     */
    UnarmedReaction: {
      /**
       * Action
       * @enum {string}
       */
      action: "punch" | "kick" | "grapple" | "arm_lock";
      /**
       * Skill
       * @default attribute:dx
       * @enum {string}
       */
      skill:
        | "attribute:dx"
        | "skill:brawling"
        | "skill:boxing"
        | "skill:karate"
        | "skill:judo"
        | "skill:wrestling"
        | "skill:sumo-wrestling";
      /**
       * Hands
       * @default []
       */
      hands: ("left-hand" | "right-hand")[];
      /**
       * Foot
       * @default right-foot
       * @enum {string}
       */
      foot: "left-foot" | "right-foot";
      /**
       * Location
       * @default torso
       * @enum {string}
       */
      location:
        "torso" | "neck" | "left-arm" | "right-arm" | "left-leg" | "right-leg";
      /**
       * Grip Id
       * @default null
       */
      grip_id: string | null;
    };
    /** WaitTrigger */
    WaitTrigger: {
      /**
       * Actor Id
       * @default null
       */
      actor_id: string | null;
      /**
       * Action
       * @enum {string}
       */
      action: "attack" | "move";
      /**
       * Target Id
       * @default null
       */
      target_id: string | null;
      /**
       * Reaction
       * @default attack
       * @enum {string}
       */
      reaction: "attack" | "all_out_attack" | "feint" | "ready";
      /**
       * Item Id
       * @default null
       */
      item_id: string | null;
      /**
       * Reaction Target Id
       * @default null
       */
      reaction_target_id: string | null;
      /**
       * Mode Id
       * @default null
       */
      mode_id: string | null;
      /**
       * Attack Option
       * @default null
       */
      attack_option: ("determined" | "strong" | "double" | "feint") | null;
      /**
       * Zone
       * @default []
       */
      zone: [number, number][];
      /**
       * Stop Thrust
       * @default false
       */
      stop_thrust: boolean;
      /** @default null */
      unarmed: components["schemas"]["UnarmedReaction"] | null;
    };
    /** TacticalSnapshotV2 */
    TacticalSnapshotV2: {
      /**
       * Version
       * @default tactical-v2
       */
      version: string;
      /** Campaign Id */
      campaign_id: string;
      /** Actor Id */
      actor_id: string;
      /** Revision */
      revision: number;
      /** Encounters */
      encounters: components["schemas"]["TacticalEncounter"][];
      /**
       * Equipment
       * @default []
       */
      equipment: components["schemas"]["EquipmentView"][];
    };
    /**
     * BlastResponse
     * @description GM declares chosen defenses and scene cover before any blast dice.
     */
    BlastResponse: {
      /** Actor Id */
      actor_id: string;
      /** Cover Dr */
      cover_dr: number;
      /**
       * Covered Locations
       * @default []
       */
      covered_locations: (
        | "torso"
        | "vitals"
        | "skull"
        | "face"
        | "neck"
        | "groin"
        | "left-arm"
        | "right-arm"
        | "left-leg"
        | "right-leg"
        | "left-hand"
        | "right-hand"
        | "left-foot"
        | "right-foot"
        | "left-eye"
        | "right-eye"
      )[];
      /**
       * Dive Covered Locations
       * @default []
       */
      dive_covered_locations: (
        | "torso"
        | "vitals"
        | "skull"
        | "face"
        | "neck"
        | "groin"
        | "left-arm"
        | "right-arm"
        | "left-leg"
        | "right-leg"
        | "left-hand"
        | "right-hand"
        | "left-foot"
        | "right-foot"
        | "left-eye"
        | "right-eye"
      )[];
      /** Size Modifier */
      size_modifier: number;
      /** @default null */
      dive_to: components["schemas"]["GroundPosition"] | null;
      /**
       * Dive Cover Dr
       * @default 0
       */
      dive_cover_dr: number;
    };
    /** ContinueCriticalMiss */
    ContinueCriticalMiss: {
      /** Id */
      id: string;
      /** Actor Id */
      actor_id: string;
      /** Expected Revision */
      expected_revision: number;
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      kind: "continue_critical_miss";
      /** Encounter Id */
      encounter_id: string;
      /** Critical Id */
      critical_id: string;
      /**
       * Stage
       * @enum {string}
       */
      stage: "migrate" | "resume";
    };
    /** DeclareThrownLanding */
    DeclareThrownLanding: {
      /** Id */
      id: string;
      /** Actor Id */
      actor_id: string;
      /** Expected Revision */
      expected_revision: number;
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      kind: "declare_thrown_landing";
      /** Encounter Id */
      encounter_id: string;
      /** Item Id */
      item_id: string;
      landing: components["schemas"]["GroundPosition"];
    };
    /**
     * HexBattlefield
     * @description New tagged contract. Legacy square maps cannot validate as hex maps.
     */
    HexBattlefield: {
      /** Id */
      id: string;
      /**
       * Location Id
       * @default unbound
       */
      location_id: string;
      /**
       * Source Template Id
       * @default null
       */
      source_template_id: string | null;
      /**
       * Darkness Penalty
       * @default 0
       */
      darkness_penalty: number;
      /**
       * Coordinate System
       * @constant
       */
      coordinate_system: "hex-axial-v1";
      /**
       * Profile Id
       * @constant
       */
      profile_id: "gurps-basic-set-4e-2004";
      /**
       * Baseline Id
       * @constant
       */
      baseline_id: "gurps-4e-characters-3p-2008+campaigns-4p-2008";
      /** Cells */
      cells: components["schemas"]["Cell"][];
      /** Stairs */
      stairs?: components["schemas"]["Stairway"][];
    };
    /** HexPlacement */
    HexPlacement: {
      /** Actor Id */
      actor_id: string;
      pose: components["schemas"]["Pose"];
    };
    /** MigrateEncounterHex */
    MigrateEncounterHex: {
      /** Id */
      id: string;
      /** Actor Id */
      actor_id: string;
      /** Expected Revision */
      expected_revision: number;
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      kind: "migrate_encounter_hex";
      /** Encounter Id */
      encounter_id: string;
      battlefield: components["schemas"]["HexBattlefield"];
      /** Placements */
      placements: components["schemas"]["HexPlacement"][];
    };
    /** Pose */
    Pose: {
      position: components["schemas"]["Hex"];
      /**
       * Facing
       * @enum {integer}
       */
      facing: 0 | 1 | 2 | 3 | 4 | 5;
      /**
       * Posture
       * @default standing
       * @enum {string}
       */
      posture:
        | "standing"
        | "crouching"
        | "kneeling"
        | "crawling"
        | "sitting"
        | "lying";
    };
    /** ResolveChokeEffects */
    ResolveChokeEffects: {
      /** Id */
      id: string;
      /** Actor Id */
      actor_id: string;
      /** Expected Revision */
      expected_revision: number;
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      kind: "resolve_choke_effects";
      /** Encounter Id */
      encounter_id: string;
      /** Grip Id */
      grip_id: string;
    };
    /** ResolveWeaponExplosion */
    ResolveWeaponExplosion: {
      /** Id */
      id: string;
      /** Actor Id */
      actor_id: string;
      /** Expected Revision */
      expected_revision: number;
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      kind: "resolve_weapon_explosion";
      /** Encounter Id */
      encounter_id: string;
      /** Blast Id */
      blast_id: string;
      /** Responses */
      responses: components["schemas"]["BlastResponse"][];
      /** Object Cover */
      object_cover: {
        [key: string]: number;
      };
      /** Object Sizes */
      object_sizes?: {
        [key: string]: number;
      };
      /** @default null */
      center: components["schemas"]["GroundPosition"] | null;
      /**
       * Environment
       * @enum {string}
       */
      environment: "air" | "water" | "vacuum";
    };
    /**
     * Stairway
     * @description Authored traversable edge, not permission to climb or jump a cliff.
     */
    Stairway: {
      start: components["schemas"]["Hex"];
      end: components["schemas"]["Hex"];
    };
    /** TacticalRequestV2 */
    TacticalRequestV2: {
      /** Command */
      command:
        | components["schemas"]["TakeCombatTurn"]
        | components["schemas"]["TakeUnarmedTurn"]
        | components["schemas"]["ChooseDefense"]
        | components["schemas"]["MigrateEncounterHex"]
        | components["schemas"]["ResumeInterruptedTurn"]
        | components["schemas"]["ResolveChokeEffects"]
        | components["schemas"]["RepairEquipment"]
        | components["schemas"]["RetrieveEquipment"]
        | components["schemas"]["ContinueCriticalMiss"]
        | components["schemas"]["DeclareThrownLanding"]
        | components["schemas"]["ResolveWeaponExplosion"];
    };
    TacticalError: {
      code: string;
      error: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  readTactical: {
    parameters: {
      query: {
        actor_id: string;
      };
      header?: never;
      path: {
        cid: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description TacticalSnapshotV2 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["TacticalSnapshotV2"];
        };
      };
      /** @description TacticalError */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["TacticalError"];
        };
      };
      /** @description TacticalError */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["TacticalError"];
        };
      };
      /** @description TacticalError */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["TacticalError"];
        };
      };
      /** @description TacticalError */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["TacticalError"];
        };
      };
      /** @description TacticalError */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["TacticalError"];
        };
      };
      /** @description TacticalError */
      413: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["TacticalError"];
        };
      };
      /** @description TacticalError */
      429: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["TacticalError"];
        };
      };
    };
  };
  executeTactical: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        cid: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["TacticalRequestV2"];
      };
    };
    responses: {
      /** @description TacticalSnapshotV2 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["TacticalSnapshotV2"];
        };
      };
      /** @description TacticalError */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["TacticalError"];
        };
      };
      /** @description TacticalError */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["TacticalError"];
        };
      };
      /** @description TacticalError */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["TacticalError"];
        };
      };
      /** @description TacticalError */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["TacticalError"];
        };
      };
      /** @description TacticalError */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["TacticalError"];
        };
      };
      /** @description TacticalError */
      413: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["TacticalError"];
        };
      };
      /** @description TacticalError */
      429: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["TacticalError"];
        };
      };
    };
  };
}
