"""General equipment rows (B288-289)."""

from decimal import Decimal
from typing import cast

from wayfarer.engine.simulation.equipment.basic.rows import source
from wayfarer.engine.simulation.equipment.catalog import EquipmentProfile, TechnologyLevel

# B288-289: fixed-TL inventory facts. Behavioral requirements keep special tools
# out of active packages until their mechanics are integrated; no invented
# skill/effect hooks. Rows printed with ``TL Var.`` remain ledger omissions
# because the catalog currently requires one concrete technology level.
ORDINARY = tuple(
    EquipmentProfile(
        definition_id=identifier,
        provenance=source(page),
        technology_level=cast(TechnologyLevel, tl),
        price=price,
        weight_millipounds=weight,
        container_capacity_millipounds=capacity,
        unsupported_mechanics=missing,
    )
    for identifier, page, tl, price, weight, capacity, missing in (
        # Camping and survival gear, B288.
        ("equipment:frame-backpack", 288, 1, 100, 10000, 100000, ()),
        ("equipment:small-backpack", 288, 1, 60, 3000, 40000, ()),
        ("equipment:blanket", 288, 1, 20, 4000, None, ()),
        ("equipment:ceramic-bottle", 288, 1, 3, 1000, 2000, ()),
        ("equipment:steel-cable-15", 288, 5, 100, 17000, None, ("special-tool-effects",)),
        ("equipment:camp-stove", 288, 6, 50, 2000, None, ("fuel-consumption",)),
        ("equipment:tallow-candle", 288, 1, 5, 1000, None, ("fuel-consumption",)),
        ("equipment:canteen", 288, 5, 10, 1000, 2000, ()),
        ("equipment:cigarette-lighter", 288, 6, 10, 0, None, ("special-tool-effects",)),
        ("equipment:climbing-gear", 288, 2, 20, 4000, None, ("special-tool-effects",)),
        ("equipment:compass", 288, 6, 50, 0, None, ("special-tool-effects",)),
        ("equipment:cord-3-16", 288, 0, 1, 500, None, ("special-tool-effects",)),
        ("equipment:fishhooks-and-line", 288, 0, 50, 0, None, ("special-tool-effects",)),
        ("equipment:heavy-flashlight", 288, 6, 20, 1000, None, ("battery-and-computer-operation",)),
        ("equipment:mini-flashlight", 288, 7, 10, 250, None, ("battery-and-computer-operation",)),
        ("equipment:gasoline-gallon", 288, 6, Decimal("1.5"), 6000, None, ("fuel-consumption",)),
        (
            "equipment:gps-receiver",
            288,
            8,
            200,
            3000,
            None,
            ("battery-and-computer-operation", "special-tool-effects"),
        ),
        ("equipment:grapnel", 288, 5, 20, 2000, None, ("special-tool-effects",)),
        ("equipment:group-basics", 288, 0, 50, 20000, None, ("special-tool-effects",)),
        ("equipment:iron-spike", 288, 2, 1, 500, None, ("special-tool-effects",)),
        ("equipment:kerosene-gallon", 288, 6, Decimal("1.5"), 6000, None, ("fuel-consumption",)),
        ("equipment:lantern", 288, 2, 20, 2000, None, ("fuel-consumption",)),
        ("equipment:life-jacket", 288, 6, 100, 6000, None, ("special-tool-effects",)),
        (
            "equipment:waterproof-matches-50",
            288,
            6,
            Decimal("1.5"),
            0,
            None,
            ("special-tool-effects",),
        ),
        ("equipment:lantern-oil-pint", 288, 2, 2, 1000, None, ("fuel-consumption",)),
        ("equipment:parachute", 288, 6, 1000, 30000, None, ("special-tool-effects",)),
        ("equipment:personal-basics", 288, 0, 5, 1000, None, ("special-tool-effects",)),
        ("equipment:six-foot-pole", 288, 0, 5, 3000, None, ()),
        ("equipment:ten-foot-pole", 288, 0, 8, 5000, None, ()),
        ("equipment:small-pouch", 288, 1, 10, 0, 3000, ()),
        ("equipment:rope-3-8", 288, 0, 5, 1500, None, ("special-tool-effects",)),
        ("equipment:rope-3-4", 288, 1, 25, 5000, None, ("special-tool-effects",)),
        ("equipment:scuba-gear", 288, 6, 1500, 32000, None, ("special-tool-effects",)),
        ("equipment:sleeping-bag", 288, 6, 25, 7000, None, ()),
        ("equipment:insulated-sleeping-bag", 288, 7, 100, 15000, None, ("cold-resistance-bonus",)),
        ("equipment:sleeping-fur", 288, 0, 50, 8000, None, ()),
        ("equipment:hard-suitcase", 288, 5, 250, 8000, 100000, ("special-tool-effects",)),
        ("equipment:one-man-tent", 288, 0, 50, 5000, None, ()),
        ("equipment:two-man-tent", 288, 0, 80, 12000, None, ()),
        ("equipment:four-man-tent", 288, 0, 150, 30000, None, ()),
        ("equipment:twenty-man-tent", 288, 1, 300, 100000, None, ()),
        ("equipment:thermos-bottle", 288, 5, 10, 2000, None, ("special-tool-effects",)),
        ("equipment:torch", 288, 0, 3, 1000, None, ("fuel-consumption",)),
        ("equipment:travelers-ration", 288, 0, 2, 500, None, ()),
        ("equipment:water-purification-tablets-50", 288, 6, 5, 0, None, ("special-tool-effects",)),
        ("equipment:wineskin", 288, 0, 10, 250, 8000, ()),
        ("equipment:wristwatch", 288, 6, 20, 0, None, ()),
        # Communications and information gear, B288-289.
        ("equipment:battery", 288, 6, 1, 0, None, ("battery-and-computer-operation",)),
        (
            "equipment:cell-phone",
            288,
            8,
            250,
            250,
            None,
            ("battery-and-computer-operation", "special-tool-effects"),
        ),
        ("equipment:laptop", 288, 8, 1500, 3000, None, ("battery-and-computer-operation",)),
        (
            "equipment:wearable-computer",
            288,
            8,
            1000,
            2000,
            None,
            ("battery-and-computer-operation",),
        ),
        ("equipment:drum", 288, 0, 40, 2000, None, ("special-tool-effects",)),
        ("equipment:mini-recorder", 288, 7, 200, 500, None, ("battery-and-computer-operation",)),
        ("equipment:mini-recorder-tape", 288, 7, 5, 0, None, ()),
        (
            "equipment:digital-mini-recorder",
            288,
            8,
            30,
            500,
            None,
            ("battery-and-computer-operation",),
        ),
        (
            "equipment:backpack-radio",
            288,
            7,
            6000,
            15000,
            None,
            ("battery-and-computer-operation", "special-tool-effects"),
        ),
        (
            "equipment:hand-radio",
            288,
            7,
            100,
            1000,
            None,
            ("battery-and-computer-operation", "special-tool-effects"),
        ),
        (
            "equipment:headset-radio",
            288,
            8,
            500,
            500,
            None,
            ("battery-and-computer-operation", "special-tool-effects"),
        ),
        (
            "equipment:secure-headset-radio",
            288,
            8,
            5000,
            500,
            None,
            ("battery-and-computer-operation", "special-tool-effects"),
        ),
        (
            "equipment:satellite-phone",
            288,
            8,
            3000,
            3000,
            None,
            ("battery-and-computer-operation", "special-tool-effects"),
        ),
        ("equipment:scribes-kit", 288, 3, 50, 2000, None, ()),
        ("equipment:transistor-radio", 288, 7, 15, 500, None, ("battery-and-computer-operation",)),
        ("equipment:mini-tv", 288, 7, 150, 3000, None, ("battery-and-computer-operation",)),
        ("equipment:manual-typewriter", 289, 6, 200, 10000, None, ()),
        ("equipment:wax-tablet", 289, 1, 10, 2000, None, ()),
        # Equestrian gear, B289.
        ("equipment:bit-and-bridle", 289, 1, 35, 3000, None, ("special-tool-effects",)),
        ("equipment:horseshoes", 289, 3, 50, 4000, None, ("special-tool-effects",)),
        ("equipment:saddle-and-tack", 289, 2, 150, 15000, None, ("special-tool-effects",)),
        ("equipment:saddlebags", 289, 1, 100, 3000, 40000, ()),
        ("equipment:spurs", 289, 2, 25, 0, None, ("special-tool-effects",)),
        ("equipment:stirrups", 289, 3, 125, 20000, None, ("special-tool-effects",)),
        ("equipment:war-saddle", 289, 3, 250, 35000, None, ("special-tool-effects",)),
        # Law-enforcement, thief and spy gear, B289.
        (
            "equipment:audio-bug",
            289,
            7,
            200,
            0,
            None,
            ("battery-and-computer-operation", "special-tool-effects"),
        ),
        (
            "equipment:bug-stomper",
            289,
            7,
            1200,
            2000,
            None,
            ("battery-and-computer-operation", "special-tool-effects"),
        ),
        ("equipment:disguise-kit", 289, 5, 200, 10000, None, ("special-tool-effects",)),
        ("equipment:electronic-lockpicks", 289, 7, 1500, 3000, None, ("special-tool-effects",)),
        ("equipment:handcuffs", 289, 5, 40, 500, None, ("special-tool-effects",)),
        (
            "equipment:homing-beacon",
            289,
            7,
            40,
            0,
            None,
            ("battery-and-computer-operation", "special-tool-effects"),
        ),
        ("equipment:laser-microphone", 289, 8, 500, 2000, None, ("special-tool-effects",)),
        ("equipment:lockpicks", 289, 3, 50, 0, None, ("special-tool-effects",)),
        ("equipment:nanobug", 289, 8, 100, 0, None, ("special-tool-effects",)),
        ("equipment:shotgun-microphone", 289, 6, 250, 2000, None, ("special-tool-effects",)),
        # Optics and sensors, B289.
        ("equipment:binoculars", 289, 6, 400, 2000, None, ("special-tool-effects",)),
        (
            "equipment:camcorder",
            289,
            8,
            1000,
            1000,
            None,
            ("battery-and-computer-operation", "special-tool-effects"),
        ),
        ("equipment:camera-35mm", 289, 6, 50, 3000, None, ("special-tool-effects",)),
        ("equipment:camera-film-32", 289, 6, 10, 0, None, ()),
        (
            "equipment:metal-detector-wand",
            289,
            7,
            50,
            1000,
            None,
            ("battery-and-computer-operation", "special-tool-effects"),
        ),
        ("equipment:digital-mini-camera", 289, 8, 500, 0, None, ("special-tool-effects",)),
        (
            "equipment:night-vision-goggles",
            289,
            8,
            600,
            2000,
            None,
            ("battery-and-computer-operation", "special-tool-effects"),
        ),
        ("equipment:spy-camera", 289, 6, 500, 0, None, ("special-tool-effects",)),
        ("equipment:telescope", 289, 4, 500, 6000, None, ("special-tool-effects",)),
        # Fixed-TL tools, B289.
        ("equipment:balance-and-weights", 289, 1, 35, 3000, None, ("special-tool-effects",)),
        ("equipment:three-foot-crowbar", 289, 2, 20, 3000, None, ("special-tool-effects",)),
        ("equipment:cutting-torch", 289, 6, 500, 30000, None, ("special-tool-effects",)),
        ("equipment:cutting-torch-gas-bottle", 289, 6, 50, 15000, None, ("fuel-consumption",)),
        ("equipment:knitting-needles", 289, 3, 5, 0, None, ()),
        ("equipment:pickaxe", 289, 2, 15, 8000, None, ("special-tool-effects",)),
        ("equipment:iron-plow", 289, 2, 220, 120000, None, ("special-tool-effects",)),
        ("equipment:wooden-plow", 289, 1, 55, 60000, None, ("special-tool-effects",)),
        ("equipment:saw", 289, 0, 150, 3000, None, ("special-tool-effects",)),
        ("equipment:shovel", 289, 1, 12, 6000, None, ("special-tool-effects",)),
        ("equipment:spinning-wheel", 289, 3, 100, 40000, None, ("special-tool-effects",)),
        ("equipment:wheelbarrow", 289, 2, 60, 18000, 350000, ("special-tool-effects",)),
        ("equipment:whetstone", 289, 1, 5, 1000, None, ("special-tool-effects",)),
        # Skill-relative and portable specialist kits, B289.
        (
            "equipment:bandages",
            289,
            "skill-relative",
            10,
            2000,
            None,
            ("technology-level-variants", "special-tool-effects"),
        ),
        (
            "equipment:crash-kit",
            289,
            "skill-relative",
            200,
            10000,
            None,
            ("technology-level-variants", "special-tool-effects"),
        ),
        (
            "equipment:first-aid-kit",
            289,
            "skill-relative",
            50,
            2000,
            None,
            ("technology-level-variants", "special-tool-effects"),
        ),
        (
            "equipment:surgical-instruments",
            289,
            "skill-relative",
            300,
            15000,
            None,
            ("technology-level-variants", "special-tool-effects"),
        ),
        (
            "equipment:portable-carpentry-tool-kit",
            289,
            1,
            300,
            20000,
            None,
            ("special-tool-effects",),
        ),
        (
            "equipment:portable-armoury-tool-kit",
            289,
            1,
            600,
            20000,
            None,
            ("special-tool-effects",),
        ),
        (
            "equipment:portable-explosives-tool-kit",
            289,
            5,
            600,
            20000,
            None,
            ("special-tool-effects",),
        ),
        (
            "equipment:portable-machinist-tool-kit",
            289,
            5,
            600,
            20000,
            None,
            ("special-tool-effects",),
        ),
        (
            "equipment:portable-mechanic-tool-kit",
            289,
            5,
            600,
            20000,
            None,
            ("special-tool-effects",),
        ),
        (
            "equipment:portable-electrician-tool-kit",
            289,
            6,
            600,
            20000,
            None,
            ("special-tool-effects",),
        ),
        (
            "equipment:portable-electronics-repair-tool-kit",
            289,
            6,
            1200,
            10000,
            None,
            ("special-tool-effects",),
        ),
        (
            "equipment:suitcase-lab",
            289,
            "skill-relative",
            3000,
            10000,
            None,
            ("technology-level-variants", "special-tool-effects"),
        ),
        # Weapon and combat accessories, B289.
        ("equipment:ear-muffs", 289, 6, 200, 1000, None, ("weapon-accessories",)),
        ("equipment:hip-quiver", 289, 0, 15, 1000, None, ("weapon-accessories",)),
        ("equipment:belt-holster", 289, 5, 25, 500, None, ("weapon-accessories",)),
        ("equipment:shoulder-holster", 289, 5, 50, 1000, None, ("weapon-accessories",)),
        ("equipment:leather-lanyard", 289, 0, 1, 0, None, ("weapon-accessories",)),
        ("equipment:woven-steel-lanyard", 289, 6, 15, 0, None, ("weapon-accessories",)),
        (
            "equipment:laser-sight",
            289,
            8,
            100,
            0,
            None,
            ("weapon-accessories", "battery-and-computer-operation"),
        ),
        ("equipment:scope-4x", 289, 6, 150, 1500, None, ("weapon-accessories",)),
        (
            "equipment:thermal-scope-4x",
            289,
            8,
            8000,
            4000,
            None,
            ("weapon-accessories", "battery-and-computer-operation"),
        ),
        ("equipment:shoulder-quiver", 289, 0, 10, 500, None, ("weapon-accessories",)),
        ("equipment:pistol-smg-silencer", 289, 6, 400, 1000, None, ("weapon-accessories",)),
        ("equipment:web-gear", 289, 6, 50, 2000, None, ("weapon-accessories",)),
    )
)
