"""Complete Characters B281 heavy-weapon and liquid-projector tables."""

from decimal import Decimal
from fractions import Fraction
from typing import Literal

from wayfarer.engine.rules.types.explosion import ExplosionSpec
from wayfarer.engine.rules.types.firearm import FirearmSpec
from wayfarer.engine.rules.types.mount import MountSpec
from wayfarer.engine.rules.types.ranged_equipment import BackBlastSpec, WeaponAttachmentSpec
from wayfarer.engine.rules.types.special_ranged import GuidanceSpec
from wayfarer.engine.rules.types.spray import SprayerSpec
from wayfarer.engine.simulation.equipment.basic.rows import source
from wayfarer.engine.simulation.equipment.catalog import (
    Damage,
    DamageType,
    EquipmentProfile,
    RangedMode,
    SmartgunSpec,
)


def _mode(
    identifier: str,
    skill: str,
    tl: int,
    dice: int,
    adds: int,
    multiplier: int,
    damage_type: DamageType,
    divisor: str,
    acc: int,
    half_range: int | None,
    maximum_range: int,
    rof: int,
    shots: int,
    reload_seconds: int,
    st: int,
    bulk: int,
    recoil: int,
    ammunition: str,
    *,
    minimum_range: int = 0,
    guidance: GuidanceSpec | None = None,
    back_blast: BackBlastSpec | None = None,
    brace_kind: Literal["one-handed", "bipod"] | None = None,
    mount: MountSpec | None = None,
    loses_armor_divisor_at_half_range: bool = False,
    minimum_shots_per_attack: int = 1,
    attachment: WeaponAttachmentSpec | None = None,
    scope_bonus: int = 0,
    smartgun: SmartgunSpec | None = None,
    firearm: FirearmSpec | None = None,
    omit_firearm: bool = False,
) -> RangedMode:
    firearm_spec = (
        None
        if omit_firearm
        else firearm
        or FirearmSpec(
            technology_level=tl,
            action="repeating" if damage_type.startswith("pi") else "launcher",
            armoury_skill_id="skill:armoury-heavy-weapons",
        )
    )
    return RangedMode(
        id="shot",
        skill_id="skill:" + skill,
        minimum_st=st,
        hands=2,
        damage=Damage(
            basis="fixed",
            dice=dice,
            adds=adds,
            multiplier=multiplier,
            damage_type=damage_type,
            armor_divisor=Decimal(divisor),
        ),
        accuracy=acc,
        range_basis="yards",
        half_damage_range=half_range,
        maximum_range=maximum_range,
        rate_of_fire=rof,
        shots=shots,
        reload_seconds=reload_seconds,
        bulk=bulk,
        recoil=recoil,
        ammunition_id="equipment:" + ammunition,
        firearm=firearm_spec,
        minimum_range=minimum_range,
        guidance=guidance,
        back_blast=back_blast,
        brace_kind=brace_kind,
        mount=mount,
        loses_armor_divisor_at_half_range=loses_armor_divisor_at_half_range,
        minimum_shots_per_attack=minimum_shots_per_attack,
        attachment=attachment,
        scope_bonus=scope_bonus,
        smartgun=smartgun,
    )


def _weapon(
    identifier: str,
    tl: int,
    price: int,
    weight: int,
    mode: RangedMode,
    legality: int,
) -> EquipmentProfile:
    return EquipmentProfile(
        definition_id="equipment:" + identifier,
        provenance=source(281),
        weight_millipounds=weight,
        price=price,
        technology_level=tl,
        legality_class=legality,
        slot="hand",
        modes=(mode,),
    )


BACK_BLAST_15 = BackBlastSpec(dice=1, range_yards=15)

HEAVY_WEAPONS = (
    _weapon(
        "atgm-115mm",
        7,
        20000,
        37000,
        _mode(
            "atgm-115mm",
            "artillery-guided-missile",
            7,
            6,
            0,
            10,
            "cr",
            "10",
            3,
            200,
            2000,
            1,
            1,
            20,
            11,
            -10,
            1,
            "atgm-115mm-missile",
            minimum_range=30,
            guidance=GuidanceSpec(kind="guided"),
            back_blast=BackBlastSpec(dice=1, range_yards=30),
            brace_kind="bipod",
            mount=MountSpec(crew=1, laying_seconds=0),
        ),
        1,
    ),
    _weapon(
        "sam-70mm",
        8,
        38000,
        18000,
        _mode(
            "sam-70mm",
            "artillery-guided-missile",
            8,
            6,
            0,
            3,
            "cr",
            "1",
            7,
            1000,
            8800,
            1,
            1,
            20,
            10,
            -8,
            1,
            "sam-70mm-missile",
            minimum_range=200,
            guidance=GuidanceSpec(
                kind="homing", seeker_skill=10, seeker_sense="hyperspectral-vision"
            ),
            mount=MountSpec(crew=1, laying_seconds=0),
        ),
        1,
    ),
    _weapon(
        "scorpion",
        2,
        5000,
        110000,
        _mode(
            "scorpion",
            "gunner-catapult",
            3,
            5,
            0,
            1,
            "imp",
            "1",
            3,
            415,
            520,
            1,
            1,
            30,
            45,
            -10,
            1,
            "scorpion-bolt",
            mount=MountSpec(
                crew=2,
                laying_seconds=0,
            ),
            omit_firearm=True,
        ),
        2,
    ),
    _weapon(
        "hmg-50",
        6,
        14000,
        84000,
        _mode(
            "hmg-50",
            "gunner-machine-gun",
            6,
            13,
            1,
            1,
            "pi+",
            "1",
            6,
            1800,
            7400,
            8,
            100,
            5,
            20,
            -8,
            2,
            "hmg-50-round",
            minimum_shots_per_attack=8,
            mount=MountSpec(
                crew=2,
                laying_seconds=0,
                required_mount_definition_id="equipment:hmg-50-tripod",
            ),
        ),
        1,
    ),
    _weapon(
        "under-barrel-40mm",
        7,
        500,
        3000,
        _mode(
            "under-barrel-40mm",
            "guns-grenade-launcher",
            7,
            4,
            0,
            1,
            "cr",
            "10",
            2,
            150,
            440,
            1,
            1,
            3,
            11,
            -1,
            2,
            "grenade-40mm",
            minimum_range=10,
            loses_armor_divisor_at_half_range=True,
            attachment=WeaponAttachmentSpec(
                kind="under-barrel",
                minimum_host_tl=7,
                host_skill_ids=("skill:guns-rifle",),
            ),
        ),
        1,
    ),
    _weapon(
        "integral-25mm",
        9,
        0,
        0,
        _mode(
            "integral-25mm",
            "guns-grenade-launcher",
            9,
            7,
            0,
            1,
            "cr",
            "1",
            4,
            None,
            2200,
            1,
            3,
            3,
            10,
            -1,
            3,
            "grenade-25mm",
            scope_bonus=2,
            smartgun=SmartgunSpec(),
            attachment=WeaponAttachmentSpec(
                kind="integral", minimum_host_tl=9, host_definition_id="equipment:icw-68mm"
            ),
        ),
        1,
    ),
    _weapon(
        "bazooka-60mm",
        7,
        1000,
        13300,
        _mode(
            "bazooka-60mm",
            "guns-light-anti-armor-weapon",
            7,
            6,
            0,
            2,
            "cr",
            "10",
            3,
            100,
            650,
            1,
            1,
            4,
            10,
            -6,
            1,
            "bazooka-60mm-rocket",
            back_blast=BACK_BLAST_15,
            loses_armor_divisor_at_half_range=True,
        ),
        1,
    ),
    _weapon(
        "rpg-85mm",
        7,
        800,
        15300,
        _mode(
            "rpg-85mm",
            "guns-light-anti-armor-weapon",
            7,
            6,
            0,
            3,
            "cr",
            "10",
            3,
            300,
            1000,
            1,
            1,
            5,
            10,
            -6,
            1,
            "rpg-85mm-rocket",
            back_blast=BACK_BLAST_15,
            loses_armor_divisor_at_half_range=True,
            scope_bonus=1,
        ),
        1,
    ),
    _weapon(
        "law-84mm",
        8,
        750,
        14700,
        _mode(
            "law-84mm",
            "guns-light-anti-armor-weapon",
            8,
            6,
            0,
            6,
            "cr",
            "10",
            3,
            330,
            2300,
            1,
            1,
            0,
            10,
            -5,
            1,
            "law-84mm-rocket",
            back_blast=BACK_BLAST_15,
            loses_armor_divisor_at_half_range=True,
            firearm=FirearmSpec(
                technology_level=8,
                action="single-use",
                armoury_skill_id="skill:armoury-heavy-weapons",
            ),
        ),
        1,
    ),
    _weapon(
        "auto-rifle-762",
        6,
        6500,
        20400,
        _mode(
            "auto-rifle-762",
            "guns-light-machine-gun",
            6,
            7,
            0,
            1,
            "pi",
            "1",
            5,
            1000,
            4200,
            9,
            20,
            3,
            12,
            -6,
            3,
            "auto-rifle-762-round",
            minimum_shots_per_attack=9,
            brace_kind="bipod",
        ),
        2,
    ),
    _weapon(
        "lmg-762",
        6,
        6600,
        24000,
        _mode(
            "lmg-762",
            "guns-light-machine-gun",
            6,
            7,
            0,
            1,
            "pi",
            "1",
            5,
            1000,
            4200,
            15,
            100,
            5,
            13,
            -6,
            2,
            "lmg-762-round",
            minimum_shots_per_attack=15,
            brace_kind="bipod",
        ),
        1,
    ),
    _weapon(
        "saw-556",
        7,
        4800,
        17000,
        _mode(
            "saw-556",
            "guns-light-machine-gun",
            7,
            5,
            1,
            1,
            "pi",
            "1",
            5,
            800,
            3500,
            12,
            200,
            5,
            12,
            -6,
            2,
            "saw-556-round",
            minimum_shots_per_attack=12,
            brace_kind="bipod",
        ),
        1,
    ),
    _weapon(
        "flamethrower",
        6,
        1800,
        70000,
        RangedMode(
            id="stream",
            skill_id="skill:liquid-projector-flamethrower",
            minimum_st=10,
            hands=2,
            damage=Damage(basis="fixed", dice=3, damage_type="burn"),
            accuracy=0,
            range_basis="yards",
            maximum_range=50,
            shots=10,
            reload_seconds=0,
            bulk=-8,
            ammunition_id="equipment:flamethrower-fuel",
            sprayer=SprayerSpec(sustained_seconds=10, rounds_per_second=1, ignites=True),
        ),
        1,
    ),
)


def _ammo(
    identifier: str,
    tl: int,
    weight: int | Fraction,
    price: int | Fraction,
    warhead: ExplosionSpec | None = None,
) -> EquipmentProfile:
    return EquipmentProfile(
        definition_id="equipment:" + identifier,
        provenance=source(281),
        weight_millipounds=weight,
        price=price,
        technology_level=tl,
        ammunition=True,
        warhead=warhead,
    )


HEAVY_AMMUNITION = (
    _ammo(
        "atgm-115mm-missile",
        7,
        26000,
        0,
        ExplosionSpec(dice=6, multiplier=10, armor_divisor=Decimal(10)),
    ),
    _ammo(
        "sam-70mm-missile", 8, 22000, 0, ExplosionSpec(dice=6, multiplier=3, fragmentation_dice=6)
    ),
    _ammo("scorpion-bolt", 2, 900, 18),
    _ammo("hmg-50-round", 6, 320, Fraction(32, 5)),
    _ammo(
        "grenade-40mm",
        7,
        500,
        10,
        ExplosionSpec(dice=4, armor_divisor=Decimal(10), fragmentation_dice=2),
    ),
    _ammo(
        "grenade-25mm",
        9,
        Fraction(1600, 3),
        Fraction(32, 3),
        ExplosionSpec(dice=7, fragmentation_dice=3),
    ),
    _ammo(
        "bazooka-60mm-rocket",
        7,
        3400,
        0,
        ExplosionSpec(dice=6, multiplier=2, armor_divisor=Decimal(10)),
    ),
    _ammo(
        "rpg-85mm-rocket",
        7,
        5700,
        0,
        ExplosionSpec(dice=6, multiplier=3, armor_divisor=Decimal(10)),
    ),
    _ammo(
        "law-84mm-rocket", 8, 0, 0, ExplosionSpec(dice=6, multiplier=6, armor_divisor=Decimal(10))
    ),
    _ammo("auto-rifle-762-round", 6, 80, Fraction(8, 5)),
    _ammo("lmg-762-round", 6, 60, Fraction(6, 5)),
    _ammo("saw-556-round", 7, 35, Fraction(7, 10)),
    _ammo("flamethrower-fuel", 6, 0, 0),
)

HEAVY_SUPPORT = (
    EquipmentProfile(
        definition_id="equipment:hmg-50-tripod",
        provenance=source(281),
        weight_millipounds=44000,
        price=0,
        technology_level=6,
    ),
)
