"""Representative higher-TL weapons and their ammunition."""

from decimal import Decimal
from fractions import Fraction

from wayfarer.engine.rules.types.firearm import FirearmSpec
from wayfarer.engine.rules.types.ranged_equipment import FollowUpSpec
from wayfarer.engine.simulation.equipment.basic.rows import ranged_weapon, source
from wayfarer.engine.simulation.equipment.catalog import (
    Damage,
    EquipmentProfile,
    RangedMode,
    RocketAcceleration,
    SmartgunSpec,
)

HIGHER_TL_WEAPONS = (
    ranged_weapon(
        "gyroc-pistol-15mm",
        278,
        9,
        200,
        600,
        RangedMode(
            id="shot",
            skill_id="skill:guns-gyroc",
            minimum_st=9,
            damage=Damage(basis="fixed", dice=6, damage_type="pi++"),
            accuracy=1,
            range_basis="yards",
            maximum_range=1900,
            rate_of_fire=3,
            shots=4,
            reload_seconds=3,
            reload_protocol="per-round",
            bulk=-2,
            recoil=1,
            ammunition_id="equipment:gyroc-pistol-15mm-round",
            firearm=FirearmSpec(
                technology_level=9,
                action="repeating",
                armoury_skill_id="skill:armoury-small-arms",
            ),
            rocket_acceleration=RocketAcceleration(
                close_max_yards=2,
                close_damage_divisor=3,
                medium_max_yards=10,
                medium_damage_divisor=2,
            ),
            smartgun=SmartgunSpec(),
        ),
    ),
    ranged_weapon(
        "laser-pistol",
        280,
        10,
        2800,
        2800,
        RangedMode(
            id="beam",
            skill_id="skill:beam-weapons-pistol",
            minimum_st=6,
            damage=Damage(
                basis="fixed",
                dice=3,
                damage_type="burn",
                armor_divisor=Decimal(2),
                tight_beam=True,
            ),
            accuracy=6,
            range_basis="yards",
            half_damage_range=250,
            maximum_range=750,
            rate_of_fire=10,
            shots=400,
            reload_seconds=3,
            bulk=-2,
            recoil=1,
            ammunition_id="equipment:laser-pistol-cell",
            firearm=FirearmSpec(
                technology_level=10,
                action="beam",
                armoury_skill_id="skill:armoury-small-arms",
            ),
            smartgun=SmartgunSpec(),
            beam_environment_dr=True,
        ),
    ),
    ranged_weapon(
        "auto-pistol-9mm-tl9",
        278,
        9,
        800,
        1300,
        RangedMode(
            id="shot",
            skill_id="skill:guns-pistol",
            minimum_st=9,
            damage=Damage(basis="fixed", dice=2, adds=2, damage_type="pi"),
            accuracy=2,
            range_basis="yards",
            half_damage_range=150,
            maximum_range=1900,
            rate_of_fire=3,
            shots=19,
            chamber_capacity=1,
            reload_seconds=3,
            bulk=-2,
            recoil=2,
            ammunition_id="equipment:auto-pistol-9mm-tl9-round",
            firearm=FirearmSpec(
                technology_level=9, action="repeating", armoury_skill_id="skill:armoury-small-arms"
            ),
            smartgun=SmartgunSpec(),
        ),
    ),
    ranged_weapon(
        "gauss-pdw-4mm",
        278,
        10,
        3600,
        3600,
        RangedMode(
            id="shot",
            skill_id="skill:guns-smg",
            minimum_st=9,
            hands=2,
            damage=Damage(basis="fixed", dice=4, damage_type="pi-", armor_divisor=Decimal(3)),
            accuracy=6,
            scope_bonus=1,
            range_basis="yards",
            half_damage_range=700,
            maximum_range=2900,
            rate_of_fire=16,
            shots=80,
            reload_seconds=3,
            bulk=-3,
            recoil=2,
            ammunition_id="equipment:gauss-pdw-4mm-round",
            firearm=FirearmSpec(
                technology_level=10, action="repeating", armoury_skill_id="skill:armoury-small-arms"
            ),
            smartgun=SmartgunSpec(),
        ),
    ),
    ranged_weapon(
        "matchlock-musket-80",
        279,
        4,
        150,
        19950,
        RangedMode(
            id="shot",
            skill_id="skill:guns-musket",
            minimum_st=10,
            hands=2,
            damage=Damage(basis="fixed", dice=4, damage_type="pi++"),
            accuracy=2,
            range_basis="yards",
            half_damage_range=100,
            maximum_range=600,
            shots=1,
            reload_seconds=60,
            bulk=-6,
            recoil=3,
            ammunition_id="equipment:matchlock-musket-80-round",
            firearm=FirearmSpec(
                technology_level=4,
                action="muzzleloader",
                armoury_skill_id="skill:armoury-small-arms",
            ),
            brace_kind="bipod",
        ),
    ),
    ranged_weapon(
        "dart-rifle-11mm",
        279,
        8,
        1200,
        6580,
        RangedMode(
            id="shot",
            skill_id="skill:guns-rifle",
            minimum_st=9,
            hands=2,
            damage=Damage(basis="fixed", dice=1, damage_type="pi-", armor_divisor=Decimal("0.2")),
            accuracy=5,
            scope_bonus=1,
            range_basis="yards",
            half_damage_range=45,
            maximum_range=145,
            shots=1,
            reload_seconds=3,
            bulk=-5,
            recoil=2,
            ammunition_id="equipment:dart-rifle-11mm-round",
            firearm=FirearmSpec(
                technology_level=8,
                action="breechloader",
                armoury_skill_id="skill:armoury-small-arms",
            ),
            linked_follow_up=FollowUpSpec(
                payload_id="equipment:tranquilizer-dose",
                kind="drug",
                resistance_penalty=-3,
                condition="unconsciousness",
                duration_minutes_per_margin=1,
            ),
        ),
    ),
    ranged_weapon(
        "sniper-rifle-338",
        279,
        8,
        5600,
        16700,
        RangedMode(
            id="shot",
            skill_id="skill:guns-rifle",
            minimum_st=11,
            hands=2,
            damage=Damage(basis="fixed", dice=9, adds=1, damage_type="pi"),
            accuracy=6,
            scope_bonus=3,
            fixed_power_scope=True,
            range_basis="yards",
            half_damage_range=1500,
            maximum_range=5500,
            shots=5,
            chamber_capacity=1,
            reload_seconds=3,
            reload_protocol="per-round",
            bulk=-6,
            recoil=4,
            ammunition_id="equipment:sniper-rifle-338-round",
            brace_kind="bipod",
            firearm=FirearmSpec(
                technology_level=8, action="repeating", armoury_skill_id="skill:armoury-small-arms"
            ),
        ),
    ),
    ranged_weapon(
        "icw-68mm",
        279,
        9,
        7000,
        10500,
        RangedMode(
            id="shot",
            skill_id="skill:guns-rifle",
            minimum_st=10,
            hands=2,
            damage=Damage(basis="fixed", dice=6, damage_type="pi"),
            accuracy=4,
            scope_bonus=2,
            range_basis="yards",
            half_damage_range=700,
            maximum_range=4000,
            rate_of_fire=15,
            shots=26,
            chamber_capacity=1,
            reload_seconds=3,
            bulk=-5,
            recoil=2,
            ammunition_id="equipment:icw-68mm-round",
            firearm=FirearmSpec(
                technology_level=9, action="repeating", armoury_skill_id="skill:armoury-small-arms"
            ),
            smartgun=SmartgunSpec(),
        ),
    ),
    ranged_weapon(
        "gauss-rifle-4mm",
        279,
        10,
        7100,
        7100,
        RangedMode(
            id="shot",
            skill_id="skill:guns-rifle",
            minimum_st=10,
            hands=2,
            damage=Damage(
                basis="fixed", dice=6, adds=2, damage_type="pi-", armor_divisor=Decimal(3)
            ),
            accuracy=7,
            scope_bonus=2,
            range_basis="yards",
            half_damage_range=1200,
            maximum_range=4800,
            rate_of_fire=12,
            shots=60,
            reload_seconds=3,
            bulk=-4,
            recoil=2,
            ammunition_id="equipment:gauss-rifle-4mm-round",
            firearm=FirearmSpec(
                technology_level=10, action="repeating", armoury_skill_id="skill:armoury-small-arms"
            ),
            smartgun=SmartgunSpec(),
        ),
    ),
)

HIGHER_TL_AMMUNITION = (
    EquipmentProfile(
        definition_id="equipment:gyroc-pistol-15mm-round",
        provenance=source(278),
        weight_millipounds=100,
        price=2,
        technology_level=9,
        ammunition=True,
    ),
    EquipmentProfile(
        definition_id="equipment:laser-pistol-cell",
        provenance=source(280),
        weight_millipounds=500,
        price=10,
        technology_level=10,
        ammunition=True,
        power_cell_capacity=400,
    ),
    *tuple(
        EquipmentProfile(
            definition_id="equipment:" + identifier,
            provenance=source(page),
            weight_millipounds=weight,
            price=price,
            technology_level=tl,
            ammunition=True,
        )
        for identifier, page, tl, weight, price in (
            ("auto-pistol-9mm-tl9-round", 278, 9, Fraction(700, 19), Fraction(14, 19)),
            ("gauss-pdw-4mm-round", 278, 10, Fraction(25, 2), Fraction(1, 4)),
            ("matchlock-musket-80-round", 279, 4, 50, 1),
            ("dart-rifle-11mm-round", 279, 8, 20, Fraction(2, 5)),
            ("sniper-rifle-338-round", 279, 8, 160, Fraction(16, 5)),
            ("icw-68mm-round", 279, 9, Fraction(750, 13), Fraction(15, 13)),
            ("gauss-rifle-4mm-round", 279, 10, Fraction(70, 3), Fraction(7, 15)),
        )
    ),
)
