"""Basic Set melee weapon rows (B271-274, B283)."""

from wayfarer.engine.simulation.equipment.basic.rows import melee, weapon

# B271-274. Natural attacks and table rows without physical item cost/weight are
# accounted for in the ledger rather than invented as equipment. Superscience,
# variable-ST and extra-die rows remain explicit omissions until the typed schema
# can represent their values exactly.
WEAPONS = (
    weapon(
        "light-club",
        271,
        0,
        5,
        3000,
        melee("swing", "broadsword", 10, "swing", 1, "cr", (1,)),
        melee("thrust", "broadsword", 10, "thrust", 1, "cr", (1,)),
        durability_dr=2,
    ),
    weapon(
        "broadsword",
        271,
        2,
        500,
        3000,
        melee("swing", "broadsword", 10, "swing", 1, "cut", (1,)),
        melee("thrust", "broadsword", 10, "thrust", 1, "cr", (1,)),
        durability_dr=6,
    ),
    weapon(
        "axe",
        271,
        0,
        50,
        4000,
        melee("axe-mace-swing", "axe-mace", 11, "swing", 2, "cut", (1,), unbalanced=True),
    ),
    weapon(
        "hatchet",
        271,
        0,
        40,
        2000,
        melee("axe-mace-swing", "axe-mace", 8, "swing", 0, "cut", (1,)),
        unsupported=("alternate-thrown-mode",),
    ),
    weapon(
        "throwing-axe",
        271,
        0,
        60,
        4000,
        melee("axe-mace-swing", "axe-mace", 11, "swing", 2, "cut", (1,), unbalanced=True),
        unsupported=("alternate-thrown-mode",),
    ),
    weapon(
        "mace",
        271,
        2,
        50,
        5000,
        melee("axe-mace-swing", "axe-mace", 12, "swing", 3, "cr", (1,), unbalanced=True),
        unsupported=("alternate-thrown-mode",),
    ),
    weapon(
        "small-mace",
        271,
        2,
        35,
        3000,
        melee("axe-mace-swing", "axe-mace", 10, "swing", 2, "cr", (1,), unbalanced=True),
        unsupported=("alternate-thrown-mode",),
    ),
    weapon(
        "pick",
        271,
        3,
        70,
        3000,
        melee("axe-mace-swing", "axe-mace", 10, "swing", 1, "imp", (1,), unbalanced=True),
        unsupported=("pick-stuck",),
    ),
    weapon(
        "blackjack",
        271,
        1,
        20,
        1000,
        melee("brawling-thrust", "brawling", 7, "thrust", 0, "cr", (0,)),
    ),
    weapon(
        "thrusting-broadsword",
        271,
        2,
        600,
        3000,
        melee("broadsword-swing", "broadsword", 10, "swing", 1, "cut", (1,)),
        melee("broadsword-thrust", "broadsword", 10, "thrust", 2, "imp", (1,)),
    ),
    weapon(
        "bastard-sword",
        (271, 274),
        3,
        650,
        5000,
        melee("broadsword-swing", "broadsword", 11, "swing", 1, "cut", (1, 2), unbalanced=True),
        melee("broadsword-thrust", "broadsword", 11, "thrust", 1, "cr", (2,), unbalanced=True),
        melee("two-handed-sword-swing", "two-handed-sword", 10, "swing", 2, "cut", (1, 2), hands=2),
        melee("two-handed-sword-thrust", "two-handed-sword", 10, "thrust", 2, "cr", (2,), hands=2),
    ),
    weapon(
        "katana",
        (271, 274),
        3,
        650,
        5000,
        melee("broadsword-swing", "broadsword", 11, "swing", 1, "cut", (1, 2)),
        melee("broadsword-thrust", "broadsword", 11, "thrust", 1, "imp", (1,)),
        melee("two-handed-sword-swing", "two-handed-sword", 10, "swing", 2, "cut", (1, 2), hands=2),
        melee("two-handed-sword-thrust", "two-handed-sword", 10, "thrust", 1, "imp", (1,), hands=2),
    ),
    weapon(
        "thrusting-bastard-sword",
        (271, 274),
        3,
        750,
        5000,
        melee("broadsword-swing", "broadsword", 11, "swing", 1, "cut", (1, 2), unbalanced=True),
        melee("broadsword-thrust", "broadsword", 11, "thrust", 2, "imp", (2,), unbalanced=True),
        melee("two-handed-sword-swing", "two-handed-sword", 10, "swing", 2, "cut", (1, 2), hands=2),
        melee("two-handed-sword-thrust", "two-handed-sword", 10, "thrust", 3, "imp", (2,), hands=2),
    ),
    weapon(
        "cavalry-saber",
        271,
        4,
        500,
        3000,
        melee("broadsword-swing", "broadsword", 10, "swing", 1, "cut", (1,)),
        melee("broadsword-thrust", "broadsword", 10, "thrust", 1, "imp", (1,)),
    ),
    weapon(
        "morningstar",
        272,
        3,
        80,
        6000,
        melee("flail-swing", "flail", 12, "swing", 3, "cr", (1,), unbalanced=True),
        unsupported=("flail-defense-penalties",),
    ),
    weapon(
        "nunchaku",
        272,
        3,
        20,
        2000,
        melee("flail-swing", "flail", 7, "swing", 1, "cr", (1,), unbalanced=True),
        unsupported=("flail-defense-penalties",),
    ),
    weapon(
        "large-knife",
        272,
        0,
        40,
        1000,
        melee("knife-swing", "knife", 6, "swing", -2, "cut", (0, 1), parry=-1),
        melee("knife-thrust", "knife", 6, "thrust", 0, "imp", (0,), parry=-1),
        unsupported=("alternate-thrown-mode",),
    ),
    weapon(
        "small-knife",
        272,
        0,
        30,
        500,
        melee("knife-swing", "knife", 5, "swing", -3, "cut", (0, 1), parry=-1),
        melee("knife-thrust", "knife", 5, "thrust", -1, "imp", (0,), parry=-1),
        unsupported=("alternate-thrown-mode",),
    ),
    weapon(
        "wooden-stake",
        272,
        0,
        4,
        500,
        melee("knife-thrust", "knife", 5, "thrust", 0, "imp", (0,), parry=-1, divisor="0.5"),
        unsupported=("alternate-thrown-mode",),
    ),
    weapon(
        "dagger",
        272,
        1,
        20,
        250,
        melee("knife-thrust", "knife", 5, "thrust", -1, "imp", (0,), parry=-1),
        unsupported=("alternate-thrown-mode",),
    ),
    weapon(
        "kusari",
        272,
        3,
        70,
        5000,
        melee(
            "kusari-swing", "kusari", 11, "swing", 2, "cr", (1, 2, 3, 4), parry=-2, unbalanced=True
        ),
        unsupported=("flail-defense-penalties", "variable-reach-ready"),
    ),
    weapon(
        "lance",
        272,
        2,
        60,
        6000,
        melee("lance-thrust", "lance", 12, "thrust", 3, "imp", (4,), parry=None),
        unsupported=("mounted-lance-damage",),
    ),
    weapon(
        "glaive",
        272,
        1,
        100,
        8000,
        melee(
            "polearm-swing",
            "polearm",
            11,
            "swing",
            3,
            "cut",
            (2, 3),
            hands=2,
            unbalanced=True,
            ready_after_attack=True,
        ),
        melee(
            "polearm-thrust", "polearm", 11, "thrust", 3, "imp", (1, 2, 3), hands=2, unbalanced=True
        ),
        unsupported=("conditional-ready-after-attack", "variable-reach-ready"),
    ),
    weapon(
        "naginata",
        (272, 273, 274),
        2,
        100,
        6000,
        melee("polearm-swing", "polearm", 9, "swing", 2, "cut", (1, 2), hands=2, unbalanced=True),
        melee("polearm-thrust", "polearm", 9, "thrust", 3, "imp", (2,), hands=2),
        melee("staff-swing", "staff", 9, "swing", 2, "cr", (1, 2), hands=2, unbalanced=True),
        melee("staff-thrust", "staff", 9, "thrust", 2, "cr", (1, 2), hands=2),
        melee(
            "two-handed-sword-swing",
            "two-handed-sword",
            9,
            "swing",
            3,
            "cut",
            (2,),
            hands=2,
            unbalanced=True,
        ),
        melee("two-handed-sword-thrust", "two-handed-sword", 9, "thrust", 3, "imp", (2,), hands=2),
        unsupported=("variable-reach-ready",),
    ),
    weapon(
        "halberd",
        272,
        3,
        150,
        12000,
        melee(
            "polearm-cut",
            "polearm",
            13,
            "swing",
            5,
            "cut",
            (2, 3),
            hands=2,
            unbalanced=True,
            ready_after_attack=True,
        ),
        melee(
            "polearm-pick",
            "polearm",
            13,
            "swing",
            4,
            "imp",
            (2, 3),
            hands=2,
            unbalanced=True,
            ready_after_attack=True,
        ),
        melee(
            "polearm-thrust", "polearm", 12, "thrust", 3, "imp", (1, 2, 3), hands=2, unbalanced=True
        ),
        unsupported=("conditional-ready-after-attack", "pick-stuck", "variable-reach-ready"),
    ),
    weapon(
        "poleaxe",
        272,
        3,
        120,
        10000,
        melee(
            "polearm-cut",
            "polearm",
            12,
            "swing",
            4,
            "cut",
            (2, 3),
            hands=2,
            unbalanced=True,
            ready_after_attack=True,
        ),
        melee(
            "polearm-crush",
            "polearm",
            12,
            "swing",
            4,
            "cr",
            (2, 3),
            hands=2,
            unbalanced=True,
            ready_after_attack=True,
        ),
        unsupported=("conditional-ready-after-attack", "variable-reach-ready"),
    ),
    weapon(
        "rapier",
        273,
        4,
        500,
        2750,
        melee("rapier-thrust", "rapier", 9, "thrust", 1, "imp", (1, 2), fencing=True),
    ),
    weapon(
        "saber",
        273,
        4,
        700,
        2000,
        melee("saber-swing", "saber", 8, "swing", -1, "cut", (1,), fencing=True),
        melee("saber-thrust", "saber", 8, "thrust", 1, "imp", (1,), fencing=True),
    ),
    weapon(
        "baton",
        273,
        0,
        20,
        1000,
        melee("shortsword-swing", "shortsword", 6, "swing", 0, "cr", (1,)),
        melee("shortsword-thrust", "shortsword", 6, "thrust", 0, "cr", (1,)),
    ),
    weapon(
        "shortsword",
        273,
        2,
        400,
        2000,
        melee("shortsword-swing", "shortsword", 8, "swing", 0, "cut", (1,)),
        melee("shortsword-thrust", "shortsword", 8, "thrust", 0, "imp", (1,)),
    ),
    weapon(
        "cutlass",
        273,
        4,
        300,
        2000,
        melee("shortsword-swing", "shortsword", 8, "swing", 0, "cut", (1,)),
        melee("shortsword-thrust", "shortsword", 8, "thrust", 0, "imp", (1,)),
        unsupported=("cutlass-hilt",),
    ),
    weapon(
        "cattle-prod",
        273,
        7,
        50,
        2000,
        melee("shortsword-burn", "shortsword", 3, "fixed", -3, "burn", (1,), dice=1),
        unsupported=("linked-affliction",),
    ),
    weapon(
        "short-staff",
        273,
        0,
        20,
        1000,
        melee("smallsword-swing", "smallsword", 6, "swing", 0, "cr", (1,), fencing=True),
        melee("smallsword-thrust", "smallsword", 6, "thrust", 0, "cr", (1,), fencing=True),
    ),
    weapon(
        "smallsword",
        273,
        4,
        400,
        1500,
        melee("smallsword-thrust", "smallsword", 5, "thrust", 1, "imp", (1,), fencing=True),
    ),
    weapon(
        "spear",
        273,
        0,
        40,
        4000,
        melee("spear-one-hand", "spear", 9, "thrust", 2, "imp", (1,), hands=1),
        melee("spear-two-hands", "spear", 9, "thrust", 3, "imp", (1, 2), hands=2),
        unsupported=("alternate-thrown-mode", "variable-reach-ready"),
    ),
    weapon(
        "javelin",
        273,
        1,
        30,
        2000,
        melee("spear-thrust", "spear", 6, "thrust", 1, "imp", (1,)),
        unsupported=("alternate-thrown-mode",),
    ),
    weapon(
        "long-spear",
        273,
        2,
        60,
        5000,
        melee("spear-one-hand", "spear", 10, "thrust", 2, "imp", (2, 3), hands=1, unbalanced=True),
        melee("spear-two-hands", "spear", 10, "thrust", 3, "imp", (2, 3), hands=2),
        unsupported=("variable-reach-ready",),
    ),
    weapon(
        "quarterstaff",
        (273, 274),
        0,
        10,
        4000,
        melee("staff-swing", "staff", 7, "swing", 2, "cr", (1, 2), hands=2, parry=2),
        melee("staff-thrust", "staff", 7, "thrust", 2, "cr", (1, 2), hands=2, parry=2),
        melee("two-handed-sword-swing", "two-handed-sword", 9, "swing", 2, "cr", (1, 2), hands=2),
        melee("two-handed-sword-thrust", "two-handed-sword", 9, "thrust", 1, "cr", (2,), hands=2),
    ),
    weapon(
        "maul",
        274,
        0,
        80,
        12000,
        melee(
            "two-handed-axe-mace-swing",
            "two-handed-axe-mace",
            13,
            "swing",
            4,
            "cr",
            (1, 2),
            hands=2,
            unbalanced=True,
            ready_after_attack=True,
        ),
        unsupported=("conditional-ready-after-attack", "variable-reach-ready"),
    ),
    weapon(
        "great-axe",
        274,
        1,
        100,
        8000,
        melee(
            "two-handed-axe-mace-swing",
            "two-handed-axe-mace",
            12,
            "swing",
            3,
            "cut",
            (1, 2),
            hands=2,
            unbalanced=True,
            ready_after_attack=True,
        ),
        unsupported=("conditional-ready-after-attack", "variable-reach-ready"),
    ),
    weapon(
        "scythe",
        274,
        1,
        15,
        5000,
        melee(
            "two-handed-axe-mace-cut",
            "two-handed-axe-mace",
            11,
            "swing",
            2,
            "cut",
            (1,),
            hands=2,
            unbalanced=True,
            ready_after_attack=True,
        ),
        melee(
            "two-handed-axe-mace-pick",
            "two-handed-axe-mace",
            11,
            "swing",
            0,
            "imp",
            (1,),
            hands=2,
            unbalanced=True,
            ready_after_attack=True,
        ),
        unsupported=("conditional-ready-after-attack", "pick-stuck"),
    ),
    weapon(
        "warhammer",
        274,
        3,
        100,
        7000,
        melee(
            "two-handed-axe-mace-swing",
            "two-handed-axe-mace",
            12,
            "swing",
            3,
            "imp",
            (1, 2),
            hands=2,
            unbalanced=True,
            ready_after_attack=True,
        ),
        unsupported=("conditional-ready-after-attack", "pick-stuck", "variable-reach-ready"),
    ),
    weapon(
        "flail",
        274,
        2,
        100,
        8000,
        melee(
            "two-handed-flail-swing",
            "two-handed-flail",
            13,
            "swing",
            4,
            "cr",
            (1, 2),
            hands=2,
            unbalanced=True,
        ),
        unsupported=("flail-defense-penalties", "variable-reach-ready"),
    ),
    weapon(
        "greatsword",
        274,
        3,
        800,
        7000,
        melee("two-handed-sword-swing", "two-handed-sword", 12, "swing", 3, "cut", (1, 2), hands=2),
        melee("two-handed-sword-thrust", "two-handed-sword", 12, "thrust", 2, "cr", (2,), hands=2),
    ),
    weapon(
        "thrusting-greatsword",
        274,
        3,
        900,
        7000,
        melee("two-handed-sword-swing", "two-handed-sword", 12, "swing", 3, "cut", (1, 2), hands=2),
        melee("two-handed-sword-thrust", "two-handed-sword", 12, "thrust", 3, "imp", (2,), hands=2),
    ),
)
