"""Complete executable B280 beam-weapon table."""

from decimal import Decimal

from wayfarer.engine.rules.types.firearm import FirearmSpec
from wayfarer.engine.rules.types.ranged_equipment import FollowUpSpec
from wayfarer.engine.simulation.equipment.basic.rows import ranged_weapon, source
from wayfarer.engine.simulation.equipment.catalog import (
    Damage,
    EquipmentProfile,
    RangedMode,
    SmartgunSpec,
)


def _beam(
    identifier: str,
    tl: int,
    price: int,
    weight: int,
    skill: str,
    dice: int,
    adds: int,
    divisor: int,
    accuracy: int,
    scope: int,
    half_range: int,
    maximum_range: int,
    rate: int,
    shots: int,
    reload_seconds: int,
    st: int,
    bulk: int,
    cell: str,
    *,
    surge: bool = False,
    atmosphere: bool = False,
    affliction: FollowUpSpec | None = None,
) -> EquipmentProfile:
    return ranged_weapon(
        identifier,
        280,
        tl,
        price,
        weight,
        RangedMode(
            id="beam",
            skill_id="skill:beam-weapons-" + skill,
            minimum_st=st,
            hands=1 if skill == "pistol" else 2,
            damage=Damage(
                basis="fixed",
                dice=dice,
                adds=adds,
                damage_type="burn",
                armor_divisor=Decimal(divisor),
                tight_beam=True,
                surge=surge,
            ),
            accuracy=accuracy,
            scope_bonus=scope,
            fixed_power_scope=bool(scope),
            range_basis="yards",
            half_damage_range=half_range,
            maximum_range=maximum_range,
            rate_of_fire=rate,
            shots=shots,
            reload_seconds=reload_seconds,
            bulk=bulk,
            recoil=1,
            ammunition_id="equipment:" + cell,
            firearm=FirearmSpec(
                technology_level=tl, action="beam", armoury_skill_id="skill:armoury-small-arms"
            ),
            smartgun=SmartgunSpec(),
            beam_environment_dr=True,
            linked_follow_up=affliction,
            requires_atmosphere=atmosphere,
        ),
    )


ELECTROLASER = FollowUpSpec(
    payload_id="affliction:electrolaser-shock",
    kind="affliction",
    resistance_penalty=-4,
    armor_divisor=Decimal(2),
    condition="stun",
    requires_penetration=False,
)

ULTRATECH_WEAPONS = (
    _beam(
        "electrolaser-pistol",
        9,
        1800,
        1700,
        "pistol",
        1,
        -3,
        1,
        4,
        0,
        40,
        80,
        3,
        180,
        3,
        4,
        -2,
        "electrolaser-pistol-cell",
        surge=True,
        atmosphere=True,
        affliction=ELECTROLASER,
    ),
    _beam(
        "blaster-pistol",
        11,
        2200,
        1100,
        "pistol",
        3,
        0,
        5,
        5,
        0,
        300,
        900,
        3,
        200,
        3,
        4,
        -2,
        "blaster-pistol-cell",
        surge=True,
    ),
    _beam(
        "electrolaser-carbine",
        9,
        3900,
        2700,
        "rifle",
        1,
        -3,
        1,
        8,
        1,
        160,
        470,
        3,
        360,
        3,
        4,
        -4,
        "electrolaser-carbine-cell",
        surge=True,
        atmosphere=True,
        affliction=ELECTROLASER,
    ),
    _beam(
        "laser-sniper-rifle",
        9,
        20000,
        16000,
        "rifle",
        5,
        0,
        2,
        12,
        2,
        1100,
        3300,
        3,
        75,
        3,
        10,
        -8,
        "laser-sniper-rifle-cell",
    ),
    _beam(
        "laser-rifle",
        10,
        10000,
        8000,
        "rifle",
        5,
        0,
        2,
        12,
        2,
        700,
        2100,
        10,
        150,
        3,
        7,
        -4,
        "laser-rifle-cell",
    ),
    _beam(
        "blaster-rifle",
        11,
        18000,
        9000,
        "rifle",
        6,
        0,
        5,
        10,
        2,
        700,
        2100,
        3,
        50,
        3,
        7,
        -4,
        "blaster-rifle-cell",
        surge=True,
    ),
    _beam(
        "heavy-blaster",
        11,
        23000,
        16000,
        "rifle",
        8,
        0,
        5,
        10,
        4,
        900,
        2700,
        3,
        90,
        5,
        10,
        -6,
        "heavy-blaster-cell",
        surge=True,
    ),
)

ULTRATECH_AMMUNITION = tuple(
    EquipmentProfile(
        definition_id="equipment:" + identifier,
        provenance=source(280),
        weight_millipounds=weight,
        price=price,
        technology_level=tl,
        ammunition=True,
        power_cell_capacity=shots,
    )
    for identifier, tl, weight, price, shots in (
        ("electrolaser-pistol-cell", 9, 500, 10, 180),
        ("blaster-pistol-cell", 11, 500, 10, 200),
        ("electrolaser-carbine-cell", 9, 1000, 20, 360),
        ("laser-sniper-rifle-cell", 9, 4000, 80, 75),
        ("laser-rifle-cell", 10, 2000, 40, 150),
        ("blaster-rifle-cell", 11, 1000, 20, 50),
        ("heavy-blaster-cell", 11, 4000, 80, 90),
    )
)

ULTRATECH_INDEX: tuple[EquipmentProfile, ...] = ()
