/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export type paths = Record<string, never>;
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    /** CatalogOption */
    CatalogOption: {
      /** Id */
      id: string;
      /** Name */
      name: string;
      kind: components["schemas"]["DefinitionKind"];
      status: components["schemas"]["ImplementationStatus"];
      /**
       * Point Cost
       * @default null
       */
      point_cost: number | null;
      /** @default null */
      skill: components["schemas"]["SkillSpec"] | null;
      /** @default null */
      trait: components["schemas"]["TraitRules"] | null;
    };
    /**
     * ControllingAttribute
     * @enum {string}
     */
    ControllingAttribute:
      | "attribute:st"
      | "attribute:dx"
      | "attribute:iq"
      | "attribute:ht"
      | "secondary:will"
      | "secondary:per";
    /**
     * DefinitionKind
     * @enum {string}
     */
    DefinitionKind: "attribute" | "secondary" | "skill" | "trait" | "equipment";
    /**
     * Difficulty
     * @enum {string}
     */
    Difficulty: "easy" | "average" | "hard" | "very-hard";
    /**
     * ImplementationStatus
     * @enum {string}
     */
    ImplementationStatus: "implemented" | "manual-adjudication" | "unsupported";
    /** ProfileOption */
    ProfileOption: {
      /** Id */
      id: string;
      /** Version */
      version: number;
      /** Title */
      title: string;
      /** Supported */
      supported: boolean;
      /** Blockers */
      blockers: string[];
    };
    /** SkillDefault */
    SkillDefault: {
      /** Target */
      target: string;
      /** Modifier */
      modifier: number;
    };
    /** SkillPrerequisite */
    SkillPrerequisite: {
      /** Target */
      target: string;
      /**
       * Minimum
       * @default 1
       */
      minimum: number;
    };
    /** SkillSpec */
    SkillSpec: {
      attribute: components["schemas"]["ControllingAttribute"];
      difficulty: components["schemas"]["Difficulty"];
      /** Reference */
      reference: string;
      /**
       * Defaults
       * @default []
       */
      defaults: components["schemas"]["SkillDefault"][];
      /**
       * Prerequisites
       * @default []
       */
      prerequisites: components["schemas"]["SkillPrerequisite"][];
      /** @default null */
      specialty: components["schemas"]["Specialty"] | null;
      /** @default null */
      technique: components["schemas"]["Technique"] | null;
    };
    /** Specialty */
    Specialty: {
      /** Family */
      family: string;
      /** Name */
      name: string;
      /**
       * Optional Parent
       * @default null
       */
      optional_parent: string | null;
    };
    /** Technique */
    Technique: {
      /** Parent */
      parent: string;
      /** Default Modifier */
      default_modifier: number;
      /**
       * Maximum Modifier
       * @default 0
       */
      maximum_modifier: number;
    };
    /** TraitModifier */
    TraitModifier: {
      /** Id */
      id: string;
      /** Percent */
      percent: number;
      /**
       * Exclusions
       * @default []
       */
      exclusions: string[];
      /**
       * Runtime Hook
       * @default null
       */
      runtime_hook: string | null;
    };
    /** TraitParameter */
    TraitParameter: {
      /** Name */
      name: string;
      /**
       * Kind
       * @enum {string}
       */
      kind: "text" | "integer" | "boolean";
      /** Choices */
      choices: (string | number | boolean)[];
    };
    /** TraitRules */
    TraitRules: {
      /** Profile Id */
      profile_id: string;
      /**
       * Maximum Level
       * @default 1
       */
      maximum_level: number;
      /**
       * Self Control
       * @default false
       */
      self_control: boolean;
      /**
       * Parameters
       * @default []
       */
      parameters: components["schemas"]["TraitParameter"][];
      /**
       * Modifiers
       * @default []
       */
      modifiers: components["schemas"]["TraitModifier"][];
      /**
       * Runtime Hooks
       * @default []
       */
      runtime_hooks: string[];
    };
    /** WorkshopOptions */
    WorkshopOptions: {
      /** Active Profile */
      active_profile: string | null;
      /**
       * Active Profile Version
       * @default null
       */
      active_profile_version: number | null;
      /** Profiles */
      profiles: components["schemas"]["ProfileOption"][];
      /** Catalog */
      catalog: components["schemas"]["CatalogOption"][];
      /** Build Revision */
      build_revision: string | null;
      /** Points Available */
      points_available: number;
      /** Can Approve */
      can_approve: boolean;
      /**
       * Can Edit
       * @default true
       */
      can_edit: boolean;
    };
    /** CharacterDraft */
    CharacterDraft: {
      /** Name */
      name: string;
      /**
       * Backstory
       * @default
       */
      backstory: string;
      /**
       * Purchases
       * @default []
       */
      purchases: components["schemas"]["Purchase"][];
    };
    /** CharacterProposal */
    CharacterProposal: {
      draft: components["schemas"]["CharacterDraft"];
      /**
       * Custom
       * @default []
       */
      custom: components["schemas"]["CustomConstruction"][];
    };
    /**
     * CustomConstruction
     * @description A named grouping of purchased catalog components, never new mechanics.
     */
    CustomConstruction: {
      /** Id */
      id: string;
      /** Components */
      components: string[];
    };
    /** Purchase */
    Purchase: {
      /** Definition Id */
      definition_id: string;
      /**
       * Amount
       * @default 1
       */
      amount: number;
      /** @default null */
      trait: components["schemas"]["TraitOptions"] | null;
    };
    /** TraitOptions */
    TraitOptions: {
      /**
       * Parameters
       * @default []
       */
      parameters: [string, string | number | boolean][];
      /**
       * Self Control
       * @default null
       */
      self_control: (6 | 9 | 12 | 15) | null;
      /**
       * Modifiers
       * @default []
       */
      modifiers: string[];
    };
    /** CharacterPreviewRequest */
    CharacterPreviewRequest: {
      proposal: components["schemas"]["CharacterProposal"];
    };
    /** PurchaseCost */
    PurchaseCost: {
      /** Definition Id */
      definition_id: string;
      /** Amount */
      amount: number;
      /** Cost */
      cost: number;
    };
    /** CharacterPreviewResult */
    CharacterPreviewResult: {
      /** Catalog */
      catalog: components["schemas"]["CatalogOption"][];
      /** Spent */
      spent: number;
      /** Remaining */
      remaining: number;
      /** Legal */
      legal: boolean;
      /** Diagnostics */
      diagnostics: string[];
      /** Derived */
      derived: [string, string][];
      /**
       * Breakdown
       * @default []
       */
      breakdown: components["schemas"]["PurchaseCost"][];
    };
    /** ProfilePreviewRequest */
    ProfilePreviewRequest: {
      /** Profile Id */
      profile_id: string;
      /** Version */
      version: number;
      proposal: components["schemas"]["CharacterProposal"];
    };
    /** ProfilePreviewResult */
    ProfilePreviewResult: {
      /** Catalog */
      catalog: components["schemas"]["CatalogOption"][];
      /** Spent */
      spent: number;
      /** Remaining */
      remaining: number;
      /** Legal */
      legal: boolean;
      /** Diagnostics */
      diagnostics: string[];
      /** Derived */
      derived: [string, string][];
      /**
       * Breakdown
       * @default []
       */
      breakdown: components["schemas"]["PurchaseCost"][];
      profile: components["schemas"]["ProfileOption"];
    };
    /** AdvanceCharacter */
    AdvanceCharacter: {
      /** Id */
      id: string;
      /** Actor Id */
      actor_id: string;
      /** Expected Revision */
      expected_revision: number;
      /** Expected Build Revision */
      expected_build_revision: string;
      draft: components["schemas"]["CharacterDraft"];
      /** Reason */
      reason: string;
    };
    /** DraftCommand */
    DraftCommand: {
      /** Id */
      id: string;
      /** Draft Id */
      draft_id: string;
      /** Actor Id */
      actor_id: string;
      /** Expected Revision */
      expected_revision: number;
      /** Expected Draft Revision */
      expected_draft_revision: number;
      /**
       * Operation
       * @default save
       * @enum {string}
       */
      operation: "save" | "submit" | "approve" | "activate";
      /**
       * Kind
       * @default character
       * @enum {string}
       */
      kind: "character" | "scenario";
      /**
       * Content Json
       * @default null
       */
      content_json: string | null;
      /**
       * Reason
       * @default
       */
      reason: string;
    };
    /** ReviewActor */
    ReviewActor: {
      /** Actor Id */
      actor_id: string;
      /** Name */
      name: string;
    };
    /** ReviewSubmission */
    ReviewSubmission: {
      /** Draft Id */
      draft_id: string;
      /** Actor Id */
      actor_id: string;
      /** Owner Id */
      owner_id: string;
      /** Name */
      name: string;
      /** Draft Revision */
      draft_revision: number;
      /** Approved */
      approved: boolean;
    };
    /** WorkshopReviewQueue */
    WorkshopReviewQueue: {
      /** Revision */
      revision: number;
      /** Submissions */
      submissions: components["schemas"]["ReviewSubmission"][];
      /** Actors */
      actors: components["schemas"]["ReviewActor"][];
    };
    /** GrantPoints */
    GrantPoints: {
      /** Id */
      id: string;
      /** Actor Id */
      actor_id: string;
      /** Target Actor Id */
      target_actor_id: string;
      /** Expected Revision */
      expected_revision: number;
      /** Points */
      points: number;
      /** Reason */
      reason: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
