"""Audited numeric equipment selection; no rulebook prose or automatic activation.

Characters third printing (February 2008), B271-274, B283, B288-289. These are
explicit review data for the selected later-printing profile.
"""

from decimal import Decimal
from fractions import Fraction
from typing import Literal, cast

from pydantic import Field

from wayfarer.errors import ValidationError
from wayfarer.models import Id, Record
from wayfarer.rules.firearm_types import FirearmSpec
from wayfarer.rules.object_types import ObjectProfile
from wayfarer.rules.readiness_types import ProjectileReadiness
from wayfarer.simulation.gurps_equipment import (
    Armor,
    Damage,
    DamageType,
    EquipmentCatalog,
    EquipmentProfile,
    Location,
    MeleeMode,
    MultipleProjectiles,
    Parry,
    Provenance,
    RangedMode,
    RatedStrength,
    RocketAcceleration,
    Shield,
    SmartgunSpec,
    TechnologyLevel,
)
from wayfarer.simulation.objects import object_hp


def source(page: int | tuple[int, ...]) -> Provenance:
    return Provenance(
        source_id="sjg:basic-set-characters-4e-2004",
        edition="Fourth Edition, third printing (2008)",
        pages=(page,) if isinstance(page, int) else page,
        errata="Third-printing text; no separate errata overlay selected",
    )


def solid(weight: int, dr: int) -> ObjectProfile:
    return ObjectProfile(
        construction="homogenous", hp=object_hp(weight, "homogenous"), dr=dr, ht=12
    )


def melee(
    identifier: str,
    skill: str,
    minimum_st: int,
    basis: Literal["thrust", "swing", "fixed"],
    adds: int,
    damage_type: DamageType,
    reach: tuple[int, ...],
    *,
    hands: Literal[1, 2] = 1,
    parry: int | None = 0,
    unbalanced: bool = False,
    fencing: bool = False,
    divisor: str = "1",
    dice: int | None = None,
    ready_after_attack: bool = False,
) -> MeleeMode:
    """Construct one independently transcribed melee-table mode."""
    return MeleeMode(
        id=identifier,
        skill_id="skill:" + skill,
        minimum_st=minimum_st,
        hands=hands,
        damage=Damage(
            basis=basis,
            dice=dice,
            adds=adds,
            damage_type=damage_type,
            armor_divisor=Decimal(divisor),
        ),
        reach=reach,
        parry=(
            None if parry is None else Parry(modifier=parry, unbalanced=unbalanced, fencing=fencing)
        ),
        ready_after_attack=ready_after_attack,
    )


def weapon(
    identifier: str,
    page: int | tuple[int, ...],
    tl: TechnologyLevel,
    price: int,
    weight: int,
    *modes: MeleeMode,
    unsupported: tuple[str, ...] = (),
    durability_dr: int | None = None,
) -> EquipmentProfile:
    """Construct one physical row, merging alternate skill rows into its mode list."""
    return EquipmentProfile(
        definition_id="equipment:" + identifier,
        provenance=source(page),
        weight_millipounds=weight,
        price=price,
        technology_level=tl,
        slot="hand",
        durability=None if durability_dr is None else solid(weight, durability_dr),
        modes=modes,
        unsupported_mechanics=unsupported,
    )


def ranged(
    identifier: str,
    skill: str,
    minimum_st: int,
    basis: Literal["thrust", "swing", "fixed"],
    adds: int,
    damage_type: DamageType,
    accuracy: int,
    half_range: Decimal | int | None,
    maximum_range: Decimal | int,
    bulk: int,
    ammunition_id: str,
    *,
    dice: int | None = None,
    hands: Literal[1, 2] = 2,
    reload_seconds: int = 2,
    rated_kind: Literal["bow", "crossbow"] | None = None,
) -> RangedMode:
    """Construct one B275-276 muscle-powered launcher mode."""
    return RangedMode(
        id=identifier,
        skill_id="skill:" + skill,
        minimum_st=minimum_st,
        hands=hands,
        damage=Damage(
            basis=basis,
            dice=dice,
            adds=adds,
            damage_type=damage_type,
        ),
        accuracy=accuracy,
        range_basis="st",
        half_damage_range=half_range,
        maximum_range=maximum_range,
        shots=1,
        reload_seconds=reload_seconds,
        bulk=bulk,
        ammunition_id="equipment:" + ammunition_id,
        rated_strength=(
            None if rated_kind is None else RatedStrength(kind=rated_kind, st=minimum_st)
        ),
        readiness=(
            None
            if rated_kind is None
            else ProjectileReadiness(
                kind=rated_kind,
                fast_draw_skill_id="skill:fast-draw-arrow",
                fast_draw_specialty="Arrow",
            )
        ),
    )


def ranged_weapon(
    identifier: str,
    page: int,
    tl: int,
    price: Decimal | int,
    weight: int,
    *modes: RangedMode,
    unsupported: tuple[str, ...] = (),
) -> EquipmentProfile:
    return EquipmentProfile(
        definition_id="equipment:" + identifier,
        provenance=source(page),
        weight_millipounds=weight,
        price=price,
        technology_level=tl,
        slot="hand",
        modes=modes,
        unsupported_mechanics=unsupported,
    )


def firearm(
    identifier: str,
    skill: str,
    tl: int,
    damage_dice: int,
    damage_adds: int,
    damage_type: DamageType,
    accuracy: int,
    half_range: int,
    maximum_range: int,
    rate_of_fire: int,
    shots: int,
    reload_seconds: int,
    minimum_st: int,
    bulk: int,
    recoil: int,
    ammunition_id: str,
    action: Literal["muzzleloader", "breechloader", "revolver", "repeating"],
    *,
    hands: Literal[1, 2] = 1,
    reload_protocol: Literal["magazine", "per-round"] = "magazine",
    chamber_capacity: int = 0,
    projectiles_per_shot: int | None = None,
    minimum_shots_per_attack: int = 1,
) -> RangedMode:
    """Construct one independently transcribed B278-279 conventional-firearm row."""
    return RangedMode(
        id=identifier,
        skill_id="skill:guns-" + skill,
        minimum_st=minimum_st,
        hands=hands,
        damage=Damage(
            basis="fixed",
            dice=damage_dice,
            adds=damage_adds,
            damage_type=damage_type,
        ),
        accuracy=accuracy,
        range_basis="yards",
        half_damage_range=half_range,
        maximum_range=maximum_range,
        rate_of_fire=rate_of_fire,
        minimum_shots_per_attack=minimum_shots_per_attack,
        shots=shots,
        chamber_capacity=chamber_capacity,
        reload_seconds=reload_seconds,
        reload_protocol=reload_protocol,
        bulk=bulk,
        recoil=recoil,
        ammunition_id="equipment:" + ammunition_id,
        firearm=FirearmSpec(
            technology_level=tl,
            action=action,
            armoury_skill_id="skill:armoury-small-arms",
        ),
        multiple_projectiles=(
            None
            if projectiles_per_shot is None
            else MultipleProjectiles(projectiles_per_shot=projectiles_per_shot)
        ),
    )


# B271-274. Natural attacks and table rows without physical item cost/weight are
# accounted for in the ledger rather than invented as equipment. Superscience,
# variable-ST and extra-die rows remain explicit omissions until the typed schema
# can represent their values exactly.
WEAPONS = (
    weapon(
        "light-club",
        271,
        0,
        5,
        3000,
        melee("swing", "broadsword", 10, "swing", 1, "cr", (1,)),
        melee("thrust", "broadsword", 10, "thrust", 1, "cr", (1,)),
        durability_dr=2,
    ),
    weapon(
        "broadsword",
        271,
        2,
        500,
        3000,
        melee("swing", "broadsword", 10, "swing", 1, "cut", (1,)),
        melee("thrust", "broadsword", 10, "thrust", 1, "cr", (1,)),
        durability_dr=6,
    ),
    weapon(
        "axe",
        271,
        0,
        50,
        4000,
        melee("axe-mace-swing", "axe-mace", 11, "swing", 2, "cut", (1,), unbalanced=True),
    ),
    weapon(
        "hatchet",
        271,
        0,
        40,
        2000,
        melee("axe-mace-swing", "axe-mace", 8, "swing", 0, "cut", (1,)),
        unsupported=("alternate-thrown-mode",),
    ),
    weapon(
        "throwing-axe",
        271,
        0,
        60,
        4000,
        melee("axe-mace-swing", "axe-mace", 11, "swing", 2, "cut", (1,), unbalanced=True),
        unsupported=("alternate-thrown-mode",),
    ),
    weapon(
        "mace",
        271,
        2,
        50,
        5000,
        melee("axe-mace-swing", "axe-mace", 12, "swing", 3, "cr", (1,), unbalanced=True),
        unsupported=("alternate-thrown-mode",),
    ),
    weapon(
        "small-mace",
        271,
        2,
        35,
        3000,
        melee("axe-mace-swing", "axe-mace", 10, "swing", 2, "cr", (1,), unbalanced=True),
        unsupported=("alternate-thrown-mode",),
    ),
    weapon(
        "pick",
        271,
        3,
        70,
        3000,
        melee("axe-mace-swing", "axe-mace", 10, "swing", 1, "imp", (1,), unbalanced=True),
        unsupported=("pick-stuck",),
    ),
    weapon(
        "blackjack",
        271,
        1,
        20,
        1000,
        melee("brawling-thrust", "brawling", 7, "thrust", 0, "cr", (0,)),
    ),
    weapon(
        "thrusting-broadsword",
        271,
        2,
        600,
        3000,
        melee("broadsword-swing", "broadsword", 10, "swing", 1, "cut", (1,)),
        melee("broadsword-thrust", "broadsword", 10, "thrust", 2, "imp", (1,)),
    ),
    weapon(
        "bastard-sword",
        (271, 274),
        3,
        650,
        5000,
        melee("broadsword-swing", "broadsword", 11, "swing", 1, "cut", (1, 2), unbalanced=True),
        melee("broadsword-thrust", "broadsword", 11, "thrust", 1, "cr", (2,), unbalanced=True),
        melee("two-handed-sword-swing", "two-handed-sword", 10, "swing", 2, "cut", (1, 2), hands=2),
        melee("two-handed-sword-thrust", "two-handed-sword", 10, "thrust", 2, "cr", (2,), hands=2),
    ),
    weapon(
        "katana",
        (271, 274),
        3,
        650,
        5000,
        melee("broadsword-swing", "broadsword", 11, "swing", 1, "cut", (1, 2)),
        melee("broadsword-thrust", "broadsword", 11, "thrust", 1, "imp", (1,)),
        melee("two-handed-sword-swing", "two-handed-sword", 10, "swing", 2, "cut", (1, 2), hands=2),
        melee("two-handed-sword-thrust", "two-handed-sword", 10, "thrust", 1, "imp", (1,), hands=2),
    ),
    weapon(
        "thrusting-bastard-sword",
        (271, 274),
        3,
        750,
        5000,
        melee("broadsword-swing", "broadsword", 11, "swing", 1, "cut", (1, 2), unbalanced=True),
        melee("broadsword-thrust", "broadsword", 11, "thrust", 2, "imp", (2,), unbalanced=True),
        melee("two-handed-sword-swing", "two-handed-sword", 10, "swing", 2, "cut", (1, 2), hands=2),
        melee("two-handed-sword-thrust", "two-handed-sword", 10, "thrust", 3, "imp", (2,), hands=2),
    ),
    weapon(
        "cavalry-saber",
        271,
        4,
        500,
        3000,
        melee("broadsword-swing", "broadsword", 10, "swing", 1, "cut", (1,)),
        melee("broadsword-thrust", "broadsword", 10, "thrust", 1, "imp", (1,)),
    ),
    weapon(
        "morningstar",
        272,
        3,
        80,
        6000,
        melee("flail-swing", "flail", 12, "swing", 3, "cr", (1,), unbalanced=True),
        unsupported=("flail-defense-penalties",),
    ),
    weapon(
        "nunchaku",
        272,
        3,
        20,
        2000,
        melee("flail-swing", "flail", 7, "swing", 1, "cr", (1,), unbalanced=True),
        unsupported=("flail-defense-penalties",),
    ),
    weapon(
        "large-knife",
        272,
        0,
        40,
        1000,
        melee("knife-swing", "knife", 6, "swing", -2, "cut", (0, 1), parry=-1),
        melee("knife-thrust", "knife", 6, "thrust", 0, "imp", (0,), parry=-1),
        unsupported=("alternate-thrown-mode",),
    ),
    weapon(
        "small-knife",
        272,
        0,
        30,
        500,
        melee("knife-swing", "knife", 5, "swing", -3, "cut", (0, 1), parry=-1),
        melee("knife-thrust", "knife", 5, "thrust", -1, "imp", (0,), parry=-1),
        unsupported=("alternate-thrown-mode",),
    ),
    weapon(
        "wooden-stake",
        272,
        0,
        4,
        500,
        melee("knife-thrust", "knife", 5, "thrust", 0, "imp", (0,), parry=-1, divisor="0.5"),
        unsupported=("alternate-thrown-mode",),
    ),
    weapon(
        "dagger",
        272,
        1,
        20,
        250,
        melee("knife-thrust", "knife", 5, "thrust", -1, "imp", (0,), parry=-1),
        unsupported=("alternate-thrown-mode",),
    ),
    weapon(
        "kusari",
        272,
        3,
        70,
        5000,
        melee(
            "kusari-swing", "kusari", 11, "swing", 2, "cr", (1, 2, 3, 4), parry=-2, unbalanced=True
        ),
        unsupported=("flail-defense-penalties", "variable-reach-ready"),
    ),
    weapon(
        "lance",
        272,
        2,
        60,
        6000,
        melee("lance-thrust", "lance", 12, "thrust", 3, "imp", (4,), parry=None),
        unsupported=("mounted-lance-damage",),
    ),
    weapon(
        "glaive",
        272,
        1,
        100,
        8000,
        melee(
            "polearm-swing",
            "polearm",
            11,
            "swing",
            3,
            "cut",
            (2, 3),
            hands=2,
            unbalanced=True,
            ready_after_attack=True,
        ),
        melee(
            "polearm-thrust", "polearm", 11, "thrust", 3, "imp", (1, 2, 3), hands=2, unbalanced=True
        ),
        unsupported=("conditional-ready-after-attack", "variable-reach-ready"),
    ),
    weapon(
        "naginata",
        (272, 273, 274),
        2,
        100,
        6000,
        melee("polearm-swing", "polearm", 9, "swing", 2, "cut", (1, 2), hands=2, unbalanced=True),
        melee("polearm-thrust", "polearm", 9, "thrust", 3, "imp", (2,), hands=2),
        melee("staff-swing", "staff", 9, "swing", 2, "cr", (1, 2), hands=2, unbalanced=True),
        melee("staff-thrust", "staff", 9, "thrust", 2, "cr", (1, 2), hands=2),
        melee(
            "two-handed-sword-swing",
            "two-handed-sword",
            9,
            "swing",
            3,
            "cut",
            (2,),
            hands=2,
            unbalanced=True,
        ),
        melee("two-handed-sword-thrust", "two-handed-sword", 9, "thrust", 3, "imp", (2,), hands=2),
        unsupported=("variable-reach-ready",),
    ),
    weapon(
        "halberd",
        272,
        3,
        150,
        12000,
        melee(
            "polearm-cut",
            "polearm",
            13,
            "swing",
            5,
            "cut",
            (2, 3),
            hands=2,
            unbalanced=True,
            ready_after_attack=True,
        ),
        melee(
            "polearm-pick",
            "polearm",
            13,
            "swing",
            4,
            "imp",
            (2, 3),
            hands=2,
            unbalanced=True,
            ready_after_attack=True,
        ),
        melee(
            "polearm-thrust", "polearm", 12, "thrust", 3, "imp", (1, 2, 3), hands=2, unbalanced=True
        ),
        unsupported=("conditional-ready-after-attack", "pick-stuck", "variable-reach-ready"),
    ),
    weapon(
        "poleaxe",
        272,
        3,
        120,
        10000,
        melee(
            "polearm-cut",
            "polearm",
            12,
            "swing",
            4,
            "cut",
            (2, 3),
            hands=2,
            unbalanced=True,
            ready_after_attack=True,
        ),
        melee(
            "polearm-crush",
            "polearm",
            12,
            "swing",
            4,
            "cr",
            (2, 3),
            hands=2,
            unbalanced=True,
            ready_after_attack=True,
        ),
        unsupported=("conditional-ready-after-attack", "variable-reach-ready"),
    ),
    weapon(
        "rapier",
        273,
        4,
        500,
        2750,
        melee("rapier-thrust", "rapier", 9, "thrust", 1, "imp", (1, 2), fencing=True),
    ),
    weapon(
        "saber",
        273,
        4,
        700,
        2000,
        melee("saber-swing", "saber", 8, "swing", -1, "cut", (1,), fencing=True),
        melee("saber-thrust", "saber", 8, "thrust", 1, "imp", (1,), fencing=True),
    ),
    weapon(
        "baton",
        273,
        0,
        20,
        1000,
        melee("shortsword-swing", "shortsword", 6, "swing", 0, "cr", (1,)),
        melee("shortsword-thrust", "shortsword", 6, "thrust", 0, "cr", (1,)),
    ),
    weapon(
        "shortsword",
        273,
        2,
        400,
        2000,
        melee("shortsword-swing", "shortsword", 8, "swing", 0, "cut", (1,)),
        melee("shortsword-thrust", "shortsword", 8, "thrust", 0, "imp", (1,)),
    ),
    weapon(
        "cutlass",
        273,
        4,
        300,
        2000,
        melee("shortsword-swing", "shortsword", 8, "swing", 0, "cut", (1,)),
        melee("shortsword-thrust", "shortsword", 8, "thrust", 0, "imp", (1,)),
        unsupported=("cutlass-hilt",),
    ),
    weapon(
        "cattle-prod",
        273,
        7,
        50,
        2000,
        melee("shortsword-burn", "shortsword", 3, "fixed", -3, "burn", (1,), dice=1),
        unsupported=("linked-affliction",),
    ),
    weapon(
        "short-staff",
        273,
        0,
        20,
        1000,
        melee("smallsword-swing", "smallsword", 6, "swing", 0, "cr", (1,), fencing=True),
        melee("smallsword-thrust", "smallsword", 6, "thrust", 0, "cr", (1,), fencing=True),
    ),
    weapon(
        "smallsword",
        273,
        4,
        400,
        1500,
        melee("smallsword-thrust", "smallsword", 5, "thrust", 1, "imp", (1,), fencing=True),
    ),
    weapon(
        "spear",
        273,
        0,
        40,
        4000,
        melee("spear-one-hand", "spear", 9, "thrust", 2, "imp", (1,), hands=1),
        melee("spear-two-hands", "spear", 9, "thrust", 3, "imp", (1, 2), hands=2),
        unsupported=("alternate-thrown-mode", "variable-reach-ready"),
    ),
    weapon(
        "javelin",
        273,
        1,
        30,
        2000,
        melee("spear-thrust", "spear", 6, "thrust", 1, "imp", (1,)),
        unsupported=("alternate-thrown-mode",),
    ),
    weapon(
        "long-spear",
        273,
        2,
        60,
        5000,
        melee("spear-one-hand", "spear", 10, "thrust", 2, "imp", (2, 3), hands=1, unbalanced=True),
        melee("spear-two-hands", "spear", 10, "thrust", 3, "imp", (2, 3), hands=2),
        unsupported=("variable-reach-ready",),
    ),
    weapon(
        "quarterstaff",
        (273, 274),
        0,
        10,
        4000,
        melee("staff-swing", "staff", 7, "swing", 2, "cr", (1, 2), hands=2, parry=2),
        melee("staff-thrust", "staff", 7, "thrust", 2, "cr", (1, 2), hands=2, parry=2),
        melee("two-handed-sword-swing", "two-handed-sword", 9, "swing", 2, "cr", (1, 2), hands=2),
        melee("two-handed-sword-thrust", "two-handed-sword", 9, "thrust", 1, "cr", (2,), hands=2),
    ),
    weapon(
        "maul",
        274,
        0,
        80,
        12000,
        melee(
            "two-handed-axe-mace-swing",
            "two-handed-axe-mace",
            13,
            "swing",
            4,
            "cr",
            (1, 2),
            hands=2,
            unbalanced=True,
            ready_after_attack=True,
        ),
        unsupported=("conditional-ready-after-attack", "variable-reach-ready"),
    ),
    weapon(
        "great-axe",
        274,
        1,
        100,
        8000,
        melee(
            "two-handed-axe-mace-swing",
            "two-handed-axe-mace",
            12,
            "swing",
            3,
            "cut",
            (1, 2),
            hands=2,
            unbalanced=True,
            ready_after_attack=True,
        ),
        unsupported=("conditional-ready-after-attack", "variable-reach-ready"),
    ),
    weapon(
        "scythe",
        274,
        1,
        15,
        5000,
        melee(
            "two-handed-axe-mace-cut",
            "two-handed-axe-mace",
            11,
            "swing",
            2,
            "cut",
            (1,),
            hands=2,
            unbalanced=True,
            ready_after_attack=True,
        ),
        melee(
            "two-handed-axe-mace-pick",
            "two-handed-axe-mace",
            11,
            "swing",
            0,
            "imp",
            (1,),
            hands=2,
            unbalanced=True,
            ready_after_attack=True,
        ),
        unsupported=("conditional-ready-after-attack", "pick-stuck"),
    ),
    weapon(
        "warhammer",
        274,
        3,
        100,
        7000,
        melee(
            "two-handed-axe-mace-swing",
            "two-handed-axe-mace",
            12,
            "swing",
            3,
            "imp",
            (1, 2),
            hands=2,
            unbalanced=True,
            ready_after_attack=True,
        ),
        unsupported=("conditional-ready-after-attack", "pick-stuck", "variable-reach-ready"),
    ),
    weapon(
        "flail",
        274,
        2,
        100,
        8000,
        melee(
            "two-handed-flail-swing",
            "two-handed-flail",
            13,
            "swing",
            4,
            "cr",
            (1, 2),
            hands=2,
            unbalanced=True,
        ),
        unsupported=("flail-defense-penalties", "variable-reach-ready"),
    ),
    weapon(
        "greatsword",
        274,
        3,
        800,
        7000,
        melee("two-handed-sword-swing", "two-handed-sword", 12, "swing", 3, "cut", (1, 2), hands=2),
        melee("two-handed-sword-thrust", "two-handed-sword", 12, "thrust", 2, "cr", (2,), hands=2),
    ),
    weapon(
        "thrusting-greatsword",
        274,
        3,
        900,
        7000,
        melee("two-handed-sword-swing", "two-handed-sword", 12, "swing", 3, "cut", (1, 2), hands=2),
        melee("two-handed-sword-thrust", "two-handed-sword", 12, "thrust", 3, "imp", (2,), hands=2),
    ),
)

# The selected table prints ``^`` instead of an integer TL for superscience.
# These rows retain their exact inventory facts but remain selection-blocked.
SUPERSCIENCE_MELEE = (
    weapon(
        "force-sword",
        272,
        "superscience",
        10000,
        2000,
        melee(
            "force-sword-swing",
            "force-sword",
            3,
            "fixed",
            0,
            "burn",
            (1, 2),
            dice=8,
            divisor="5",
        ),
        unsupported=("superscience-technology-level",),
    ),
    EquipmentProfile(
        definition_id="equipment:monowire-whip",
        provenance=source(272),
        technology_level="superscience",
        price=900,
        weight_millipounds=500,
        unsupported_mechanics=(
            "superscience-technology-level",
            "extra-die-strength-damage",
            "variable-reach-ready",
        ),
    ),
)

# B275-276. The table's slash-separated weights are split into the reusable
# launcher and one separately inventoried missile. Rows whose damage is
# ``spec.`` remain indexed and unavailable until their binding procedure can be
# stated without inventing a damage value.
MUSCLE_POWERED_RANGED = (
    ranged_weapon(
        "blowpipe",
        275,
        0,
        30,
        1000,
        ranged("shot", "blowpipe", 2, "fixed", -3, "pi-", 1, None, 4, -6, "blowpipe-dart", dice=1),
        unsupported=("follow-up-poison-or-drug",),
    ),
    ranged_weapon(
        "longbow",
        275,
        0,
        200,
        3000,
        ranged("shot", "bow", 11, "thrust", 2, "imp", 3, 15, 20, -8, "arrow", rated_kind="bow"),
    ),
    ranged_weapon(
        "regular-bow",
        275,
        0,
        100,
        2000,
        ranged("shot", "bow", 10, "thrust", 1, "imp", 2, 15, 20, -7, "arrow", rated_kind="bow"),
    ),
    ranged_weapon(
        "short-bow",
        275,
        0,
        50,
        2000,
        ranged("shot", "bow", 7, "thrust", 0, "imp", 1, 10, 15, -6, "arrow", rated_kind="bow"),
    ),
    ranged_weapon(
        "composite-bow",
        275,
        1,
        900,
        4000,
        ranged("shot", "bow", 10, "thrust", 3, "imp", 3, 20, 25, -7, "arrow", rated_kind="bow"),
    ),
    ranged_weapon(
        "crossbow",
        276,
        2,
        150,
        6000,
        ranged(
            "shot",
            "crossbow",
            7,
            "thrust",
            4,
            "imp",
            4,
            20,
            25,
            -6,
            "bolt",
            reload_seconds=4,
            rated_kind="crossbow",
        ),
    ),
    ranged_weapon(
        "pistol-crossbow",
        276,
        3,
        150,
        4000,
        ranged(
            "shot",
            "crossbow",
            7,
            "thrust",
            2,
            "imp",
            1,
            15,
            20,
            -4,
            "bolt",
            reload_seconds=4,
            rated_kind="crossbow",
        ),
        unsupported=("one-handed-rated-crossbow",),
    ),
    ranged_weapon(
        "prodd",
        276,
        3,
        150,
        6000,
        ranged(
            "shot",
            "crossbow",
            7,
            "thrust",
            4,
            "pi",
            2,
            20,
            25,
            -6,
            "lead-pellet",
            reload_seconds=4,
            rated_kind="crossbow",
        ),
    ),
    ranged_weapon(
        "sling",
        276,
        0,
        20,
        500,
        ranged("shot", "sling", 6, "swing", 0, "pi", 0, 6, 10, -4, "sling-stone"),
    ),
    ranged_weapon(
        "staff-sling",
        276,
        1,
        20,
        2000,
        ranged("shot", "sling", 7, "swing", 1, "pi", 1, 10, 15, -6, "sling-stone"),
    ),
    ranged_weapon("bolas", 275, 0, 20, 2000, unsupported=("entangling-special-damage",)),
    ranged_weapon("heavy-cloak", 275, 1, 50, 5000, unsupported=("entangling-special-damage",)),
    ranged_weapon("light-cloak", 275, 1, 20, 2000, unsupported=("entangling-special-damage",)),
    ranged_weapon("lariat", 276, 1, 40, 3000, unsupported=("entangling-special-damage",)),
    ranged_weapon("large-net", 276, 0, 40, 20000, unsupported=("entangling-special-damage",)),
    ranged_weapon("melee-net", 276, 2, 20, 5000, unsupported=("entangling-special-damage",)),
    ranged_weapon("atlatl", 276, 0, 20, 1000, unsupported=("launcher-assisted-throw",)),
    ranged_weapon("goats-foot", 276, 3, 50, 2000, unsupported=("crossbow-cocking-aid",)),
)

MUSCLE_POWERED_AMMUNITION = tuple(
    EquipmentProfile(
        definition_id="equipment:" + identifier,
        provenance=source(276),
        weight_millipounds=weight,
        price=price,
        technology_level=tl,
        ammunition=True,
    )
    for identifier, tl, price, weight in (
        ("blowpipe-dart", 0, Decimal("0.1"), 50),
        ("arrow", 0, 2, 100),
        ("bolt", 2, 2, 60),
        ("lead-pellet", 2, Decimal("0.1"), 60),
        ("sling-stone", 0, 0, 50),
    )
)

# B278: capacity preserves the printed chamber separately from the magazine;
# ammunition mass remains an exact rational number of millipounds.
FIREARMS = (
    ranged_weapon(
        "flintlock-pistol-51",
        278,
        4,
        200,
        3000,
        firearm(
            "shot",
            "pistol",
            4,
            2,
            -1,
            "pi+",
            1,
            75,
            450,
            1,
            1,
            20,
            10,
            -3,
            2,
            "flintlock-pistol-51-round",
            "muzzleloader",
        ),
    ),
    ranged_weapon(
        "wheel-lock-pistol-60",
        278,
        4,
        200,
        3250,
        firearm(
            "shot",
            "pistol",
            4,
            1,
            1,
            "pi+",
            1,
            75,
            400,
            1,
            1,
            20,
            10,
            -3,
            2,
            "wheel-lock-pistol-60-round",
            "muzzleloader",
        ),
    ),
    ranged_weapon(
        "derringer-41",
        278,
        5,
        100,
        400,
        firearm(
            "shot",
            "pistol",
            5,
            1,
            0,
            "pi+",
            1,
            80,
            650,
            1,
            2,
            3,
            9,
            -1,
            2,
            "derringer-41-round",
            "breechloader",
            reload_protocol="per-round",
        ),
    ),
    ranged_weapon(
        "revolver-36",
        278,
        5,
        150,
        2260,
        firearm(
            "shot",
            "pistol",
            5,
            2,
            -1,
            "pi",
            1,
            120,
            1300,
            1,
            6,
            3,
            10,
            -2,
            2,
            "revolver-36-round",
            "revolver",
            reload_protocol="per-round",
        ),
    ),
    ranged_weapon(
        "auto-pistol-45-tl6",
        278,
        6,
        300,
        2400,
        firearm(
            "shot",
            "pistol",
            6,
            2,
            0,
            "pi+",
            2,
            175,
            1700,
            3,
            8,
            3,
            10,
            -2,
            3,
            "auto-pistol-45-tl6-round",
            "repeating",
            chamber_capacity=1,
        ),
    ),
    ranged_weapon(
        "auto-pistol-9mm-tl6",
        278,
        6,
        350,
        2000,
        firearm(
            "shot",
            "pistol",
            6,
            2,
            2,
            "pi",
            2,
            150,
            1850,
            3,
            9,
            3,
            9,
            -2,
            2,
            "auto-pistol-9mm-tl6-round",
            "repeating",
            chamber_capacity=1,
        ),
    ),
    ranged_weapon(
        "snub-revolver-38",
        278,
        6,
        250,
        1300,
        firearm(
            "shot",
            "pistol",
            6,
            1,
            2,
            "pi",
            1,
            120,
            1250,
            3,
            5,
            3,
            8,
            -1,
            3,
            "snub-revolver-38-round",
            "revolver",
            reload_protocol="per-round",
        ),
    ),
    ranged_weapon(
        "handgonne-90",
        279,
        3,
        300,
        15000,
        firearm(
            "shot",
            "musket",
            3,
            2,
            0,
            "pi++",
            0,
            100,
            600,
            1,
            1,
            60,
            10,
            -6,
            4,
            "handgonne-90-round",
            "muzzleloader",
            hands=2,
        ),
        unsupported=("conditional-one-handed-firearm",),
    ),
    ranged_weapon(
        "flintlock-musket-75",
        279,
        4,
        200,
        13000,
        firearm(
            "shot",
            "musket",
            4,
            4,
            0,
            "pi++",
            2,
            100,
            1500,
            1,
            1,
            15,
            10,
            -6,
            4,
            "flintlock-musket-75-round",
            "muzzleloader",
            hands=2,
        ),
        unsupported=("conditional-one-handed-firearm",),
    ),
    ranged_weapon(
        "rifle-musket-577",
        279,
        5,
        150,
        8500,
        firearm(
            "shot",
            "rifle",
            5,
            4,
            0,
            "pi+",
            4,
            700,
            2100,
            1,
            1,
            15,
            10,
            -6,
            3,
            "rifle-musket-577-round",
            "muzzleloader",
            hands=2,
        ),
        unsupported=("conditional-one-handed-firearm",),
    ),
    ranged_weapon(
        "cartridge-rifle-45",
        279,
        5,
        200,
        6000,
        firearm(
            "shot",
            "rifle",
            5,
            5,
            0,
            "pi+",
            3,
            600,
            2000,
            1,
            1,
            4,
            10,
            -6,
            3,
            "cartridge-rifle-45-round",
            "breechloader",
            hands=2,
        ),
        unsupported=("conditional-one-handed-firearm",),
    ),
    ranged_weapon(
        "blunderbuss-8g",
        279,
        4,
        150,
        12000,
        firearm(
            "shot",
            "shotgun",
            4,
            1,
            0,
            "pi",
            1,
            15,
            100,
            1,
            1,
            15,
            11,
            -5,
            1,
            "blunderbuss-8g-round",
            "muzzleloader",
            hands=2,
            projectiles_per_shot=9,
        ),
    ),
    ranged_weapon(
        "double-shotgun-10g",
        279,
        5,
        450,
        9900,
        firearm(
            "shot",
            "shotgun",
            5,
            1,
            2,
            "pi",
            3,
            50,
            125,
            2,
            2,
            3,
            11,
            -5,
            1,
            "double-shotgun-10g-round",
            "breechloader",
            hands=2,
            reload_protocol="per-round",
            projectiles_per_shot=9,
        ),
    ),
    ranged_weapon(
        "pump-shotgun-12g",
        279,
        6,
        240,
        7300,
        firearm(
            "shot",
            "shotgun",
            6,
            1,
            1,
            "pi",
            3,
            50,
            125,
            2,
            5,
            3,
            10,
            -5,
            1,
            "pump-shotgun-12g-round",
            "repeating",
            hands=2,
            reload_protocol="per-round",
            projectiles_per_shot=9,
        ),
    ),
    ranged_weapon(
        "auto-shotgun-12g",
        279,
        7,
        950,
        7550,
        firearm(
            "shot",
            "shotgun",
            7,
            1,
            1,
            "pi",
            3,
            50,
            125,
            3,
            7,
            3,
            10,
            -5,
            1,
            "auto-shotgun-12g-round",
            "repeating",
            hands=2,
            chamber_capacity=1,
            reload_protocol="per-round",
            projectiles_per_shot=9,
        ),
    ),
    ranged_weapon(
        "smg-9mm-tl6",
        278,
        6,
        700,
        9000,
        firearm(
            "shot",
            "smg",
            6,
            3,
            -1,
            "pi",
            3,
            160,
            1900,
            8,
            32,
            3,
            10,
            -4,
            2,
            "smg-9mm-tl6-round",
            "repeating",
            hands=2,
            minimum_shots_per_attack=2,
        ),
        unsupported=("conditional-one-handed-firearm",),
    ),
)

# Remaining ordinary B278 handguns and the one one-handed machine-pistol row.
# Rows with smartgun, rocket-acceleration, full-auto-only, or two-hand notation
# stay outside this tuple until those mechanics are represented.
ORDINARY_HANDGUNS = tuple(
    ranged_weapon(
        identifier,
        278,
        tl,
        price,
        unloaded_weight,
        firearm(
            "shot",
            skill,
            tl,
            dice,
            adds,
            cast(DamageType, damage_type),
            accuracy,
            half_range,
            maximum_range,
            rate_of_fire,
            shots,
            reload_seconds,
            minimum_st,
            bulk,
            recoil,
            ammunition_id,
            cast(Literal["muzzleloader", "breechloader", "revolver", "repeating"], action),
            reload_protocol=cast(Literal["magazine", "per-round"], reload_protocol),
            chamber_capacity=chamber_capacity,
        ),
    )
    for (
        identifier,
        skill,
        tl,
        price,
        unloaded_weight,
        dice,
        adds,
        damage_type,
        accuracy,
        half_range,
        maximum_range,
        rate_of_fire,
        shots,
        chamber_capacity,
        reload_seconds,
        reload_protocol,
        minimum_st,
        bulk,
        recoil,
        ammunition_id,
        action,
    ) in (
        (
            "revolver-38",
            "pistol",
            6,
            400,
            1800,
            2,
            -1,
            "pi",
            2,
            120,
            1500,
            3,
            6,
            0,
            3,
            "per-round",
            8,
            -2,
            2,
            "revolver-38-round",
            "revolver",
        ),
        (
            "auto-pistol-9mm-tl7",
            "pistol",
            7,
            600,
            2000,
            2,
            2,
            "pi",
            2,
            150,
            1850,
            3,
            15,
            1,
            3,
            "magazine",
            9,
            -2,
            2,
            "auto-pistol-9mm-tl7-round",
            "repeating",
        ),
        (
            "holdout-pistol-380",
            "pistol",
            7,
            300,
            1100,
            2,
            0,
            "pi",
            1,
            125,
            1500,
            3,
            5,
            1,
            3,
            "magazine",
            8,
            -1,
            3,
            "holdout-pistol-380-round",
            "repeating",
        ),
        (
            "revolver-357m",
            "pistol",
            7,
            500,
            2790,
            3,
            -1,
            "pi",
            2,
            185,
            2000,
            3,
            6,
            0,
            3,
            "per-round",
            10,
            -2,
            3,
            "revolver-357m-round",
            "revolver",
        ),
        (
            "revolver-44m",
            "pistol",
            7,
            900,
            2950,
            3,
            0,
            "pi+",
            2,
            200,
            2500,
            3,
            6,
            0,
            3,
            "per-round",
            11,
            -3,
            4,
            "revolver-44m-round",
            "revolver",
        ),
        (
            "auto-pistol-44m",
            "pistol",
            8,
            750,
            3900,
            3,
            0,
            "pi+",
            2,
            230,
            2500,
            3,
            9,
            1,
            3,
            "magazine",
            12,
            -3,
            4,
            "auto-pistol-44m-round",
            "repeating",
        ),
        (
            "auto-pistol-40",
            "pistol",
            8,
            640,
            1400,
            2,
            0,
            "pi+",
            2,
            150,
            1900,
            3,
            15,
            1,
            3,
            "magazine",
            9,
            -2,
            2,
            "auto-pistol-40-round",
            "repeating",
        ),
        (
            "machine-pistol-9mm",
            "smg",
            7,
            900,
            4400,
            2,
            2,
            "pi",
            2,
            160,
            1900,
            20,
            25,
            1,
            3,
            "magazine",
            12,
            -3,
            3,
            "machine-pistol-9mm-round",
            "repeating",
        ),
    )
)

# B278 two-handed SMG/PDW rows without full-auto-only, smartgun, or Gauss
# notation. Their ordinary modes are exact; the dagger-marked one-hand ST
# exception remains the same explicit blocker as the B279 long guns.
ORDINARY_SMGS = tuple(
    ranged_weapon(
        identifier,
        278,
        tl,
        price,
        unloaded_weight,
        firearm(
            "shot",
            "smg",
            tl,
            dice,
            adds,
            cast(DamageType, damage_type),
            accuracy,
            half_range,
            maximum_range,
            rate_of_fire,
            shots,
            reload_seconds,
            minimum_st,
            bulk,
            recoil,
            ammunition_id,
            "repeating",
            chamber_capacity=1,
            hands=2,
        ),
        unsupported=("conditional-one-handed-firearm",),
    )
    for (
        identifier,
        tl,
        price,
        unloaded_weight,
        dice,
        adds,
        damage_type,
        accuracy,
        half_range,
        maximum_range,
        rate_of_fire,
        shots,
        reload_seconds,
        minimum_st,
        bulk,
        recoil,
        ammunition_id,
    ) in (
        (
            "smg-45",
            6,
            2200,
            10800,
            2,
            1,
            "pi+",
            3,
            190,
            1750,
            13,
            50,
            5,
            11,
            -4,
            3,
            "smg-45-round",
        ),
        (
            "smg-9mm-tl7",
            7,
            1200,
            6300,
            3,
            -1,
            "pi",
            4,
            160,
            1900,
            13,
            30,
            3,
            10,
            -4,
            2,
            "smg-9mm-tl7-round",
        ),
        (
            "pdw-46",
            8,
            800,
            3400,
            4,
            1,
            "pi-",
            3,
            200,
            2000,
            15,
            20,
            3,
            7,
            -3,
            2,
            "pdw-46-round",
        ),
    )
)

# B279 ordinary repeating rifles without R/B annotations or exotic footnotes.
# Loaded table weight is split into the physical weapon plus one exact reload;
# +1 chamber capacity stays distinct from magazine capacity.
REPEATING_RIFLES = tuple(
    ranged_weapon(
        identifier,
        279,
        tl,
        price,
        unloaded_weight,
        firearm(
            "shot",
            "rifle",
            tl,
            dice,
            adds,
            cast(DamageType, damage_type),
            accuracy,
            half_range,
            maximum_range,
            rate_of_fire,
            shots,
            reload_seconds,
            minimum_st,
            bulk,
            recoil,
            ammunition_id,
            "repeating",
            reload_protocol=cast(Literal["magazine", "per-round"], reload_protocol),
            chamber_capacity=chamber_capacity,
            hands=2,
        ),
        unsupported=("conditional-one-handed-firearm",),
    )
    for (
        identifier,
        tl,
        price,
        unloaded_weight,
        dice,
        adds,
        damage_type,
        accuracy,
        half_range,
        maximum_range,
        rate_of_fire,
        shots,
        chamber_capacity,
        reload_seconds,
        reload_protocol,
        minimum_st,
        bulk,
        recoil,
        ammunition_id,
    ) in (
        (
            "lever-action-carbine-30",
            5,
            300,
            6700,
            5,
            0,
            "pi",
            4,
            450,
            3000,
            1,
            6,
            1,
            3,
            "per-round",
            10,
            -4,
            2,
            "lever-action-carbine-30-round",
        ),
        (
            "bolt-action-rifle-762",
            6,
            350,
            8600,
            7,
            0,
            "pi",
            5,
            1000,
            4200,
            1,
            5,
            1,
            3,
            "magazine",
            10,
            -5,
            4,
            "bolt-action-rifle-762-round",
        ),
        (
            "self-loading-rifle-762",
            6,
            600,
            9500,
            7,
            0,
            "pi",
            5,
            1000,
            4200,
            3,
            8,
            0,
            3,
            "magazine",
            10,
            -5,
            3,
            "self-loading-rifle-762-round",
        ),
        (
            "assault-rifle-556",
            7,
            800,
            8000,
            5,
            0,
            "pi",
            5,
            500,
            3500,
            12,
            30,
            1,
            3,
            "magazine",
            9,
            -4,
            2,
            "assault-rifle-556-round",
        ),
        (
            "assault-rifle-762s",
            7,
            300,
            8700,
            5,
            1,
            "pi",
            4,
            400,
            3000,
            10,
            30,
            1,
            3,
            "magazine",
            10,
            -4,
            2,
            "assault-rifle-762s-round",
        ),
        (
            "battle-rifle-762",
            7,
            900,
            9300,
            7,
            0,
            "pi",
            5,
            1000,
            4200,
            11,
            20,
            1,
            3,
            "magazine",
            11,
            -5,
            3,
            "battle-rifle-762-round",
        ),
        (
            "assault-carbine-556",
            8,
            900,
            6300,
            4,
            2,
            "pi",
            4,
            400,
            3000,
            15,
            30,
            1,
            3,
            "magazine",
            9,
            -3,
            2,
            "assault-carbine-556-round",
        ),
    )
)

FIREARM_AMMUNITION = tuple(
    EquipmentProfile(
        definition_id="equipment:" + identifier,
        provenance=source(278),
        weight_millipounds=weight,
        price=price,
        technology_level=tl,
        ammunition=True,
    )
    for identifier, tl, price, weight in (
        ("flintlock-pistol-51-round", 4, Decimal("0.2"), 10),
        ("wheel-lock-pistol-60-round", 4, Decimal("0.2"), 10),
        ("derringer-41-round", 5, 1, 50),
        ("revolver-36-round", 5, Decimal("0.8"), 40),
        ("snub-revolver-38-round", 6, Decimal("0.8"), 40),
        ("auto-pistol-45-tl6-round", 6, Decimal("1.5"), 75),
        ("auto-pistol-9mm-tl6-round", 6, Fraction(8, 9), Fraction(400, 9)),
        ("revolver-38-round", 6, Fraction(2, 3), Fraction(100, 3)),
        ("auto-pistol-9mm-tl7-round", 7, Decimal("0.8"), 40),
        ("holdout-pistol-380-round", 7, Decimal("0.8"), 40),
        ("revolver-357m-round", 7, Decimal("0.7"), 35),
        ("revolver-44m-round", 7, 1, 50),
        ("auto-pistol-44m-round", 8, Fraction(4, 3), Fraction(200, 3)),
        ("auto-pistol-40-round", 8, Fraction(14, 15), Fraction(140, 3)),
        ("machine-pistol-9mm-round", 7, Fraction(22, 25), 44),
        ("smg-9mm-tl6-round", 6, Fraction(15, 16), Fraction(375, 8)),
        ("smg-45-round", 6, Fraction(49, 25), 98),
        ("smg-9mm-tl7-round", 7, Decimal("0.8"), 40),
        ("pdw-46-round", 8, Decimal("0.5"), 25),
    )
)

LONG_GUN_AMMUNITION = tuple(
    EquipmentProfile(
        definition_id="equipment:" + identifier,
        provenance=source(279),
        weight_millipounds=weight,
        price=price,
        technology_level=tl,
        ammunition=True,
    )
    for identifier, tl, price, weight in (
        ("handgonne-90-round", 3, 2, 100),
        ("flintlock-musket-75-round", 4, 1, 50),
        ("rifle-musket-577-round", 5, 1, 50),
        ("cartridge-rifle-45-round", 5, 2, 100),
        ("lever-action-carbine-30-round", 5, 1, 50),
        ("bolt-action-rifle-762-round", 6, Fraction(6, 5), 60),
        ("self-loading-rifle-762-round", 6, Fraction(5, 4), Fraction(125, 2)),
        ("assault-rifle-556-round", 7, Fraction(2, 3), Fraction(100, 3)),
        ("assault-rifle-762s-round", 7, Fraction(6, 5), 60),
        ("battle-rifle-762-round", 7, Fraction(17, 10), 85),
        ("assault-carbine-556-round", 8, Fraction(2, 3), Fraction(100, 3)),
    )
)

SHOTGUN_AMMUNITION = tuple(
    EquipmentProfile(
        definition_id="equipment:" + identifier,
        provenance=source(279),
        weight_millipounds=weight,
        price=price,
        technology_level=tl,
        ammunition=True,
    )
    for identifier, tl, price, weight in (
        ("blunderbuss-8g-round", 4, Decimal("2.6"), 130),
        ("double-shotgun-10g-round", 5, 1, 50),
        ("pump-shotgun-12g-round", 6, Decimal("2.8"), 140),
        ("auto-shotgun-12g-round", 7, Fraction(17, 7), Fraction(850, 7)),
    )
)

HIGHER_TL_WEAPONS = (
    ranged_weapon(
        "gyroc-pistol-15mm",
        278,
        9,
        200,
        600,
        RangedMode(
            id="shot",
            skill_id="skill:guns-gyroc",
            minimum_st=9,
            damage=Damage(basis="fixed", dice=6, damage_type="pi++"),
            accuracy=1,
            range_basis="yards",
            maximum_range=1900,
            rate_of_fire=3,
            shots=4,
            reload_seconds=3,
            reload_protocol="per-round",
            bulk=-2,
            recoil=1,
            ammunition_id="equipment:gyroc-pistol-15mm-round",
            firearm=FirearmSpec(
                technology_level=9,
                action="repeating",
                armoury_skill_id="skill:armoury-small-arms",
            ),
            rocket_acceleration=RocketAcceleration(
                close_max_yards=2,
                close_damage_divisor=3,
                medium_max_yards=10,
                medium_damage_divisor=2,
            ),
            smartgun=SmartgunSpec(),
        ),
    ),
    ranged_weapon(
        "laser-pistol",
        280,
        10,
        2800,
        2800,
        RangedMode(
            id="beam",
            skill_id="skill:beam-weapons-pistol",
            minimum_st=6,
            damage=Damage(
                basis="fixed",
                dice=3,
                damage_type="burn",
                armor_divisor=Decimal(2),
                tight_beam=True,
            ),
            accuracy=6,
            range_basis="yards",
            half_damage_range=250,
            maximum_range=750,
            rate_of_fire=10,
            shots=400,
            reload_seconds=3,
            bulk=-2,
            recoil=1,
            ammunition_id="equipment:laser-pistol-cell",
            firearm=FirearmSpec(
                technology_level=10,
                action="beam",
                armoury_skill_id="skill:armoury-small-arms",
            ),
            smartgun=SmartgunSpec(),
            beam_environment_dr=True,
        ),
    ),
)

HIGHER_TL_AMMUNITION = (
    EquipmentProfile(
        definition_id="equipment:gyroc-pistol-15mm-round",
        provenance=source(278),
        weight_millipounds=100,
        price=2,
        technology_level=9,
        ammunition=True,
    ),
    EquipmentProfile(
        definition_id="equipment:laser-pistol-cell",
        provenance=source(280),
        weight_millipounds=500,
        price=10,
        technology_level=10,
        ammunition=True,
        power_cell_capacity=400,
    ),
)

# B283: complete rigid, unsplit body-armor rows without special footnotes.
ARMOR = tuple(
    EquipmentProfile(
        definition_id=identifier,
        provenance=source(283),
        technology_level=tl,
        weight_millipounds=weight,
        price=price,
        slot="body",
        armor=Armor(locations=cast(tuple[Location, ...], locations), dr=dr),
    )
    for identifier, tl, price, weight, locations, dr in (
        ("equipment:bronze-corselet", 1, 1300, 40000, ("torso", "groin"), 5),
        ("equipment:leather-armor", 1, 100, 10000, ("torso", "groin"), 2),
        ("equipment:light-scale-armor", 2, 150, 15000, ("torso",), 3),
        ("equipment:lorica-segmentata", 2, 680, 26000, ("torso",), 5),
        ("equipment:scale-armor", 2, 420, 35000, ("torso", "groin"), 4),
        ("equipment:heavy-steel-corselet", 3, 2300, 45000, ("torso", "groin"), 7),
        ("equipment:steel-corselet", 3, 1300, 35000, ("torso", "groin"), 6),
        ("equipment:steel-laminate-plate", 3, 900, 30000, ("torso", "groin"), 5),
    )
)

# B287: ordinary shield rows. Durability uses the table's explicit DR/HP
# columns rather than deriving HP from weight. Cloaks are the same physical
# rows already recorded on B276; the superscience force shield cannot fit the
# integer TL or finite-HP schema and remains an explicit audit omission.
SHIELDS = tuple(
    EquipmentProfile(
        definition_id=identifier,
        provenance=source(287),
        technology_level=tl,
        weight_millipounds=weight,
        price=price,
        slot="shield",
        shield=Shield(skill_id="skill:shield", defense_bonus=db),
        durability=ObjectProfile(construction="homogenous", hp=hp, dr=dr, ht=12),
    )
    for identifier, tl, db, price, weight, dr, hp in (
        ("equipment:light-shield", 0, 1, 25, 2000, 5, 20),
        ("equipment:small-shield", 0, 1, 40, 8000, 6, 30),
        ("equipment:medium-shield", 1, 2, 60, 15000, 7, 40),
        ("equipment:large-shield", 1, 3, 90, 25000, 9, 60),
    )
)

SUPERSCIENCE_SHIELDS = (
    EquipmentProfile(
        definition_id="equipment:force-shield",
        provenance=source(287),
        technology_level="superscience",
        price=1500,
        weight_millipounds=500,
        unsupported_mechanics=(
            "superscience-technology-level",
            "shield-material-variants",
        ),
    ),
)

# B288-289: fixed-TL inventory facts. Behavioral requirements keep special tools
# out of active packages until their mechanics are integrated; no invented
# skill/effect hooks. Rows printed with ``TL Var.`` remain ledger omissions
# because the catalog currently requires one concrete technology level.
ORDINARY = tuple(
    EquipmentProfile(
        definition_id=identifier,
        provenance=source(page),
        technology_level=cast(TechnologyLevel, tl),
        price=price,
        weight_millipounds=weight,
        container_capacity_millipounds=capacity,
        unsupported_mechanics=missing,
    )
    for identifier, page, tl, price, weight, capacity, missing in (
        # Camping and survival gear, B288.
        ("equipment:frame-backpack", 288, 1, 100, 10000, 100000, ()),
        ("equipment:small-backpack", 288, 1, 60, 3000, 40000, ()),
        ("equipment:blanket", 288, 1, 20, 4000, None, ()),
        ("equipment:ceramic-bottle", 288, 1, 3, 1000, 2000, ()),
        ("equipment:steel-cable-15", 288, 5, 100, 17000, None, ("special-tool-effects",)),
        ("equipment:camp-stove", 288, 6, 50, 2000, None, ("fuel-consumption",)),
        ("equipment:tallow-candle", 288, 1, 5, 1000, None, ("fuel-consumption",)),
        ("equipment:canteen", 288, 5, 10, 1000, 2000, ()),
        ("equipment:cigarette-lighter", 288, 6, 10, 0, None, ("special-tool-effects",)),
        ("equipment:climbing-gear", 288, 2, 20, 4000, None, ("special-tool-effects",)),
        ("equipment:compass", 288, 6, 50, 0, None, ("special-tool-effects",)),
        ("equipment:cord-3-16", 288, 0, 1, 500, None, ("special-tool-effects",)),
        ("equipment:fishhooks-and-line", 288, 0, 50, 0, None, ("special-tool-effects",)),
        ("equipment:heavy-flashlight", 288, 6, 20, 1000, None, ("battery-and-computer-operation",)),
        ("equipment:mini-flashlight", 288, 7, 10, 250, None, ("battery-and-computer-operation",)),
        ("equipment:gasoline-gallon", 288, 6, Decimal("1.5"), 6000, None, ("fuel-consumption",)),
        (
            "equipment:gps-receiver",
            288,
            8,
            200,
            3000,
            None,
            ("battery-and-computer-operation", "special-tool-effects"),
        ),
        ("equipment:grapnel", 288, 5, 20, 2000, None, ("special-tool-effects",)),
        ("equipment:group-basics", 288, 0, 50, 20000, None, ("special-tool-effects",)),
        ("equipment:iron-spike", 288, 2, 1, 500, None, ("special-tool-effects",)),
        ("equipment:kerosene-gallon", 288, 6, Decimal("1.5"), 6000, None, ("fuel-consumption",)),
        ("equipment:lantern", 288, 2, 20, 2000, None, ("fuel-consumption",)),
        ("equipment:life-jacket", 288, 6, 100, 6000, None, ("special-tool-effects",)),
        (
            "equipment:waterproof-matches-50",
            288,
            6,
            Decimal("1.5"),
            0,
            None,
            ("special-tool-effects",),
        ),
        ("equipment:lantern-oil-pint", 288, 2, 2, 1000, None, ("fuel-consumption",)),
        ("equipment:parachute", 288, 6, 1000, 30000, None, ("special-tool-effects",)),
        ("equipment:personal-basics", 288, 0, 5, 1000, None, ("special-tool-effects",)),
        ("equipment:six-foot-pole", 288, 0, 5, 3000, None, ()),
        ("equipment:ten-foot-pole", 288, 0, 8, 5000, None, ()),
        ("equipment:small-pouch", 288, 1, 10, 0, 3000, ()),
        ("equipment:rope-3-8", 288, 0, 5, 1500, None, ("special-tool-effects",)),
        ("equipment:rope-3-4", 288, 1, 25, 5000, None, ("special-tool-effects",)),
        ("equipment:scuba-gear", 288, 6, 1500, 32000, None, ("special-tool-effects",)),
        ("equipment:sleeping-bag", 288, 6, 25, 7000, None, ()),
        ("equipment:insulated-sleeping-bag", 288, 7, 100, 15000, None, ("cold-resistance-bonus",)),
        ("equipment:sleeping-fur", 288, 0, 50, 8000, None, ()),
        ("equipment:hard-suitcase", 288, 5, 250, 8000, 100000, ("special-tool-effects",)),
        ("equipment:one-man-tent", 288, 0, 50, 5000, None, ()),
        ("equipment:two-man-tent", 288, 0, 80, 12000, None, ()),
        ("equipment:four-man-tent", 288, 0, 150, 30000, None, ()),
        ("equipment:twenty-man-tent", 288, 1, 300, 100000, None, ()),
        ("equipment:thermos-bottle", 288, 5, 10, 2000, None, ("special-tool-effects",)),
        ("equipment:torch", 288, 0, 3, 1000, None, ("fuel-consumption",)),
        ("equipment:travelers-ration", 288, 0, 2, 500, None, ()),
        ("equipment:water-purification-tablets-50", 288, 6, 5, 0, None, ("special-tool-effects",)),
        ("equipment:wineskin", 288, 0, 10, 250, 8000, ()),
        ("equipment:wristwatch", 288, 6, 20, 0, None, ()),
        # Communications and information gear, B288-289.
        ("equipment:battery", 288, 6, 1, 0, None, ("battery-and-computer-operation",)),
        (
            "equipment:cell-phone",
            288,
            8,
            250,
            250,
            None,
            ("battery-and-computer-operation", "special-tool-effects"),
        ),
        ("equipment:laptop", 288, 8, 1500, 3000, None, ("battery-and-computer-operation",)),
        (
            "equipment:wearable-computer",
            288,
            8,
            1000,
            2000,
            None,
            ("battery-and-computer-operation",),
        ),
        ("equipment:drum", 288, 0, 40, 2000, None, ("special-tool-effects",)),
        ("equipment:mini-recorder", 288, 7, 200, 500, None, ("battery-and-computer-operation",)),
        ("equipment:mini-recorder-tape", 288, 7, 5, 0, None, ()),
        (
            "equipment:digital-mini-recorder",
            288,
            8,
            30,
            500,
            None,
            ("battery-and-computer-operation",),
        ),
        (
            "equipment:backpack-radio",
            288,
            7,
            6000,
            15000,
            None,
            ("battery-and-computer-operation", "special-tool-effects"),
        ),
        (
            "equipment:hand-radio",
            288,
            7,
            100,
            1000,
            None,
            ("battery-and-computer-operation", "special-tool-effects"),
        ),
        (
            "equipment:headset-radio",
            288,
            8,
            500,
            500,
            None,
            ("battery-and-computer-operation", "special-tool-effects"),
        ),
        (
            "equipment:secure-headset-radio",
            288,
            8,
            5000,
            500,
            None,
            ("battery-and-computer-operation", "special-tool-effects"),
        ),
        (
            "equipment:satellite-phone",
            288,
            8,
            3000,
            3000,
            None,
            ("battery-and-computer-operation", "special-tool-effects"),
        ),
        ("equipment:scribes-kit", 288, 3, 50, 2000, None, ()),
        ("equipment:transistor-radio", 288, 7, 15, 500, None, ("battery-and-computer-operation",)),
        ("equipment:mini-tv", 288, 7, 150, 3000, None, ("battery-and-computer-operation",)),
        ("equipment:manual-typewriter", 289, 6, 200, 10000, None, ()),
        ("equipment:wax-tablet", 289, 1, 10, 2000, None, ()),
        # Equestrian gear, B289.
        ("equipment:bit-and-bridle", 289, 1, 35, 3000, None, ("special-tool-effects",)),
        ("equipment:horseshoes", 289, 3, 50, 4000, None, ("special-tool-effects",)),
        ("equipment:saddle-and-tack", 289, 2, 150, 15000, None, ("special-tool-effects",)),
        ("equipment:saddlebags", 289, 1, 100, 3000, 40000, ()),
        ("equipment:spurs", 289, 2, 25, 0, None, ("special-tool-effects",)),
        ("equipment:stirrups", 289, 3, 125, 20000, None, ("special-tool-effects",)),
        ("equipment:war-saddle", 289, 3, 250, 35000, None, ("special-tool-effects",)),
        # Law-enforcement, thief and spy gear, B289.
        (
            "equipment:audio-bug",
            289,
            7,
            200,
            0,
            None,
            ("battery-and-computer-operation", "special-tool-effects"),
        ),
        (
            "equipment:bug-stomper",
            289,
            7,
            1200,
            2000,
            None,
            ("battery-and-computer-operation", "special-tool-effects"),
        ),
        ("equipment:disguise-kit", 289, 5, 200, 10000, None, ("special-tool-effects",)),
        ("equipment:electronic-lockpicks", 289, 7, 1500, 3000, None, ("special-tool-effects",)),
        ("equipment:handcuffs", 289, 5, 40, 500, None, ("special-tool-effects",)),
        (
            "equipment:homing-beacon",
            289,
            7,
            40,
            0,
            None,
            ("battery-and-computer-operation", "special-tool-effects"),
        ),
        ("equipment:laser-microphone", 289, 8, 500, 2000, None, ("special-tool-effects",)),
        ("equipment:lockpicks", 289, 3, 50, 0, None, ("special-tool-effects",)),
        ("equipment:nanobug", 289, 8, 100, 0, None, ("special-tool-effects",)),
        ("equipment:shotgun-microphone", 289, 6, 250, 2000, None, ("special-tool-effects",)),
        # Optics and sensors, B289.
        ("equipment:binoculars", 289, 6, 400, 2000, None, ("special-tool-effects",)),
        (
            "equipment:camcorder",
            289,
            8,
            1000,
            1000,
            None,
            ("battery-and-computer-operation", "special-tool-effects"),
        ),
        ("equipment:camera-35mm", 289, 6, 50, 3000, None, ("special-tool-effects",)),
        ("equipment:camera-film-32", 289, 6, 10, 0, None, ()),
        (
            "equipment:metal-detector-wand",
            289,
            7,
            50,
            1000,
            None,
            ("battery-and-computer-operation", "special-tool-effects"),
        ),
        ("equipment:digital-mini-camera", 289, 8, 500, 0, None, ("special-tool-effects",)),
        (
            "equipment:night-vision-goggles",
            289,
            8,
            600,
            2000,
            None,
            ("battery-and-computer-operation", "special-tool-effects"),
        ),
        ("equipment:spy-camera", 289, 6, 500, 0, None, ("special-tool-effects",)),
        ("equipment:telescope", 289, 4, 500, 6000, None, ("special-tool-effects",)),
        # Fixed-TL tools, B289.
        ("equipment:balance-and-weights", 289, 1, 35, 3000, None, ("special-tool-effects",)),
        ("equipment:three-foot-crowbar", 289, 2, 20, 3000, None, ("special-tool-effects",)),
        ("equipment:cutting-torch", 289, 6, 500, 30000, None, ("special-tool-effects",)),
        ("equipment:cutting-torch-gas-bottle", 289, 6, 50, 15000, None, ("fuel-consumption",)),
        ("equipment:knitting-needles", 289, 3, 5, 0, None, ()),
        ("equipment:pickaxe", 289, 2, 15, 8000, None, ("special-tool-effects",)),
        ("equipment:iron-plow", 289, 2, 220, 120000, None, ("special-tool-effects",)),
        ("equipment:wooden-plow", 289, 1, 55, 60000, None, ("special-tool-effects",)),
        ("equipment:saw", 289, 0, 150, 3000, None, ("special-tool-effects",)),
        ("equipment:shovel", 289, 1, 12, 6000, None, ("special-tool-effects",)),
        ("equipment:spinning-wheel", 289, 3, 100, 40000, None, ("special-tool-effects",)),
        ("equipment:wheelbarrow", 289, 2, 60, 18000, 350000, ("special-tool-effects",)),
        ("equipment:whetstone", 289, 1, 5, 1000, None, ("special-tool-effects",)),
        # Skill-relative and portable specialist kits, B289.
        (
            "equipment:bandages",
            289,
            "skill-relative",
            10,
            2000,
            None,
            ("technology-level-variants", "special-tool-effects"),
        ),
        (
            "equipment:crash-kit",
            289,
            "skill-relative",
            200,
            10000,
            None,
            ("technology-level-variants", "special-tool-effects"),
        ),
        (
            "equipment:first-aid-kit",
            289,
            "skill-relative",
            50,
            2000,
            None,
            ("technology-level-variants", "special-tool-effects"),
        ),
        (
            "equipment:surgical-instruments",
            289,
            "skill-relative",
            300,
            15000,
            None,
            ("technology-level-variants", "special-tool-effects"),
        ),
        (
            "equipment:portable-carpentry-tool-kit",
            289,
            1,
            300,
            20000,
            None,
            ("special-tool-effects",),
        ),
        (
            "equipment:portable-armoury-tool-kit",
            289,
            1,
            600,
            20000,
            None,
            ("special-tool-effects",),
        ),
        (
            "equipment:portable-explosives-tool-kit",
            289,
            5,
            600,
            20000,
            None,
            ("special-tool-effects",),
        ),
        (
            "equipment:portable-machinist-tool-kit",
            289,
            5,
            600,
            20000,
            None,
            ("special-tool-effects",),
        ),
        (
            "equipment:portable-mechanic-tool-kit",
            289,
            5,
            600,
            20000,
            None,
            ("special-tool-effects",),
        ),
        (
            "equipment:portable-electrician-tool-kit",
            289,
            6,
            600,
            20000,
            None,
            ("special-tool-effects",),
        ),
        (
            "equipment:portable-electronics-repair-tool-kit",
            289,
            6,
            1200,
            10000,
            None,
            ("special-tool-effects",),
        ),
        (
            "equipment:suitcase-lab",
            289,
            "skill-relative",
            3000,
            10000,
            None,
            ("technology-level-variants", "special-tool-effects"),
        ),
        # Weapon and combat accessories, B289.
        ("equipment:ear-muffs", 289, 6, 200, 1000, None, ("weapon-accessories",)),
        ("equipment:hip-quiver", 289, 0, 15, 1000, None, ("weapon-accessories",)),
        ("equipment:belt-holster", 289, 5, 25, 500, None, ("weapon-accessories",)),
        ("equipment:shoulder-holster", 289, 5, 50, 1000, None, ("weapon-accessories",)),
        ("equipment:leather-lanyard", 289, 0, 1, 0, None, ("weapon-accessories",)),
        ("equipment:woven-steel-lanyard", 289, 6, 15, 0, None, ("weapon-accessories",)),
        (
            "equipment:laser-sight",
            289,
            8,
            100,
            0,
            None,
            ("weapon-accessories", "battery-and-computer-operation"),
        ),
        ("equipment:scope-4x", 289, 6, 150, 1500, None, ("weapon-accessories",)),
        (
            "equipment:thermal-scope-4x",
            289,
            8,
            8000,
            4000,
            None,
            ("weapon-accessories", "battery-and-computer-operation"),
        ),
        ("equipment:shoulder-quiver", 289, 0, 10, 500, None, ("weapon-accessories",)),
        ("equipment:pistol-smg-silencer", 289, 6, 400, 1000, None, ("weapon-accessories",)),
        ("equipment:web-gear", 289, 6, 50, 2000, None, ("weapon-accessories",)),
    )
)

BASIC_EQUIPMENT = EquipmentCatalog(
    profile_id="gurps-basic-set-4e-2004",
    entries=(
        WEAPONS
        + SUPERSCIENCE_MELEE
        + MUSCLE_POWERED_RANGED
        + MUSCLE_POWERED_AMMUNITION
        + FIREARMS
        + ORDINARY_HANDGUNS
        + ORDINARY_SMGS
        + REPEATING_RIFLES
        + FIREARM_AMMUNITION
        + LONG_GUN_AMMUNITION
        + SHOTGUN_AMMUNITION
        + HIGHER_TL_WEAPONS
        + HIGHER_TL_AMMUNITION
        + ARMOR
        + SHIELDS
        + SUPERSCIENCE_SHIELDS
        + ORDINARY
    ),
)

# B280: unresolved ultra-tech index entries carry facts but cannot be activated.
ULTRATECH_INDEX = tuple(
    EquipmentProfile(
        definition_id=identifier,
        provenance=source(280),
        technology_level=tl,
        price=price,
        weight_millipounds=weight,
        unsupported_mechanics=missing,
    )
    for identifier, tl, price, weight, missing in (
        (
            "equipment:electrolaser-pistol",
            9,
            1800,
            2200,
            ("linked-affliction", "surge"),
        ),
        ("equipment:blaster-pistol", 11, 2200, 1600, ("surge",)),
    )
)

# Vehicle listing is deliberately separate from wearable/carryable equipment.
# Campaigns fourth printing B464; masses are loaded tons, never inventory lbs.


class VehicleEntry(Record):
    definition_id: Id
    page: int = 464
    edition: str = "Campaigns Fourth Edition, fourth printing"
    technology_level: int = Field(ge=0)
    hp: int = Field(gt=0)
    dr: int = Field(ge=0)
    price: int = Field(ge=0)
    required_capabilities: tuple[str, ...] = ("gurps.vehicles.movement", "gurps.vehicles.combat")

    def require_operation(self) -> None:
        # #120 closed without the operation integration; #358 owns the two
        # capability rows a listed vehicle would need before it can be driven.
        raise ValidationError("Vehicle listing does not implement operation; see #358")


VEHICLE_INDEX = (
    VehicleEntry(definition_id="vehicle:wagon", technology_level=3, hp=35, dr=2, price=680),
    VehicleEntry(definition_id="vehicle:luxury-car", technology_level=8, hp=57, dr=5, price=30000),
)
